### ISSUE TITLE
Coding assistance for developing apps with Jakarta EE 9/9.1 Web Profile APIs

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/open-liberty#10353]
Provide developers with coding assistance (e.g., validations, auto completion, quick fixes, code snippets) to write cloud-native Java applications using Jakarta EE 9/9.1 Web Profile APIs.

A solution is to build a language server with the community for Jakarta EE (like through Eclipse LSP4Jakarta project) to assist developers to build applications with the programming model.  We will focus on Web Profile APIs first.

## Description

Solution provides a language server implementation for the JakartaEE specification. This language server implementations solution is  managed from a new community Eclipse LSP4Jakarta project to assist developers in building applications with the JakartaEE programming model.  We will focus on Web Profile APIs first.

The solution implements the Language Server Protocol specifically for the JakartaEE Programming model. 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Note on Checklist for non-runtime feature

Took some liberties in deleting, ignoring, marking N/A sections that did not seem to apply to a tooling (rather than a runtime) deliverable, while realizing this isn't the only way to interpret or map the runtime process onto tooling.   Still left some aspects like the ID and SVT focal approval, and of course the whole UFO process.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Documents

- Aha: Externally raised RFE - N/A
- UFO: https://ibm.ent.box.com/file/980757432199
- FTS: 
- Beta 
- GA Blog: 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
### **Design Preliminaries**
- [X] ID requirements identified. (Epic owner / Feature owner with ID focal point) Doc [issue]()
- [X] Serviceability Requirements Identified. (Owner and [Serviceability focal point](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
- [X] SVT Requirements Identified. (Epic owner / Feature owner with SVT focal point) SVT [epic](https://github.ibm.com/websphere/system-test/issues/600)
- [X] Performance testing requirements identified.

### **Design**
- [X] POC Design / UFO review requested.
- [X] POC Design / UFO review scheduled.
- [X] POC Design / UFO review completed.
- [X] POC / UFO Review follow-ons completed.
- [X] POC Design / UFO approval requested.
- [X] Design / UFO approved. 
  - The UFO must always accurately reflect the final implementation of the feature. Any changes must be first approved. Afterwards, update the UFO by creating a copy of the original approved slide(s) at the end of the deck and prepend "OLD" to the title(s). A single updated copy of the slide(s) should take the original's place, and have its title(s) prepended with "UPDATED".

### **FAT Documentation**
- [X] "Feature Test Summary" child task created

## **Legal and Translation**

In order to avoid last minute blockers and significant disruptions to the feature, the **legal items need to be done as early in the feature process as possible**, either in design or as early into the development as possible.  Similarly, translation is to be done concurrently with development.  Both **MUST** be completed before Beta or GA is requested.

### **Legal** (Complete before Feature Complete Date)
- [X] Changed or new open source libraries are cleared and approved, or N/A. (Legal Release Services/Cass Tucker/Release PM).
- [X] Licenses and Certificates of Originality (COOs) are updated, or N/A: 
- OUR WORK: Went through initial PTC scan in October. Delta scan will happen 11/25. The license is EPL 2 since this is an open source offering, and there will be no COO.

### **Translation** (Complete 1 week before Feature Complete Date)
- [X] N/A 

### **Innovation** (Complete 1 week before Feature Complete Date)
- [X] Consider whether any aspects of the feature may be patentable. If any identified, disclosures have been submitted.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Beta**

In order to facilitate early feedback from users, all new features and functionality should first be released as part of a beta release.

### **Beta Code**
- Did release as Early Release as noted in beta blog post

## **GA**

A feature is ready to GA after it is Feature Complete and has obtained all necessary Focal Point Approvals. 

### **Feature Complete**
- [X] Feature implementation and tests completed.
  - [X] All PRs are merged.
  - [X] All epic and child issues are closed.
  - [X] All stop ship issues are completed.
- [X] Legal: all necessary approvals granted.
- [X ] Translation: N/A
- [X] GA development complete and feature ready for inclusion in a GA release

### **Focal Point Approvals** (Complete by Feature Complete Date)

- [X] **Demo** Demo is scheduled for an upcoming EOI or N/A. 

### **Design Approved Features**

- [x] **ID** Documentation 
- [X] **Performance**: N/A
- [X] **Serviceability**: N/A
- [X] **STE**: N/A
- [x] **SVT** 
  - Approver adds label `focalApproved:svt`.

### **GA Blog** (Complete by Feature Complete Date)
- [X] GA Blog issue created and populated 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Other Deliverables**

- [X] **Standalone Feature Blog Post** N/A
- [X] **OL Guides**  N/A
- [X] **Dev Experience** Developer Experience & Tools work is complete or N/A. ([OpenLiberty/dev-experience-assessment](https://github.com/orgs/OpenLiberty/teams/dev-experience-assessment/members))

**Comment by angelozerr** [comment]
I think JDT LS is the language server that you wish to have, no?

**Comment by yeekangc** [comment]
This is more looking at what more beyond the JDT LS that the community may want to consider for Jakarta EE.

**Comment by yeekangc** [comment]
@kathrynkodama is working on the first draft of the UFO.

**Comment by kathrynkodama** [comment]
UFO: https://ibm.box.com/s/wnux2tmy5hwzu81pfml98u2uqbrzagtn

The following updates have been made to the UFO following the review:
Slide 18: Highlighted the Language Clients in the image 
Slide 32 and 38: Updated to clarify what will be done as part of LSP4Jakarta

**Comment by kathrynkodama** [comment]
@NottyCode Updated Slide 34 (Platform/Cloud Considerations) to indicate that for the first release we will be targeting Java 17 and Eclipse 22.0.0.9. 
cc: @yeekangc

**Comment by yeekangc** [comment]
Discussed with @scottkurz that @ajm01 will take over ownership of this item.

**Comment by yeekangc** [comment]
@ajm01, can you please go over the checklist and take this for closure?  Thank you.

**Comment by yeekangc** [comment]
Closing as done.
