### ISSUE TITLE
XFS prevention with settable permitted HTTP response headers

### ISSUE THREAD

**Issue by smikishk** [OpenLiberty/open-liberty#10483]
In order to prevent cross frame scripting (XFS), we would like the ability to set http response headers via server configuration.  We can set the header in the http response via java application code, but the application code will not fire until an authenticated requests passes through J2EE security with openidconnectclient-1.0.  By the time we set the response, it may be too late where an rogue application loads the vulnerable application via iframe.

Specifically, we would like to set the "X-Frame-Options" header.  To take the enhancement even further, it would be nice if the Liberty web container could set generic headers as there is a growing use case of running on a cloud platform without a configurable HTTP server out front.  Additionally, browser standards and headers change very quickly over time.

The application itself is secured, but it is possible through social engineering that Liberty OIDC Client could redirect a client to the OpenID Provider to intercept credentials before the header has been set.

An alternative solution would be to add a standard web server in front of Liberty that could set specific headers for all responses.  We primarily run on cloud platforms that do not have configurable web servers, or where adding one would incur an additional infrastructure cost.

This request for enhancement would allow generic HTTP response headers to be set for all requests, both unauthenticated and authenticated.

UFO: https://ibm.box.com/s/wd4zl0wkprnhd6urinn4x5kwbyb2xclp
Existing RFE: https://cloud-platform.ideas.aha.io/ideas/TWAS-I-165
FAT Test Summary: https://github.com/openliberty/open-liberty/issues/18109

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)
 
Instructions:
 - Do the actions below and mark them complete in the checklist when they are done.
 - Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **Before Development Starts or 8 weeks before Onboarding** 
- [x] POC Design / WAD Review Scheduled (David Chang) or N/A.
- [x] POC Design / WAD Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / WAD Approval (Alasdair Nottingham) or N/A.
- [x] No Design / No WAD Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of the epic entitled "FAT Approval Test Summary".  Add and fill in the template as described here: https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **3 weeks before Onboarding** 
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE ** 3 weeks before Onboarding** 
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **2 weeks before Onboarding** 
- [x] Implementation complete. (Epic owner / Feature owner) 
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## APPROVALS with TARGET COMPLETION DATE **2 to 1 week before Onboarding** 
Prereq: You must have the Design Approved or No Design Approved label on the GitHub Epic.
- [x] **Accessibility** - (Steven Zvonek). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **FAT Liberty SOE** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Globalization** (Sam Wong - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.
- [x] **ID** - (Kareen Deen). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - (Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - (Don Bourne). Serviceability has been addressed. 
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - (Greg Ecock - Cloud, Brian Hanczaryk- APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.
- [x] **Demo** - (Liberty only - Tom Evans or Chuck Bridgham). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## TARGET COMPLETION DATE **1 week before Onboarding** 
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [x] Github Epic and Epic's issues are closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / Backlog Subtribe PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## NOT REQUIRED FOR A FEATURE
- [x] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A. 
- [x] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Related Deliverables TARGET COMPLETION DATE **General Availability** 
- [x] Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by pnicolucci** [comment]
@jtmulvey , we have a similar RFE here: https://www.ibm.com/developerworks/rfe/execute?use_case=viewChangeRequest&CR_ID=80739

**Comment by mrsaldana** [comment]
Will be addressed by #12529

**Comment by garypicher** [comment]
Design review comments:

- Overview slide:
  - Make it clear that headers element is inside an http endpoint.

- Feature Design slide:
  - Ensure that one of your tests involves symbolic variables for the value of an HTTP header.  We think this support will come for free, but it needs to be verified.
  - Show an example of a header where you'd want to use "add" twice to set the same header two times with different values.

- Feature Design discussion needed:
  - How does priority work with respect to headers defined in the config in this new way versus headers set by the application?  Which one takes precedence?
  - Should we log whenever there's a conflict and we need to choose which one takes precedence?  
  - Do we need a config setting to determine which takes precedence?
  - Alasdair would like us to add a "remove" element that removes any headers with the specified name, to go alone with the "add" and "set" elements that are being proposed.
  - Update the UFO to reflect all of the design choices that need to be resolved, and then check with Alasdair to see if a follow-on UFO review is needed.

- Platform Considerations slide
  - Talk about using kubernetes config maps to set these values into a liberty config.

- Testing
  - Make sure that we test the specific customer situation that this is being added in support of.  An automated test is preferred, if possible.

**Comment by mrsaldana** [comment]
With regards to outstanding comments: 

**How does priority work with respect to headers defined in the config in this new way versus headers set by the application? Which one takes precedence? Also in the same line, should we log whenever there's a conflict and we need to choose which one takes precedence.**
 
- The proposal is for the configuration to be applied during the HTTP transport's header compliance method. This is done at the very end of the request/response cycle, just before the transport hands off the data buffers down to the TCP channel to be written out to the underlying socket connection. Historically, this method has been used to add other headers, like cache control, making it a natural place for the configuration to be consumed.
 
Additionally, the remove header option would almost be a moot point if the transport would apply the configuration before the application layer, since then the header might not be present when evaluated at the transport, and then added at a later point by the application layer. As such, the proposal is for the presentation layer (Web Container, application, etc) to add/set headers first and for the transport layer to apply the configuration after control has been handed back. The `add `option appends values, so there is no conflict regarding precedence. The conflict would then be with the `set` option, since whichever layer is called last will overwrite the first. To address this, customers can make use of the `setIfMissing` option to ensure the value set by the transport doesn't overwrite the value set by their application/filters, since it will only set it when not already present.
 
**Do we need a config setting to determine precedence?**
 
- I believe the current proposal should avoid issues with precedence. In addition, the `remove `option would not be optimal if it were applied before the presentation layer modifies the response. As such, I'm of the opinion of not adding a precedence switch option.
 
**Add a "remove" element to go along with the "add" and "set" attributes being proposed.**
 
- The `remove `option has been added, as well as a `setIfMissing` to address precedence conflicts.
 
 
A sample configuration that adds a header and removes another header would look like:
 
```
<httpEndpoint host="*" httpPort=9080 https=9443>
    <headers>
            <add>${desired.add.response.header}</add>
            <remove>${desired.remove.response.header}</remove>
     </headers>
</httpEndpoint>
```
 
Similar to other configuration options in the <httpEndpoint> the options can also be provided in element/attribute form, such as:
`<headers add="foo:bar, foo2:bar2" remove="Via"/>`
 
These values can be hard coded, or externalized and supplied by bootstrap, or by making use of the mpConfig feature.

**Comment by skasund** [comment]
L2 has requested STE slides for this feature.  The STE template can be found at the links below.  You can use either one to create the education.  

Slide Template:  https://ibm.box.com/s/1an42g7zdgmaj84w7dft0indqfgi8ffm

Github Template:  https://pages.github.ibm.com/WASL3/site/STE/about

Please upload the completed slides to the same 'STE Archive' BOX folder and let me know they're complete or provide me the Github link.   Thanks!

**Comment by chirp1** [comment]
From a slack with Paul, all the information that needs to be documented is in the autogen. Approving.

**Comment by donbourne** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature?
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  

4.  Which L2 / L3 queues will handle PMRs for this feature?  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info.

5.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?

**Comment by mrsaldana** [comment]
Serviceability Approval Comment - Please answer the following questions for serviceability approval:

UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR? Have these issues been addressed in the implementation?

> Yes

Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).
a) What problem paths were tested and demonstrated?

>  The demo covered proper configuration with the expected config initialization messages and well as messages seen when the header configuration is applied as the response is being handled. It also covered the configurations that would be considered erroneous, demonstrating the expected warning messages a customer will be able to see. It was also proven that the bad configurations are not applied or affect the resulting response. These scenarios were: 
> 
> 1. Providing an empty header name (CWWKT0042W) to any of the configuration options (add, set, setIfMissing, remove)
> 2. Providing duplicate header names (CWWKT0043W) across different configurations other than "add". Demonstrated that the "add" configuration can define multiple headers of the same name, but header names must be unique across the other configuration options. Showed variations of this misconfiguration across all of the configuration options. 
> 3. Providing duplicate header names more than twice (or in multiple of the configuration options) will result in CWWKT0044W. This message shows that a previously misconfigured header name was declared again. 

b) Who did you demo to?

> Bill Lucy and Volodymyr Siedlecki

c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?

> Yes, it is sufficient and clear enough that L2 should be able to quickly address and understand when the feature is being used correctly/incorrectly. 

SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them. Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature?
Daniel Guinan
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?

> Yes, I (Daniel Guinan) agree that the serviceability any problems encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3.

Which L2 / L3 queues will handle PMRs for this feature? Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it. Ask Don Bourne if you need links or more info.

> WAS: L2 WIN Team, WAS: L3 Channel Framework

Does this feature add any new metrics or emit any new JSON events? If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?

> No new metrics / JSON events

**Comment by tpickett1** [comment]
WAS Performance team
Ran throughput and Startup/Footprint tests with/without the headers elements.
Added performance approval tag - no performance impact found.

Run details follow:
Throughput test (daytrader8 - skylake2 2core)
Throughput with headers.  2455 req/s
Throughput without header. 2457 req/s

Startup/Footprint test(Petclinic - skylake2 2core)
Startup with headers. 5461ms
Startup without headers  5449ms

Footprint with headers. 369m
Footprint without headers 369m

**Comment by pnicolucci** [comment]
I spoke with YK today about the WDT and Guides items for this Epic. He said there isn't anything for guides or WDT for this feature.  We will be creating a blog though for this functionality.

**Comment by pnicolucci** [comment]
GA blog post can be found here : https://github.com/OpenLiberty/open-liberty/issues/19262
