### ISSUE TITLE
JakartaEE: Enable JSON-B and JSON-P

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#11278]
Child story for epic #9876 

Support the [Jakarta JSON Processing 2.0](https://jakarta.ee/specifications/jsonp/2.0/) and [Jakarta JSON Processing 2.0](https://jakarta.ee/specifications/jsonb/2.0/) specifications.

 - [x] Provide new JSON API (`jakarta.jsonp-2.0`, `jakarta.jsonb-2.0`). 
 - [x] Enable new JSON features for EE 9 -- `jsonp-2.0`, `jsonb-2.0`, `jsonpContainer-2.0`, `jsonbContainer-2.0` -- along with the supporting services and provider implementations, glassfish and yasson. 
 - [x] Deliver in EE 9 beta 21.0.0.8.
 - [x] Enable EE 9 tests covering Jakarta JSON 1.1 requirements, including the integration of yasson and glassfish, and the container features (see FAT summary at #12969)
 - [x] Announce in 20.0.0.8 EE 9 beta blog. 

The story was completed in two phases.

**PHASE 2: Complete Jakarta JSON enablement**
- Deliver tasks outlined in #11633 
- Rename feature artifacts according to new feature naming guidelines
- Update yasson-2.0 bundle to yasson 2.0.0-M1

**PHASE 1: Jakarta JSON enablement**
Uploaded any available, new Jakarta artifacts to Artifactory:

- jakarta.enterprise:jakarta.enterprise.cdi-api:3.0.0-M1
- jakarta.inject:jakarta.inject-api:2.0.0-RC2
- jakarta.interceptor:jakarta.interceptor-api:2.0.0-RC2
- jakarta.json-api:2.0.0-RC2
- jakarta.json.bind-api:2.0.0-RC2
- org.glassfish:jakarta.json:2.0.0-RC2

Transformed existing projects:
- com.ibm.ws.org.glassfish.1.0
- com.ibm.ws.repository
- com.ibm.ws.org.eclipse.yasson.1.0 
      (special case, see the yasson-2.0 project, below)

Created new bundle projects:
- com.ibm.websphere.jakarta.cdi.3.0
- com.ibm.websphere.jakarta.interceptor.2.0
- com.ibm.ws.org.eclipse.yasson.2.0 
    (unique transform of 1.0 to enable service resource provider)
- com.ibm.websphere.jakarta.jsonp.2.0
- com.ibm.websphere.jakarta.jsonb.2.0
- com.ibm.ws.org.glassfish.2.0

Composed new features over the new bundles, features and transformed bundles:
- com.ibm.websphere.appserver.jakarta.cdi-3.0
- com.ibm.websphere.appserver.jakarta.interceptor-2.0
- com.ibm.websphere.appserver.jakarta.jsonpImpl-2.0.0 
      (Depends on the transformed glassfish 1.0)
- com.ibm.websphere.appserver.jakarta.jsonpInternal-2.0.0
- com.ibm.websphere.appserver.jakarta.jsonp-2.0 w/ nls props
- com.ibm.websphere.appserver.jakarta.jsonbImpl-2.0.0 
      (Depends on the yasson-2.0 bundle, which is a special transform of yasson-1.0)
- com.ibm.websphere.appserver.jakarta.jsonbInternal-2.0.0
- com.ibm.websphere.appserver.jakarta.jsonb-2.0 w/ nls props
- com.ibm.websphere.appserver.jsonpContainer-2.0 w/ nls props
- com.ibm.websphere.appserver.jsonbContainer-2.0 w/ nls props

Updated the transformer rules for jsonp, jsonb, inject, interceptor, johnzon-jsonb

Modified FAT project com.ibm.ws.jsonp.1.1_fat to repeat for JakartaEE9 (simple fat)

Modified FAT project com.ibm.ws.jsonb1.0_fat to partially repeat for JakartaEE9 (see Problems encountered)

Simplicity support for JakartaEE
- Modified JakartaEE9Action to invoke the jakartaee transformer with liberty-specific rules during repeatable ee9 test execution.
- Enabled the use of Simplicity's @TestServlet annotation in Jakarta FATs by removing the build dependency on class javax.servlet.http.HttpServlet from the @TestServlet annotation.
- Modified the TestServletProcessor to support the jakarta WebServlet annotation and HttpServlet classes.

EE platform support
- Created the private singleton feature, eeCompatible-9.0
- Changed the dependency on javaeeCompatible-8.0 to eeCompatible-9.0 for all features in branch Jakartaee_work

Problems encountered
- The jakarta glassfish release artifact suffered runtime failures. Used the transformed glassfish JSONP provider, instead.
- The jakarta yasson release artifact is not yet published at maven central.
- Service loading did not enable for the JSONB provider because the transformer did not modify the service-component metadata within the yasson bundle. Opened an issue for the transformer: tbitonti/jakartaee-prototype#97; created a new project to transform the existing yasson bundle and to package the correct service meta-data.
- Two test cases within the JSONB FAT suite depend on the CDI feature, which will not jakartee-enable for some while; and the johnzon provider tests fail due to (most likely) both the yasson and johnzon provider impls are made visible to the application. Skipped the two CDI-dependent test cases and any test method that verifies johnzon provider behavior.

**Comment by dazavala** [comment]
**Jakarta JSON enablement**
Uploaded any available, new Jakarta artifacts to Artifactory:
1. jakarta.enterprise:jakarta.enterprise.cdi-api:3.0.0-M1
2. jakarta.inject:jakarta.inject-api:2.0.0-RC2
3. jakarta.interceptor:jakarta.interceptor-api:2.0.0-RC2
4. jakarta.json-api:2.0.0-RC2
5. jakarta.json.bind-api:2.0.0-RC2
6. org.glassfish:jakarta.json:2.0.0-RC2

Transformed existing projects:

1. com.ibm.ws.org.glassfish.1.0
2. com.ibm.ws.repository
3. com.ibm.ws.org.eclipse.yasson.1.0 (special case, see the yasson-2.0 project, below)

Created new bundle projects:

1. com.ibm.websphere.jakarta.cdi.3.0
2. com.ibm.websphere.jakarta.interceptor.2.0
3. com.ibm.ws.org.eclipse.yasson.2.0 (unique transform of 1.0 to enable service resource provider)
4. com.ibm.websphere.jakarta.jsonp.2.0
5. com.ibm.websphere.jakarta.jsonb.2.0
6. com.ibm.ws.org.glassfish.2.0

Composed new features over the new bundles, features and transformed bundles:

1. com.ibm.websphere.appserver.jakarta.cdi-3.0
2. com.ibm.websphere.appserver.jakarta.interceptor-2.0
3. com.ibm.websphere.appserver.jakarta.jsonpImpl-2.0.0 (Depends on the transformed glassfish 1.0)
4. com.ibm.websphere.appserver.jakarta.jsonpInternal-2.0.0
5. com.ibm.websphere.appserver.jakarta.jsonp-2.0 w/ nls props
6. com.ibm.websphere.appserver.jakarta.jsonbImpl-2.0.0 (Depends on the yasson-2.0 bundle, which is a special tranform of yasson-1.0)
7. com.ibm.websphere.appserver.jakarta.jsonbInternal-2.0.0
8. com.ibm.websphere.appserver.jakarta.jsonb-2.0 w/ nls props
9. com.ibm.websphere.appserver.jsonpContainer-2.0 w/ nls props
10. com.ibm.websphere.appserver.jsonbContainer-2.0 w/ nls props

Updated the transformer rules for jsonp, jsonb, inject, interceptor, johnzon-jsonb

Modified FAT project com.ibm.ws.jsonp.1.1_fat to repeat for jakarta ee9 (simple fat)

Modified FAT project com.ibm.ws.jsonb1.0_fat to partially repeat for jakarta ee9 (see Problems encountered)

**Simplicity support for JakartaEE**

1. Modified JakartaEE9Action to invoke the jakartaee transformer with liberty-specific rules during repeatable ee9 test execution
2. Enabled the use of Simplicity's @TestServlet annotation in Jakarta FATs by removing the build dependency on class javax.servlet.http.HttpServlet from the @TestServlet annotation
3. Modified the TestServletProcessor to support the jakarta WebServlet annotation and HttpServlet classes.

**EE platform support**

1. Created the private singleton feature, eeCompatible-9.0
2. Changed the dependency on javaeeCompatible-8.0 to eeCompatible-9.0 for all features in branch Jakartaee_work

**Problems encountered**

1. The jakarta glassfish release artifact suffered runtime failures. Used the transformed glassfish JSONP provider, instead. 
2.   The jakarta yasson release artifact is not yet published at maven central
3.   Service loading did not enable for the JSONB provider because the transformer did not modify the service-component metadata within the yasson bundle.  Opened an issue for the transformer: https://github.com/tbitonti/jakartaee-prototype/issues/97; created a new project to transform existing yasson bundle and package the correct service meta-data. 
4.   Two test cases within the JSONB FAT suite depend on the CDI feature, which will cannot jakartee-enable for some while; and the johnzon provider tests fail due to (most likely) both the yasson and johnzon provider impls are made visible to the application. Skipped the two CDI-dependent test cases and any test method that verifies johnzon provider behavior.

**Comment by malincoln** [comment]
@dazavala  pls add the FAT summary here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by dazavala** [comment]
Closing issue as fat-complete.
