### ISSUE TITLE
Support new change in the client certificate with urlencoded string.

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#11680]
Some of the open source web proxy servers or load balancers (for example, Nginx) start using a client certificate in the PEM **url-encoded** format to send to application server.  This change was due to the deprecation of long lines folding in the HTTP header continuation.

An example of the url-encoded X.509 client certificate sent to application server (truncated some characters)

[-----BEGIN%20CERTIFICATE-----%0AMIIDODCCAiCgAwIBAgIIHbO76YfCH1cwDQYJKoZIhvcNAQELBQAwOjELMAkGA1UE%0ABhMCVVMxDDAKBgNVBAoTA0lCTTEMMAoGA1UECxMDVFdTMQ8wDQYDVQQDEwZDbGll%0AbnQwHhcNMTUxMTAzMTYyODM1WhcNMzUxMDMwMTYyODM1WjA6MQswCQYDVQQGEwJV%0AUzEMMAoGA1UEChMDSUJNMQwwCgYDVQQLEwNUV1MxDz%2F%2Bpo%2FF%2Bzi%2F0sfAUwRdfgMm%2FAKAGzwMQufOYeKCgMULtq14QAJQnLmq4M%2FM00%0AC5QyeYtdaTou%2BMsLmoa1tkq2VSDVxAcktJyRSRsox36G7EHDLV4U2gtR6xczNEjw%0A2%2Bsj772FjdAMXRSR%0A-----END%20CERTIFICATE-----%0A]

All versions of WebSphere Application Server are not ready to support this new url-encoded certificate format.

This feature will enhance the WebContainer to handle the new url-encoded certificate.

**CURRENT BEHAVIOR:**

The original certificate is not checked for urlencoded string.  It is automatically wrapped with the Armor Header Line  (i.e BEGIN) and Armor Tail Line (i.e END).

**OVERALL DESIGN:**

During the process of the request's peer certificates String, the WebContainer processes the following steps:

 Determine if the String is already armored.  

    1. If armored, determine if there is any encoded character (i.e %). 
         1.1 If present, return the decoded String from java.net.URLDecoder.decode(String, "UTF-8").  UTF-8 is the recommended (see [1])
         1.1 If not (or there is any exception during the decoded), return as-is the armored String.

    2. Else, resume the current behavior to armor the String.

**Testing**
FAT Approval Test Summary: https://github.com/openliberty/open-liberty/issues/19438

**References:**
[1]
https://docs.oracle.com/javase/7/docs/api/java/net/URLDecoder.html#decode(java.lang.String,%20java.lang.String)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [x] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [x] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / UFO Approval (Alasdair Nottingham) or N/A.
- [x] No Design / No UFO Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "FAT Approval Test Summary". Add the link in above.

## **Legal**
3 weeks before Onboarding
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - (Tom Evans or Chuck Bridgham). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** (Sam Wong - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - (G Scott Johnston). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - (Kareen Deen). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - (Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - (Don Bourne). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - (Greg Ecock - Cloud, Brian Hanczaryk- APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [x] Github Epic and Epic's issues are closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / Backlog Subtribe PM)

## **Other deliverbles**
- [x] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A.
- [x] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [x] **Blog** - (Laura Cowen) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by pmd1nh** [comment]
WAS 8.5.5 Epic:
https://github.ibm.com/was-liberty/WS-CD-Open/issues/20794

WAS 9.0.5 Epic:
https://github.ibm.com/was-liberty/WS-CD-Open/issues/20795

**Comment by pmd1nh** [comment]
### FAT
https://github.com/OpenLiberty/open-liberty/issues/19438

**Comment by pnicolucci** [comment]
I talked with @yeekangc and he agreed we don't have any Open Liberty guides or WDT work for this issue so checking those off the release check list.

**Comment by pmd1nh** [comment]
As per Michal Broz, no **Standalone Feature Blog Post** needs for this feature.

**Comment by pnicolucci** [comment]
This epic is completed, I'm going to close it!
