### ISSUE TITLE
Jakarta RESTful Web Services 3.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#11803]
Describe the high level feature, including any external spec links.
This will be the epic issue for Jakarta RESTful Web Services (aka JAX-RS) 3.0, part of the EE 9 effort covered by Epic issue #9876.

The 3.0 spec adds little more than some behavior clarifications over the 2.1 spec, but we may be changing the implementation of the 3.0 spec.

When ready, add links to the Upcoming Feature Overview document and Feature Test Summary issue:
- UFO: https://ibm.box.com/shared/static/6tfnxuor042psbtu76k85p0qcd0pzpq0.pptx
- FTS: https://github.com/OpenLiberty/open-liberty/issues/15552

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [x] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [x] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / UFO Approval (Alasdair Nottingham) or N/A.
- [x] No Design / No UFO Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "FAT Approval Test Summary". Add the link in above.

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - (Adam Yoho). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - (Tom Evans or Chuck Bridgham). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** (Sam Wong - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [x] **Accessibility** - (Steven Zvonek). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **ID** - (Kareen Deen). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - (Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - (Don Bourne). Serviceability has been addressed.
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - (Greg Ecock - Cloud, Brian Hanczaryk- APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / Backlog Subtribe PM)

## **Other deliverbles**
- [ ] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - (Laura Cowen) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by WhiteCat22** [comment]
Tasks:

- [x] #12742 Migration tool entries / Document differences - All
- [x] Discuss with RESTEasy community the EE9 plans - Andy - [mail archives](https://lists.jboss.org/pipermail/resteasy-dev/2020-June/thread.html)
- [x] Verify SSE bucket passes - Jim
   - passing but 3 skip for repeats that we would like to remove - however, the test behavior is in dispute
- [x] #12314 - Initial commit - Adam
- [x] #12746 - Single bundle for all/most RESTEasy jars - Adam
- [x] #12998  - CDI Integration - Adam
- [x] Test CDI integration with our com.ibm.ws.jaxrs.2.0.cdi.1.2_fat bundle - Adam #14471
- [x] Investigate EJB Integration
- [x] #15027 Bean Validation Integration - John
- [x] #13658 JSON-P Provider support - Andy
- [x] #13219 Update JAX-RS 3.0 feature to use Jakarta API's - also create JAX-RS 2.2 feature for RESTEasy using the 2.1 APIs - Andy
- [x] #13236 Transform Resteasy libs to use Jakarta API's (i.e. convert to `jakarta.ws.rs.*` package namespace) - Andy
- [x] #13083 JSON provider support - two modules (one for JSON-B, one for JSON-P) - probably want to use our own - Jim/Andy?
- [x] #13369 Split RESTEasy JAXB module into separate bundle that is enabled by auto feature (`jaxrs-3.0` + `jaxb-3.0`) - Andy
- [x] #13495 Split JSON-B code into separate bundle that is enabled by auto feature (`jaxrs-3.0` + `jsonb-2.0`) - Andy
- [x] #13772 Rename `jaxrs-3.0` to `restfulWS-3.0` and `jaxrsClient-3.0` to `restfulWSClient-3.0` (see https://ibm.ent.box.com/notes/694805555197?s=zm2tpqlflwnagzab2qg1gkky0pmk0zny for more details) - Andy
- [x] ~~Refactor Liberty JAX-RS integration to support an implementation other than CXF - can we consolidate any of the 2.X stuff to re-use in 3.X?  Might need to scrap this item...~~
- [x] Work with Brian to get the EE 9 TCK running on `restfulWS-3.0` feature - Jim
   - we can run the TCK with a personal build - just not on our own VM like we do with JAX-RS 2.X
- [x] #12672 - Test overall functionality with our com.ibm.ws.jaxrs.2.0_fat bundle - Jim / Andy
         - https://github.com/OpenLiberty/open-liberty/pull/14091 (first pass)
         - https://github.com/OpenLiberty/open-liberty/pull/17553
- [x] Determine what to do with com.ibm.websphere.jaxrs20.multipart - implement with our own providers - #13658 - Andy
- [x] Determine what to do with com.ibm.websphere.jaxrs.providers.json4j - hoping to remove
- [x] #12975 Authorization integration (`@RolesAllowed`, `@DenyAll`, `@PermitAll`, etc.) - Andy
- [x] #13476 SSL client integration (ensuring JAX-RS Client will use Liberty's SSL contexts) - Andy
- [x] add default SSL support and testing - #17159 
- [x] add proxy authority (properties com.ibm.ws.jaxrs.client.proxy.*) support and testing - #17343 
- [x] #15092  Reactive extensions - only works with Jersey and CXF providers... (RESTEasy providers depends on internals & SSE) - John
- [x] #16290 Enable `<webTarget ... />` config to work with RESTEasy JAX-RS client implementation - Andy
- [x] Investigate global handler (JAX-RS & JAX-WS interceptor- Legacy SPI) - require opt-in in EE 9, and replace internals with JAX-RS Filter - Andy
- [x] #12875 Investigate IBMRestServlet - Andy - working with limitations - may need further investigation
- [x] Test against the EE 9 TCK - Brian D looking into this
- [x] Verify that LTPA works with RestEasy with a new set of tests - Andy - #17160 
- [x] Metrics - PMI -Andy
***
- [x] Problem determination - Skills transfer education - L2
- [x] Problem determination for users - serviceability - see issues #18145 (Adam) and #18147 (Andy)
- [x] #14039 Add to Beta / `web profile-9.0`- Andy
- [ ] Blogs / samples / etc.
- [x] Upgrade to the latest version RESTEasy
- [x] #12976 Address one app per web module limitation (or handle as migration issue) - Andy
- [x] Investigate difference between RestEasy and our current impl related to introspecting for providers, filters, etc. if an application specifies the ones they want in getClasses() or getSingletons().
- [x] #12806 Add Jakarta JAX-RS 3.0 API's into Liberty - Andy - done, but using milestone build - TODO: swap to GA API jars when available.
- [ ] Get RESTEasy-specific reactive providers to work and tested - can be done post-GA if at all.
 - [x] Fix intermittent Build Break Defects
- https://github.com/OpenLiberty/open-liberty/issues/16648
- https://github.com/OpenLiberty/open-liberty/issues/16650
- https://github.com/OpenLiberty/open-liberty/issues/16651
- https://github.com/OpenLiberty/open-liberty/issues/16693
***
Stuff to be addressed by MP 5.0:
- [x] ~~Investigate OpenAPI - mainly look for differences between CXF vs RESTEasy~~ - UPDATE: cannot do until MP 5.0
- [x] Investigate OpenTracing integration (Prasanth?)
- [x] MP Metrics w/JAX-RS 3.0 (David Chan?)

**Comment by andymc12** [comment]
UFO Review today - updated slides available at: https://ibm.box.com/s/6tfnxuor042psbtu76k85p0qcd0pzpq0

**Comment by mbroz2** [comment]
UFO Review Feedback:
Slide 17; Firm statement regarding JAX-RS 2.X Config continuing to work.
Slide 25: Include performance metrics/improvements in the Beta & GA Blog posts.
Slide 26: Update the Java certification requirement
Slide 28: RESTEasy has less trace then CXF.  We'll add trace over time as we participate in RESTEasy (as we had done for CXF).

**Comment by malincoln** [comment]
@NottyCode can you approve the design request?  Thanks

**Comment by malincoln** [comment]
@andymc12 pls add FAT summary to overall epic here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by andymc12** [comment]
Checkpoint Meeting 2021-04-16:
Epic Issue: https://github.com/OpenLiberty/open-liberty/issues/11803

First, what we've accomplished:
- Pulled RESTEasy into Open Liberty
- Transformed it
- Based the implementation on CDI - this should simplify support and better position us for future JAX-RS versions
- Transformed FATs - skipping several due to RESTEasy vs CXF compatibility issues and CXF-specific FAT tests
	- Also worked with transformer tool to resolve issues
- Passed the TCK - both the Web Profile and Full Platform
- Found and fixed issues in other components (servlet and security) that needed fixing or enhancing to support RESTEasy
- Some of the "extras" - like global handlers, configuring the client in server.xml, some client properties, etc.
- Built some karma with the RESTEasy development community

What we have left to do (taken from the epic):
- [All] Document migration changes (ongoing/all) - periodically review and add notes when things change
- [Adam] CDI Integration - seems to be blocking BeanValidation and EJB - need more understanding here since we pass the TCK
	- CDI not injecting into Application subclass beans (product issue) 
	- Application#getSingletons() not working with CDI (test case change) - ref: https://github.com/OpenLiberty/open-liberty/issues/12742#issuecomment-705094494
	- UPDATE: This is now working when the Application subclass is annotated with @ApplicationPath - still need to get it working when Application subclass is only specified via web.xml.
- ~~[Andy] Default SSL Support and testing - tests failing have @SkipForRepeat with comment on default ssl not working - might be child of next item~~ - Should be resolved by PR #17159 
- ~~[Andy/John] Resolve issue with Invocation.Builder.get(SomeClass.class) not working - ref: https://github.com/OpenLiberty/open-liberty/issues/12742#issuecomment-772535041~~
	- UPDATE: This appears to be resolved - we have some FAT test cases for this (with Invocation.Builder.get(String.class) ) that are passing 
	- ~~[John] Would be good to test with a more complex object (maybe already have a test that is skipped) - to be verified~~
	- UPDATE: `JAXRS20ClientSyncInvokerTest.testSyncInvoker_get2()` does a `Book response = builder.get(Book.class);` and the test passes on EE9.
- Test of Client Properties  - code
	- ~~[Andy] Proxy authorization support and testing~~
		- Adam updated Mock-Server to latest levels (mainly for L3 case on 2.0/2.1 - but should help enable this on 3.0)
	- ~~Verify timeout properties - ref: https://github.com/OpenLiberty/open-liberty/issues/12742#issuecomment-765477724~~
	         - UPDATE: John has verified that the timeout properties com.ibm.*timeout work
	- ~~[Andy] Verify security handler properties - LTPA/SAML/JWT/MPJWT/OAuth - ref: https://github.com/OpenLiberty/open-liberty/issues/12742#issuecomment-767125327~~
		- See issue #17160 / PR #17201
	- ~~[Andy] Determine what to do with MP-JWT client property - throw error/log warning?~~ - just use it since it is just propagating a header
	- ~~[John] Need new tests to verify  that ClientBuilder.readTimeout()/connectTimeout() take precedence over com.ibm.*.timeout properties~~
		- Need to change 2.1 tests to still verify com.ibm.*timeout properties work
- [Jim] Iron out SSE behavior differences between RESTEasy and CXF and IBM (?)
- [] Check all the `@SkipForRepeat` in FATs - make sure we're testing everything we should
- [Andy/All] All feature approver stuff:
	- Serviceability writeup
	- Skills Transfer Education
	- Documentation - can we reference RESTEasy docs directly?
	- Work with Performance and SVT
	- FAT approval
	- etc.
- ------------------------------------------------------------------------------------
- [John] Document "client.*" properties in migration guide - (nice-to-have - can be after GA) tests and possible config-mapping code for RESTEasy-specific properties 
- [John] RESTEasy Reactive Extension provider support + intermittent failures with Jersey and CXF reactive providers
- Upgrade to latest released version of RESTEasy
	- UPDATE: Now at RESTEasy 4.6.0.Final - this was escalated due to security vulnerability in previous version.
- ~~Clean up IBM-API-Packages~~
	- ~~[Jim] remove JSON4J package - ref: https://github.com/OpenLiberty/open-liberty/pull/17032#issue-629331307~~
- 
- Nice to have: Integration with MP (likely in future feature) - Metrics, OpenAPI, OpenTracing

FAT buckets in WS-CD-Open that are not in OL:
- [Adam] com.ibm.ws.jaxrs.2.0.cdi_fat * possibly in OL but moved/renamed - Adam will confirm
- [Adam] com.ibm.ws.jaxrs.2.0_legacy_fat * might not need to be migrated - contains EE6 (beanVal 1.0) tests that are not in OL
- com.ibm.ws.jaxrs.2.0.ejb.cdi_fat
- com.ibm.ws.jaxrs.2.1.ejb.cdi_fat

[Andy] Verify DCUT and GA dates

**Comment by donbourne** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?

**Yes, behavior changes between 2.X (CXF) and 3.0 (RESTEasy) that are not strictly defined by the spec are the most likely problems that customers will see. We have addressed many and attempted to minimize the behavior changes that customers will see - we have also contributed back some serviceability related changes to the RESTEasy community.**

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated?  **Mismatched mapping between code and URLs and issues with processing HTTP requests/responses were demonstrated.**
b) Who did you demo to?  **Jim Krueger demonstrated to Swati / L2.**
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3? **Yes**

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature? **Brian/Jag/Rumana**
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  **Yes, serviceability of any problems encountered was sufficient to avoid PMRs or L2 should be able to quickly address the problems without L3.**

4.  Which L2 / L3 queues will handle PMRs for this feature?  **WASWIN (formerly WASWEB) and WL3JRS** Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info. **Confirmed**

5.  Does this feature add any new metrics or emit any new JSON events?  **Yes, but in the same vain as former JAX-RS releases** If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs? **The `restfulWS-3.0` features provides the same metrics as `jaxrs-2.1` via the `monitor` feature, but note that it does _not_ provide any metrics via MicroProfile metrics - that support will come as part of MP 5.0.**

**Comment by skasund** [comment]
L2 has requested STE slides for this feature.  The STE template can be found at the links below.  You can use either one to create the education.  

Slide Template:  https://ibm.box.com/s/1an42g7zdgmaj84w7dft0indqfgi8ffm

Github Template:  https://pages.github.ibm.com/WASL3/site/STE/about

Please upload the completed slides to the same 'STE Archive' BOX folder or provide me the Github link.   Thanks!

**Comment by andymc12** [comment]
Doc/ID issue https://github.com/OpenLiberty/docs/issues/4825 opened.

**Comment by skasund** [comment]
Thanks for completing the STE.  I've provided the approval.

**Comment by chirp1** [comment]
Approving. Doc issue at https://github.com/OpenLiberty/docs/issues/4825 has info needed.

**Comment by WhiteCat22** [comment]
We did it! Good job team!
