### ISSUE TITLE
JakartaEE: Jakarta Managed Bean Support 

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11850]
Support the Jakarta Managed Bean specification (`jakarta.annotation.ManagedBean`).

The following will be required to support `ManagedBeans`

 - [x] Provide the API (`jakarta.annotation.ManagedBean).  This is provided by the common annotations Epic (https://github.com/OpenLiberty/open-liberty/issues/11849).
 - [x] Provide the implementation. In open-liberty, `ManagedBean` support is primarily provided as a special bean type in the EJB Container core, so EJB Container core will be provided here, and the Jakarta Enterprise Beans Epic (https://github.com/OpenLiberty/open-liberty/issues/11450) will depend on this Epic.
 - [x] Deliver in beta / webProfile
 - [x] Provide implementation for application client (client container)
 - [x] Provide testing

FAT Summary : #12969

**Comment by tkburroughs** [comment]
All work complete; FAT Summary : #12969
