### ISSUE TITLE
JakartaEE: Jakarta XML WS Support

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11862]

**Comment by neuwerk** [comment]
**Jakarta XML WS Support will require the following:** 

- [ ]  Add Jakarta XML WS APIs (jws.3.0 + jaxws.3.0 +saaj.2.0) + jaxws-3.0 Feature
- [ ]  Add final JAX-WS spec APIs
- [ ]  Add or Transform wsdl4j bundles
         -  com.ibm.websphere.prereq.wsdl4j.api
         -  com.ibm.websphere.javaee.wsdl4j.1.2
- [ ]  Rename jaxws-3.0 to xmlWS-3.0
- [ ]  Add final JAX-WS spec APIs
- [ ]  Transform CXF + Dependency bundles
         -  
         -  
         -  
com.ibm.ws.com.sun.xml.messaging.saaj; require-java:="9", \
 com.ibm.ws.javaee.ddmodel.wsbnd, \
 com.ibm.ws.cxf.client, \
 com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.tools.validator.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.hc.3.2, \
 com.ibm.ws.org.jvnet.mimepull, \
 com.ibm.ws.jaxws.tools.2.2.10, \
 com.ibm.ws.jaxws.2.3.common; start-phase:=CONTAINER_LATE, \

 com.ibm.ws.prereq.wsdl4j.1.6.2, \
 com.ibm.ws.jaxws.2.3.wsat, \
 com.ibm.ws.javaee.ddmodel.ws, \
 com.ibm.ws.javaee.ddmodel.wsbnd, \
 com.ibm.ws.webservices.javaee.common, \
 com.ibm.ws.webservices.handler
- Transform jaxws-2.3 integartion layer
- Create auto features
- Transform FAT Buckets

**Comment by neuwerk** [comment]
**Jakarta XML WS Support will require the following:** 

- [ ]  Add Jakarta XML WS APIs (jws.3.0 + jaxws.3.0 +saaj.2.0) + jaxws-3.0 Feature
- [ ]  Add final JAX-WS spec APIs
- [ ]  Add or Transform wsdl4j bundles
         -  com.ibm.websphere.prereq.wsdl4j.api
         -  com.ibm.websphere.javaee.wsdl4j.1.2
- [ ]  Rename jaxws-3.0 to xmlWS-3.0
- [ ]  Add final JAX-WS spec APIs
- [ ]  Transform CXF + Dependency bundles
         -  com.ibm.ws.com.sun.xml.messaging.saaj
         -  com.ibm.ws.cxf.client
         -  com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2
         -  com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.3.2
         -  com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2
         -  com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2
         -  com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.3.2
         -   
         -   
         -   
; require-java:="9", \
 com.ibm.ws.javaee.ddmodel.wsbnd, \
 , \
 , \
 , \
 , \
 , \
, \
 com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.tools.validator.3.2, \
 com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.hc.3.2, \
 com.ibm.ws.org.jvnet.mimepull, \
 com.ibm.ws.jaxws.tools.2.2.10, \
 com.ibm.ws.jaxws.2.3.common; start-phase:=CONTAINER_LATE, \

 com.ibm.ws.prereq.wsdl4j.1.6.2, \
 com.ibm.ws.jaxws.2.3.wsat, \
 com.ibm.ws.javaee.ddmodel.ws, \
 com.ibm.ws.javaee.ddmodel.wsbnd, \
 com.ibm.ws.webservices.javaee.common, \
 com.ibm.ws.webservices.handler
- Transform jaxws-2.3 integartion layer
- Create auto features
- Transform FAT Buckets

**Comment by malincoln** [comment]
@neuwerk  pls add FAT summary to overall epic here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by neuwerk** [comment]
Closing this issue, as work is complete.
