### ISSUE TITLE
Be more forgiving of issues in deployment descriptors

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#11911]
**For delivery of this issue:**

(Main pull request)
"Issue 11911: Parsing and test updates"
https://github.com/OpenLiberty/open-liberty/pull/17781 **MERGED**

(design-issue)
"Issue 11911: Descriptor parsing reference failures are ignored"
https://github.com/OpenLiberty/open-liberty/issues/19207 **CLOSED**

(FAT Approval Test Summary)
"Issue 11911: FAT Approval Test Summary"
https://github.com/OpenLiberty/open-liberty/issues/19274 **CLOSED**

(Commercial Liberty)
"Remove "com.ibm.ws.javaee.ddmodel_fat"
https://github.ibm.com/websphere/WS-CD-Open/pull/25339 **MERGED**

**Technical debt:**

"Issue 11911: Technical debt"
https://github.com/OpenLiberty/open-liberty/issues/19416

POC: "Open Liberty Issue 11911: Handling unresolved references from bindings and extensions"
https://github.ibm.com/websphere/POC-Meeting/issues/60

"Issue 11911: Update resource adapter (ra.xml) parsing to be less strict"
https://github.com/OpenLiberty/open-liberty/issues/18628

"Issue 11911: Implement remaining FATs"
https://github.com/OpenLiberty/open-liberty/issues/19278

"Issue 11911: Relocate descriptor parsing BVT from Commercial Liberty to Open Liberty"
https://github.com/OpenLiberty/open-liberty/issues/19276

"Issue 11911: Tests with unfound references in bindings and extensions resources"
 https://github.com/OpenLiberty/open-liberty/issues/19415 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Describe the high level feature, including any external spec links.
When Liberty parses the spec deployment descriptors it is pretty unforgiving of errors, especially around the **schemas** and **schema version** entries. Other runtimes are more forgiving. This makes it harder to move apps from more forgiving runtimes to Liberty so we should investigate making the dd parsing more forgiving too.

When ready, add links to the Upcoming Feature Overview document and Feature Test Summary issue:
- UFO: https://ibm.box.com/s/5nvb0whjbs30olqohxul6ns9k84lrzh5
- FTS: https://ibm.box.com/s/pcfzyz3ixuk6sisn3ck3usqp85iyf4op

- UFO (obsolete): https://ibm.box.com/s/ouezcaxipynvpeg4w29sbkv2gsolkfz1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [x] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [x] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / UFO Approval (Alasdair Nottingham) or N/A.
- [N/A] No Design / No UFO Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "FAT Approval Test Summary". Add the link in above.

## **Legal**
3 weeks before Onboarding
- [N/A] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [N/A] **Demo** - (Tom Evans or Chuck Bridgham). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** (Sam Wong - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [N/A] **Accessibility** - (Steven Zvonek). Accessibility testing is complete or N/A. Approver adds labl focalApproved:accessibility to the Epic in Github.
- [N/A] **ID** - (Kareen Deen). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [X] **Performance** - (Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - (Don Bourne). Serviceability has been addressed.
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [N/A] **SVT** - (Greg Ecock - Cloud, Brian Hanczaryk- APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [x] Github Epic and Epic's issues are closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / Backlog Subtribe PM)

## **Other deliverbles**
- [N/A] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A.
- [N/A] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [N/A] **Blog** - (Laura Cowen) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by tbitonti** [comment]
UFO followup:
resource-adapter (ra.xml) parsing is at:
    open-liberty/dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/DeploymentDescriptorParser.java
See:
    DeploymentDescriptorParser$NamespaceFilter.startElement
Are there any other XML resource types which should be considered?
For example, "permissions.xml", which is parsed by code external to open-liberty.

**Comment by tbitonti** [comment]
UFO followup:
The exception which occurs for an incomplete schema definition is (for example):

```
The namespace prefix "xsi" was not declared.
at com.ibm.xml.xlxp.api.stax.msg.StAXMessageProvider.throwWrappedXMLStreamException(StAXMessageProvider.java:73)
at com.ibm.xml.xlxp.api.stax.XMLStreamReaderImpl.produceFatalErrorEvent(XMLStreamReaderImpl.java:2172)
at com.ibm.xml.xlxp.api.stax.XMLStreamReaderImpl.reportFatalError(XMLStreamReaderImpl.java:2178)
at com.ibm.xml.xlxp.api.util.SimpleScannerHelper.undeclaredPrefix(SimpleScannerHelper.java:778)
at com.ibm.xml.xlxp.api.util.SimpleScannerHelper.resolveNamespaceURIs(SimpleScannerHelper.java:760)
at com.ibm.xml.xlxp.api.util.SimpleScannerHelper.finishElement(SimpleScannerHelper.java:683)
at com.ibm.xml.xlxp.api.util.SimpleScannerHelper.finishStartElement(SimpleScannerHelper.java:712)
at com.ibm.xml.xlxp.scan.DocumentEntityScanner.scanStartElementUnbuffered(DocumentEntityScanner.java:3548)
at com.ibm.xml.xlxp.api.util.SimpleScannerHelper.scanStartElementUnbuffered(SimpleScannerHelper.java:1003)
at com.ibm.xml.xlxp.scan.DocumentEntityScanner.stateUnbufferedStartElement(DocumentEntityScanner.java:507)
at com.ibm.xml.xlxp.scan.DocumentEntityScanner.scanRootElement(DocumentEntityScanner.java:1874)
at com.ibm.xml.xlxp.scan.DocumentEntityScanner.scanProlog(DocumentEntityScanner.java:1757)
at com.ibm.xml.xlxp.scan.DocumentEntityScanner.produceEvent(DocumentEntityScanner.java:636)
at com.ibm.xml.xlxp.api.stax.XMLStreamReaderImpl.getNextScannerEvent(XMLStreamReaderImpl.java:1714)
at com.ibm.xml.xlxp.api.stax.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:605)
at com.ibm.xml.xlxp.api.stax.XMLInputFactoryImpl$XMLStreamReaderProxy.next(XMLInputFactoryImpl.java:188)
at com.ibm.ws.javaee.ddmodel.DDParser.parseToRootElement(DDParser.java:879)
```

**Comment by tbitonti** [comment]
UFO followup:
Migration has a case of version-namespace mismatch which is reported as an error.   This should perhaps be downgraded to a warning, for consistency with the new parsing code.

**Comment by tbitonti** [comment]
UFO followup:
Beta guarding may not be necessary, given the cost of placing a beta property based code switch.  However, omitting a beta guard means the update must be delivered at the beginning of the release cycle, so to provide sufficient time for problems to be discovered and, if necessary, for the update to be reverted.  This in turn requires that the update be compact enough to be easily reverted.

**Comment by tbitonti** [comment]
UFO followup:
The question of whether a property which would re-enable strict parsing is still un-answered.  Unless requested, the current design, which is not to have such a property, is being followed.

**Comment by tbitonti** [comment]
UFO followup:
Displaying full paths is categorized as a security weakness, not as a security vulnerability.  Per the security team, when possible, full paths should not be displayed.

**Comment by tbitonti** [comment]
UFO followup:
The UFO was requested to be updated to show the elements which are omitted in the partial header cases.  See the original slides 15, 24, and 25.

**Comment by mbroz2** [comment]
Looks like you've already addressed above most of the comments from the UFO, but here they are:
Update Communication slide to make it clear that it's the openliberty.io blogs.
Slide 21 (To-be): Clarify that highest supporting version is referring to the xml file
Slide 24 (To-be): Mention what's incomplete about the example (missing schema)
Beta Slide: Decision was that if doing the beta guards would significantly add work (by needing to add them all over the place, or copying large parts of the codebase), then it can be skipped for this feature.  However, care must be taken when delivering this, which includes delivering early into upcoming release and working closely (and early) with focal approvers.  Also, try to limit the delivery to a single PR to make any reverts simpler.
Migration Impact Slide: Migration toolkit will need to be updated to lower errors to warnings (or remove them all together)

To Do: make sure other deployment xmls were not missed (like resource adapter, persistence (in jpa container))

-----
Regarding the communication slide, you can update it with something like:
If this functionality is included in a beta, currently unlikely, then a description of this functionality will be included in the beta release blog post on openliberty.io.

When the functionality GAs, it will be included in the release blog post on openliberty.io.

No standalone blog post regarding the functionality will be made.

**Comment by NottyCode** [comment]
@tbitonti 

slide 13 has an open question. Is it still open?
slide 24 says in brackets something might be an error which begs the question does it? I'm not sure how to read this.
slide 50 hints that this might be a breaking behaviour change. I'm assuming the "break" would be a case that causes an error today would not which is normally not an issue since people do not deploy broken code, but I'd like to check.

**Comment by tbitonti** [comment]
@NottyCode 
See the current update (26-Oct-2021).  In particular:
re "slide 13": New slides 11-13 replace the previous unresolved question.
re "slide 24": See the updated text on slide 25-26.
re "slide 50": See the text on new slide 50.

**Comment by chirp1** [comment]
From slack with Thomas, no ID is required.  There will be only messages and a blog, neither of which requires an ID issue. Approved.

**Comment by dave-waddling** [comment]
Hi, if this work is targeted for 21.0.0.12 please can you add the "target:ga" label otherwise it won't appear on our radar for FAT Focal approvals. Also once the testing is fully delivered adding the "FAT Complete" label will indicate to us that this work is ready for review. 

Additionally no Feature Test Summary issue is linked. The link provided in the description leads to an obsolete UFO and I tried the other links in case the order was wrong but they all seem to link to a variety of UFOs. Please can you fix the link to the Feature Test Summary?
Edit: Ah, there is a working link in the top of the description, it's the specific call out to the Feature Test Summary further down that's incorrect.

Thanks!

**Comment by jhanders34** [comment]
Startup does not appear to be slower with this code integrated.

**Comment by donbourne** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation? **Yes.  The feature reduces cases of unnecessary failures, and improves messages for the remaining failure cases.**

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated?
**Serviceability is limited to new messaging.  The feature does not introduce new problem paths.**
b) Who did you demo to?
**Demo at next EOI showing new messages.**
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3? **Yes**

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature? **Approved by Brian Hanczyark**
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3? **Yes**

4.  Which L2 / L3 queues will handle PMRs for this feature?  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info. **L3: Kernel**

5.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs? **No**

**Comment by samwatibm** [comment]
Adding STE approvals on behalf of Vish who is Swati's backup

**Comment by dave-waddling** [comment]
Hi, the Feature Test Summary looks good and the outstanding defect (287799) has been resolved so I've added the FAT Focal Approval.
