### ISSUE TITLE
Add JDBC testing scenarios that utilize SSL/TLS communications

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/open-liberty#11930]
Because of the prevalence of securing database communications with SSL/TLS, we need to add a few continuous tests that use secure comms between the app server and database.  In discussions about this, we considered creating additional TestContainers with SSL enabled,  and also discussed what tests we might want to run.  We agreed that these would be additional tests and would include one or two tests for basic connectivity and one or two tests of transaction recovery (since that is a different code path).  We also noted that there is a single existing bucket for trans recovery using postgres db, com.ibm.ws.transaction.db_fat.

**Comment by aguibert** [comment]
In this epic we will ensure SSL/TLS coverage of the following databases in their respective FAT buckets:

- [ ] DB2 (com.ibm.ws.jdbc_fat_db2)
- [ ] Oracle (com.ibm.ws.jdbc_fat_oracle)
- [ ] PostgreSQL (com.ibm.ws.jdbc_fat_postgresql)
- [ ] Microsoft SQLServer (com.ibm.ws.jdbc_fat_sqlserver)

**Comment by frowe** [comment]
@ayoho Adam, @njr-11 and I am trying to figure out why this story didn't get picked up for FAT approval since it seems to meet the criteria on the process page https://github.ibm.com/websphere/WS-CD-Open/wiki/Liberty-Feature-Focal-Point-Approvals . Nathan went so far as to add the Fat complete label today, but according to the process page that's optional.  Do we have a hole in our approval process causing this not to get picked up?

**Comment by ayoho** [comment]
@frowe Hi, Fred. It looks like this feature hasn't had the `target:ga` label added to it. That's the label that all of the focal approvers' queries look for to see which features are ready for review, and the https://github.ibm.com/websphere/WS-CD-Open/wiki/Liberty-Feature-Focal-Point-Approvals page does have a section at the top that mentions that. Unfortunately since the label is missing it didn't show up on my radar. If this one is ready to be reviewed, go ahead and add that label and I'll make sure it gets reviewed.

**Comment by frowe** [comment]
Doh, that would explain it.  We're ready now...
