### ISSUE TITLE
JakartaEE 9: Jakarta Enterprise Beans 4.0 Testing

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#13717]
Provide testing for the Jakarta Enterprise Beans 4.0 features.  The following FAT projects are required to work with Enterprise Beans 4.0 / Jakarta EE 9:

- [x] com.ibm.ws.ejbcontainer.async_fat _(enterpriseBeansLite-4.0)_ (#13718)
- [x] com.ibm.ws.ejbcontainer.bindings_fat _(enterpriseBeansHome-4.0, enterpriseBeansRemote-4.0)_ (#18211)
- [x] com.ibm.ws.ejbcontainer.cdi_fat _(enterpriseBeansLite-4.0, enterpriseBeansHome-4.0, enterpriseBeansRemote-4.0)_
- [x] com.ibm.ws.ejbcontainer.exception_fat _(enterpriseBeansLite-4.0, enterpriseBeansHome-4.0, enterpriseBeansRemote-4.0)_ (#17949) 
- [x] com.ibm.ws.ejbcontainer.injection_fat _(enterpriseBeansLite-4.0, enterpriseBeansRemote-4.0, mdb-4.0)_
- [x] com.ibm.ws.ejbcontainer.interceptor_fat _(enterpriseBeansLite-4.0, enterpriseBeansPersistentTimer-4.0, mdb-4.0)_ (#17939) 
- [x] com.ibm.ws.ejbcontainer.interceptor.v32_fat _(enterpriseBeansLite-4.0, enterpriseBeansHome-4.0)_ (#17929)
- [x] com.ibm.ws.ejbcontainer.legacy_fat _(enterpriseBeansHome-4.0, enterpriseBeansRemote-4.0)_ (#17925)
- [x] com.ibm.ws.ejbcontainer.mdb.ra_fat  _(mdb-4.0)_
- [x] com.ibm.ws.ejbcontainer.remote_fat _(enterpriseBeansRemote-4.0)_ (#17745)
- [x] com.ibm.ws.ejbcontainer.remote.client_fat _(enterpriseBeansRemoteClient-2.0)_
- [x] com.ibm.ws.ejbcontainer.session.async_fat _(enterpriseBeansLite-4.0, mdb-4.0)_ (#17736)
- [x] com.ibm.ws.ejbcontainer.session.passivation_fat _(enterpriseBeansLite-4.0)_
- [x] com.ibm.ws.ejbcontainer.timer.auto_fat _(enterpriseBeansLite-4.0)_ (#14591)
- [x] com.ibm.ws.ejbcontainer.timer.persistent_fat _(enterpriseBeansPersistentTimer-4.0)_ (#17719)
- [x] com.ibm.ws.ejbcontainer.tx_fat _(enterpriseBeansLite-4.0, mdb-4.0)_ (#17709)
- [x] com.ibm.ws.injection_fat _(enterpriseBeansLite-4.0)_
- [x] new test for `@Schedule` as repeatable _(enterpriseBeansLite-4.0)_ (#18181)
- [x] Enable tests skipped waiting for #17742]  (**Search in source for** 17742 in remote_fat & legacy_fat) (#18314)

And the following FAT buckets updated/added and also working with Jakarta Enterprise Beans 4.0 features:

- [x] com.ibm.ws.ejbcontainer.interceptor.v32_fat (additional tests for @AroundConstruct) (#18501)
- [x] com.ibm.ws.ejbcontainer.exceptions_fat (additional tests for Remote Exceptions) (#18440)
- [x] com.ibm.ws.ejbcontainer.war_fat (new fat project for testing EJB in WAR) (#18557)
- [x] com.ibm.ws.ejbcontainer.timer.np_fat (new fat project for programmatically created non-persistent timers) (#18719)

**Comment by tkburroughs** [comment]
All FAT for Enterprise Beans 4.0 is complete.
