### ISSUE TITLE
Language Server for Liberty Config

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/open-liberty#14054]
Develop a language server for Liberty server configuration to provide edit assistance to users like auto complete and validations.  The language server can in turn be made available in the various editors/IDEs through Open Liberty Tools.

See a prototype here: https://github.com/OpenLiberty/liberty-language-server

When ready, add links to the Upcoming Feature Overview document and Feature Test Summary issue:
- UFO:
- FTS:

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [ ] Create a child task of this epic entitled "FAT Approval Test Summary". Add the link in above.

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([Kevin Smith](https://github.com/sabolo)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Kareen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / Backlog Subtribe PM)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by yeekangc** [comment]
Assigning to @rzgry @kathrynkodama.  Cc @ericglau.

**Comment by tevans78** [comment]
UFO review comments & follow-on items:

* Slide 22: Questions about which features may be configured. Can you configure incompatible features together? Can a feature be configured which is not installed in the runtime? There are a variety of error paths than need to be considered. Follow up with Alasdair.

* Slide 28: Will there be completion support for using property references in server.xml? Only well known properties or any defined in server.env or bootstrap.properties? Then, as a secondary item, where properties have been referenced in server.xml, provide content assist to help define those properties in server.env/bootstrap.properties.

* Slide 34: Need to have an issue open to support config overrides. Also need to consider supporting when the config dir itself has been overridden (server.xml etc in a non-standard folder).

* Slide 36: Issue required to cover providing feature suggestions when config element is used but the feature is not currently listed.

* Slide 45: Will the language server be made available as a beta?

* What is the actual deliverable (jar, war etc)? What does it run on? Can we run it on Liberty? (We should run it on Liberty if we can)

**Comment by cherylking** [comment]
@NottyCode I have updated the UFO at the Box [link](https://ibm.box.com/s/pfw3l83ny1gy3k11x1611uhfbxnyrta1) for the review comments. Each updated slide includes (updated) in the title.

> * Slide 22: Questions about which features may be configured. Can you configure incompatible features together? Can a feature be configured which is not installed in the runtime? There are a variety of error paths than need to be considered. Follow up with Alasdair.

Features can be configured that are not installed. The main user scenario is using `dev` mode which will handle installing the configured features.

Incompatible features can also be detected by `dev` mode, and we will look into a future enhancement in the language server to display a diagnostic to the user for those features. Opened issue [70](https://github.com/OpenLiberty/liberty-language-server/issues/70) to track that.

> * Slide 28: Will there be completion support for using property references in server.xml? Only well known properties or any defined in server.env or bootstrap.properties? Then, as a secondary item, where properties have been referenced in server.xml, provide content assist to help define those properties in server.env/bootstrap.properties.

Adding completion support for property references in server.xml will be a future enhancement. It should include any property/variable defined in server.xml, bootstrap.properties or server.env. Issue [68](https://github.com/OpenLiberty/liberty-language-server/issues/68) for tracking.

If a property reference in server.xml does not match a defined property/variable, a future enhancement would provide a quick fix to create a variable by that name in server.xml. Issue [69](https://github.com/OpenLiberty/liberty-language-server/issues/69) for tracking.

> * Slide 34: Need to have an issue open to support config overrides. Also need to consider supporting when the config dir itself has been overridden (server.xml etc in a non-standard folder).

The slide has been updated to indicate config overrides are supported. Issue [66](https://github.com/OpenLiberty/liberty-language-server/issues/66) has been opened for a future enhancement to support an alternate configDirectory or file (Maven/Gradle allow serverXmlFile, bootstrapPropertiesFile and serverEnvFile to be overridden).

> * Slide 36: Issue required to cover providing feature suggestions when config element is used but the feature is not currently listed.

Issue [67](https://github.com/OpenLiberty/liberty-language-server/issues/67) has been opened to track this as a future enhancement. The slide has been updated.

> * Slide 45: Will the language server be made available as a beta?

Slide has been updated to indicate the language server will be included in an early release of the Liberty Developer Tools v2 Eclipse IDE.

> * What is the actual deliverable (jar, war etc)? What does it run on? Can we run it on Liberty? (We should run it on Liberty if we can)

There are two jar files that will be delivered. The lemminx-liberty jar is placed on the classpath of the IDE and is loaded by the lemminx extension. The language-server jar will be pulled in by whichever IDE extension we (IBM) has provided for Liberty, whether it be Eclipse, IntelliJ or MS VSCode. I don't understand why it is being asked if it can run on Liberty.

**Comment by cherylking** [comment]
Noting here that we plan to release a `1.0` version of the Liberty Config Language Server that is compatible with Eclipse LemMinX `0.22.0` through `0.24.0` and will be utilized by Liberty Tools for Eclipse, and a `2.0` version that is compatible with Eclipse LemMinX `0.25.0` and will be utilized by Liberty Tools for IntelliJ IDEA and Liberty Tools for Visual Studio Code. Both the `1.0` and `2.0` artifacts need to be published by the end of May in order to get pulled into the three IDE releases that will happen between June 2nd and June 9th. We are waiting for SVT to complete and add their approval.

**Comment by cherylking** [comment]
Status of remaining issues that were not part of MVP:

- [x] Issue [66](https://github.com/OpenLiberty/liberty-language-server/issues/66) - completed in LCLS and VS Code. Work remains in Eclipse and IntelliJ to enable it.
- [x] Issue [67](https://github.com/OpenLiberty/liberty-language-server/issues/67) - done
- [x] Issue [68](https://github.com/OpenLiberty/liberty-language-server/issues/68) - minimal work started in a branch
- [x] Issue [69](https://github.com/OpenLiberty/liberty-language-server/issues/69) - not started
- [x] Issue [70](https://github.com/OpenLiberty/liberty-language-server/issues/70) - not started (but becomes somewhat moot once auto feature generation is turned on by default). Also, we added the `Enables` and `Enabled by` information when hovering over features in our most recent LCLS release `2.1.2`, which will be included in upcoming fix releases for Liberty Tools.

Those issues that are not done will not be worked on in the near future. Our priorities have shifted. 

@NottyCode @yeekangc Should this epic be closed for the work that has been completed and a separate one opened for the remaining items? Or should the current epic remain open and get marked as not "In Progress" until we pick it back up?

**Comment by yeekangc** [comment]
> Status of remaining issues that were not part of MVP:
> 
> * [ ]  Issue [66](https://github.com/OpenLiberty/liberty-language-server/issues/66) - completed in LCLS and VS Code. Work remains in Eclipse and IntelliJ to enable it.
> * [x]  Issue [67](https://github.com/OpenLiberty/liberty-language-server/issues/67) - done
> * [ ]  Issue [68](https://github.com/OpenLiberty/liberty-language-server/issues/68) - minimal work started in a branch
> * [ ]  Issue [69](https://github.com/OpenLiberty/liberty-language-server/issues/69) - not started
> * [ ]  Issue [70](https://github.com/OpenLiberty/liberty-language-server/issues/70) - not started (but becomes somewhat moot once auto feature generation is turned on by default). Also, we added the `Enables` and `Enabled by` information when hovering over features in our most recent LCLS release `2.1.2`, which will be included in upcoming fix releases for Liberty Tools.
> 
> Those issues that are not done will not be worked on in the near future. Our priorities have shifted.
> 
> @NottyCode @yeekangc Should this epic be closed for the work that has been completed and a separate one opened for the remaining items? Or should the current epic remain open and get marked as not "In Progress" until we pick it back up?

Ref Cheryl's update and question, @NottyCode, thoughts on how this epic should be best handled?  Thank you.

**Comment by cherylking** [comment]
Updated status of remaining issues that were not part of MVP:


- [x] Issue https://github.com/OpenLiberty/liberty-language-server/issues/66 - completed in LCLS and VS Code. Work remains in Eclipse and IntelliJ to enable it. Update 11/04/25: This has been fixed in Eclipse and IntelliJ. Marking this complete.

- [x] Issue https://github.com/OpenLiberty/liberty-language-server/issues/67 - done

- [x] Issue https://github.com/OpenLiberty/liberty-language-server/issues/68 - done

- [x] Issue https://github.com/OpenLiberty/liberty-language-server/issues/69 - done

- [x] Issue https://github.com/OpenLiberty/liberty-language-server/issues/70 - not started (but becomes somewhat moot once auto feature generation is turned on by default). Also, we added the Enables and Enabled by information when hovering over features in LCLS release 2.1.2, which has been included in a fix release for Liberty Tools. Finally, now that we have more info available in the features.json and featurelist.xml related to platforms for features (due to versionless feature support), we can probably do a reasonable level of validation for incompatible features. We can have someone work on this in 2Q25. Update on 11/04/25: We added more validation/diagnostics in LCLS for incompatible features with the information available from featurelist.xml. I am marking this complete.

**Comment by cherylking** [comment]
All items have been completed and released in latest version of Liberty Tools available in the public marketplaces. I could not find an appropriate label to indicate that. I am closing this epic since it is done.
