### ISSUE TITLE
Developer builds using Github Actions

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#14808]
Create a system for "developer builds" (i.e. the builds that need to run for each pull request) based on Github Actions.

Documentation can be found here: https://github.com/OpenLiberty/open-liberty/wiki/Github-Actions-builds

**Comment by KyleAure** [comment]
Notes from EOI meeting questions: 

- [ ] Introduce a way to run all fats regardless of what change was made

- [ ] For fat changes run in lite and full mode 10 times similar to how current RTC builds run

- [ ] For concerns about space, is there a way to detect canceled workflows?  If so can we cleanup those artifacts earlier?
