### ISSUE TITLE
Improve tests for OpenAPI annotation scanning

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#14867]
When working on adding caching to OpenAPI 2.0, it looked like it may not scan WAR libs when the application was expanded.

We should ensure we test OpenAPI annotation scanning in multiple deployment scenarios including:
- [x] war containing libs (added in #14967)
- [x] ear containing war (added in #14967)
- [ ] ear containing war and additional libs
- [ ] war using library defined in server.xml
- [ ] ear using library defined in server.xml

We could also include testing of some more obtuse scenarios:
- [x] loose config configurations (added in #15384)
- [ ] ear containing jars which are not on the classpath
- [ ] jars referenced from classpath defined in war manifest

**Comment by Azquelt** [comment]
Some of these tests have been added already so I've updated the original comment to be a ticklist with references to the PRs that added them.

**Comment by Azquelt** [comment]
I wrote some more tests and discovered the following:
 - jax-rs does not discover root resources outside of the war and its libraries
   - i.e. root resources in ear libraries, libraries defined in the server.xml or listed in the .war's manifest classpath are not scanned for root resources
   - other classes can be in libraries and will be used (e.g. parameter or response types annotated with jsonb annotations)
 - smallrye openapi uses a single jandex index to retrieve class information
   - it expects to be able to find classes needed to generate the openapi document within that index

If we want to avoid wrongly scanning libraries for root resource classes but still pick up MP OpenAPI annotations from there, we'll need a change in smallrye. (Either providing two indexes, or providing a way to specify the root resources which we could find from the jaxrs feature)

**Comment by Azquelt** [comment]
Some tests have been added. Opened #17069 to address the problems encountered.
