### ISSUE TITLE
Shell variable support in server.env

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#14901]
## Description of the high level feature, including any external spec links:  

As a WAS administrator I want to be able to rely on config information provided by runtime platform.

As WebSphere Liberty is heavily used in cloud contexts, configuration options that need to be configured in the server.env file should allow the use of shell variables.

This is not allowed today: https://openliberty.io/docs/20.0.0.11/reference/config/server-configuration-overview.html#server-env.

RFE: https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=103332 (https://cloud-platform.ideas.aha.io/ideas/TWAS-I-249)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO: https://ibm.box.com/s/i0yyi6sgp6jwy4s6yd05ckwzcu3f4uj4
- FTS: https://github.com/OpenLiberty/open-liberty/issues/19563
- Open Liberty Documentation updates: https://github.com/OpenLiberty/docs/issues/4882
- Blog Post:   https://github.com/OpenLiberty/open-liberty/issues/19564
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ x ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ x ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ x ] Complete any follow-ons from the POC Review.
- [ x ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ N/A ] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [ x ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
   [Link to new documentation issue.](https://github.com/OpenLiberty/docs/issues/4882)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ x ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [ x ] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ N/A ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ x ] Implementation complete. (Epic owner / Feature owner)
- [ x ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ x ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ x ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [N/A ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ x ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ x ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ x ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by jimblye** [comment]
@NottyCode
Are there specific syntax requirements?   For example, how would one specify an environment variable on Windows vs Linux?
On Windows, if you sandwich the variable name between exclamation points (!!), eg. !WLP_OUTPUT_DIR!, that already works today.  If you want to ensure that the value does not have quotation marks then you can use the following syntax to remove quotation marks:  !WLP_OUTPUT_DIR:"=!

Example  **server.env**

WLP_OUTPUT_DIR=!MY_WLP_OUTPUT_DIR_ENV_VAR!

I think to use a different syntax, say ${var_name} or $var_name would be a bit more complicated and would require replacing $, ${, and }  with !.

On Linux, I'm thinking the syntax should be ${var_name} or $var_name.











On Linux, maybe $someVarName or ${someVarName}

**Comment by jimblye** [comment]
The current "server" script reads server.env from 4 locations - line by line.

I don't know the security implications of this, if any, but I found that reading line-by-line can simply be replaced by the source command.  Since server.env is basically just a properties file, all of the properties get assigned just by sourcing the file.   The scope is limited to the script.  So after the script terminates, those variables are not set in the environment.  The cool thing is that any environment variables specified in the server.env automagically get replaced by their values, and I didn't have to do anything overly complicated; i.e parsing with sed and regular expressions.

I commented out the call to readServerEnv and added 4 lines to just source the server.env.   I did that in 4 places.

```
# readServerEnv "${WLP_INSTALL_DIR}/etc/server.env"
 if [ -e "${WLP_INSTALL_DIR}/etc/server.env" ]
 then
   eval ". \"${WLP_INSTALL_DIR}/etc/server.env\""
 fi
```
 
That seems to work.   Question is, is there anything wrong with doing it that way?
I'm not sure what further testing needs to happen to be sure this doesn't break anything.

One other thing worth mentioning is that the reason I didn't just make the update in readServerEnv is that readServerEnv is overloaded and it reads other files as well.   So I would probably rename readServerEnv to something like readEnvFile.    I don't know if it makes sense to also "source" the other env files this way or not.

**Comment by jimblye** [comment]
This was on the design issues call for April 20, 2021.   
Sourcing the server.env would actually break support for having an odd number of single quotes in a value.
The solution must not require bash.
If we cannot find a solution that does not require bash, then a possible solution is to allow a callout script.   If the script exists, we would call it.  Customer would set variables in the script.

**Comment by NottyCode** [comment]
@jimblye given the discussion we have had so far I don't think we can go with a no design approval. Perhaps as things evolve we can reassess, but right now I think it needs the more formal process.

**Comment by samwatibm** [comment]
RFE's have moved:  https://cloud-platform.ideas.aha.io/ideas/TWAS-I-249

**Comment by jimblye** [comment]
Two options:

*** 1) Add a user script.    The server script will continue to process server.env as it does today, but after processing each server.env file, it will call a "serverEnv" shell script in which the customer can resolve shell variables. Of course, this removes the need for server.env, as everything can be done in the script.

We have zero migration,  since no one is forcing you to create a new script.  Tthe customer simply renames their server.env to serverEnv and makes it executable (  chmod +x) in order to have env/shell vars resolved..   That works except when they use single quotes (') in variable names or in values.  In which, case (if they have an odd number of quotes) they need to escape quotes where necessary; for example:  MESSAGE1='Don\'t do that'

On Windows, there is no need for a user script, as shell and environment variables can already be resolved today using delayed expansion syntax ( !var! ).   However, if we want to add the user script capability because we added it to Linux, they would rename server.env to serverEnv.bat.  They would need to insert the "set" command in front of each assignment.   Note windows does NOT seem to have a problem with an odd number of single quotes (').

*** 2)  Use the source command, but for zero migration, the customer has to enable the new feature.   I propose that the customer just add server_env_version='2' to the server.env file to enable the new capability.   The server script would process the server.env file as it does today, but if it encounters this indicator, it will stop reading server.env, and execute "source server.env".   The user can put **server_env_version='2'** anywhere in the file, but it makes more sense to be the first line of the file to avoid reading the file twice.   This option also requires the user to escape single quotes where needed if they enable the feature.

This option is not applicable to Windows, since there is no source command on Windows.   But again environment & shell variables already resolve in server.env on Windows.

**Comment by jimblye** [comment]
Link to UFO: https://ibm.box.com/s/i0yyi6sgp6jwy4s6yd05ckwzcu3f4uj4
All issues resolved.
Ready for design approval.

**Comment by chirp1** [comment]
Jim provided the doc info at https://github.com/OpenLiberty/docs/issues/4882. Approving the epic.

**Comment by jimblye** [comment]
###Serviceability
@donbourne  - Note this isn't actually a feature.  It's more like an enhancement to the server script.  So most of this does not seem applicable.

UFO: Does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR? Have these issues been addressed in the implementation?    **I can't think of any problems the customer will encounter other than not enabling the feature, which is required on non-Windows systems, and maybe not setting the environment variable that they want to expand.  I don't see anything we can do about either of those.**

Test and Demo: As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team). 
   a) What problem paths were tested and demonstrated?  There is a FAT test for the case where customer forgets to enable variable expansion.
   b) Who did you demo to?   **end-of-iteration demo scheduled - Jan 11,2022.   It's pretty straight forward.**
   c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?   **N/A**

SVT: SVT team is often the first team to try new features and often encounters problems setting up and using them. Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered. 
    a) Who conducted SVT tests for this feature?   **N/A**
    b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3? **N/A**

Service: Which L2 / L3 queues will handle PMRs for this feature?  **Kernel**
Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it. Ask Don Bourne if you need links or more info.

Metrics: Does this feature add any new metrics or emit any new JSON events? ** no ** If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?  **N/A**

**Comment by jimblye** [comment]
@samwatibm  No new messages.  Globalization is N/A

**Comment by jimblye** [comment]
@steven1046 Accessibility is N/A for this one.  Can you add the label?

**Comment by jimblye** [comment]
@hanczaryk  - I believe SVT is also N/A for this one.
