### ISSUE TITLE
Add support for setting JVM working dir

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#15128]
As a Liberty Administrator, I would like to set the JVM working dir independent of the server output dir.

Use case: I want to be able to control where heap dumps end up and not require log4 to always prefix the paths with logs/ or use a fully qualified log path as that is pretty un-portable.

RFE: https://www.ibm.com/developerworks/rfe/execute?use_case=viewChangeRequest&CR_ID=98086

**Comment by cbridgha** [comment]
Alasdair's Proto PR: https://github.com/OpenLiberty/open-liberty/pull/12713

**Comment by samwatibm** [comment]
RFE's have moved:  https://cloud-platform.ideas.aha.io/ideas/TWAS-I-148

**Comment by NottyCode** [comment]
@hlhoots to give you a no design approval I do need the description to describe the design of this.

**Comment by hlhoots** [comment]
@NottyCode will do; I had put that request on earlier in the week.  After that I thought of a couple more things I wanted to play around with before I put that text in here.  I should have it here sometime mid-next-week after the ATO conference.

**Comment by hlhoots** [comment]
High Level Explanation of this function:

Users would like to have a setting that allows them to set the working directory for the JVM utilized by Open Liberty.  Currently, the Open Liberty JVM currently outputs information like java dumps, etc to the ${WLP_OUTPUT_DIR}/serverName location (which by default is /wlp/usr/servers/serverName/).  There needs to be a mechanism by which to change this default value.

This enhancement would allow the user to specify the SERVER_WORKING_DIR environment variable and set the location to something other than the ${WLP_OUTPUT_DIR}/serverName location.  The request from the RFE is to NOT make this a fully qualified path for portability purposes.  Thus a path that is relative to the ${WLP_OUTPUT_DIR}/serverName location can be used, as well as, an absolute path.

So for example, the user could set the Open Liberty JVM output to be added to the ${WLP_OUTPUT_DIR}/serverName/logs location so that all JVM related data would be in with the server log data(relative path example):

SERVER_WORKING_DIR=logs

Or the end user could move the information outside of the ${WLP_OUTPUT_DIR}/serverName location by doing something similar to the following (which would put the data in the /wlp/usr/servers/logs/ folder and is an absolute path example):

SERVER_WORKING_DIR=/wlp/usr/servers/logs/

This enhancement gives users more flexibility regarding the location of the Open Liberty JVM output.

**NOTE:**  This function is being implemented at the scripting level and will not support property substitution values as part of the SERVER_WORKING_DIR environment variable.

**Comment by hlhoots** [comment]
## Description of the high level feature, including any external spec links:  
The description needs to be detailed enough such that it can be [prioritized on the backlog](https://github.com/orgs/OpenLiberty/projects/2) and implemented by the development team.
<br/><br/><br/>  


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:
- FTS: https://github.com/OpenLiberty/open-liberty/issues/19432
- Beta Blog Post (if applicable):
- Blog Post: https://github.com/OpenLiberty/open-liberty/issues/19442
- Aha: https://cloud-platform.ideas.aha.io/ideas/TWAS-I-148


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [x] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [ ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
#### Before proceeding to any items below (active development), this feature MUST be [prioritized on the backlog](https://github.com/orgs/OpenLiberty/projects/2), and have been socialized (e.g., UFO Review).  Follow the Feature and UFO Approval Process.
##

## **Development**
When active development has begun 
- [x] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.


## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by hlhoots** [comment]
@NottyCode Ready for a quick review when you have a second.  See above content on design.

cc @cbridgha

**Comment by NottyCode** [comment]
@hlhoots We need to add this new variable to the documentation [here](https://github.com/OpenLiberty/docs/blob/vNext/modules/reference/pages/directory-locations-properties.adoc). I couldn't find a docs item for this. If it exists can you make sure it is linked to this item, and if not please raise it.

**Comment by hlhoots** [comment]
Feature Test Summary : https://github.com/OpenLiberty/open-liberty/issues/19432

**Comment by hlhoots** [comment]
GA Blog Issue: #19442

**Comment by chirp1** [comment]
Harry included the info to be documented at https://github.com/OpenLiberty/docs/issues/4880 Approving.

**Comment by hlhoots** [comment]
@samwatibm hi Sam -- No new messages / translation for this one.  Can you add the globalization tag for me?

**Comment by dave-waddling** [comment]
Hi, as per the Feature Test Summary there is an outstanding test bug, but it is minor and easily fixed (already in progress). I'm happy to grant the FAT Focal Approval at this time.

**Comment by hlhoots** [comment]
Should be in the latest GM.  Closing epic for now.
