### ISSUE TITLE
Add support to add 'expandLocation' property for autoExpanded Apps.

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#15132]
Currently - when using the "autoExpand" A static directory (AppManagerConstants.EXPANDED_APPS_DIR)+ {appname} - or "apps/expanded/{appname}". is always used for destination of the unzipped app.

An additional config property could be added (targetDir=xxxx) that would be used as the zip target.

**Comment by hlhoots** [comment]
High Level Explanation of the function:

This enhancement would allow the user to specify a target directory (targetDir) on the applicationManager configuration.  As currently implemented, when an application is autoExpanded the default location for the expanded files is ${server.config.dir}/apps/expanded/.  After this change, the user would be able to configure that location to a new value on the filesystem.  Thus for example:

<applicationManager autoExpand="true" targetDir="${server.config.dir}/myApps/" /> 

would result in the expanded application belong located at ${server.config.dir}/myApps/expanded/

This enhancement gives users more flexibility regarding the location of their expanded applications.

**Comment by NottyCode** [comment]
@hlhoots I wouldn't go with targetDir, since the attribute name doesn't explain what the target is used for. I think something like expandLocation would make more sense. I assume this would be ibm:type="location(dir)"? The default would be `${server.config.dir}/apps/expand`?

**Comment by hlhoots** [comment]
@NottyCode 

That sounds good to change the attribute to expandLocation. 

Yes, on the metadata type.  It would be ibm:type="location(dir)".

So on the default, you have it ending with /expand above (${server.config.dir}/apps/expand).  Do we want it to change from the current default which is ${server.config.dir}/apps/expand**ed**? Let me know if I missing something there.

Also, when the user sets the expandLocation attribute, do we want to append "/expanded/" to the end of the supplied string or just let them use whatever string value they want?

ex
\<applicationManager autoExpand="true" expandLocation="${server.config.dir}/myApps/version_1" />
if we append the value it would result in ${server.config.dir}/myApps/version_1/**expanded**/{appName}.war
else as-is string it would just be ${server.config.dir}/myApps/version_1/{appName}.war

**Comment by NottyCode** [comment]
@hlhoots I think we should set the default for expandLocation to be `${server.config.dir}/apps/expanded` so there is no behaviour change. I'll correct my prior incorrect comment. I do not think we should add anything to the end of the provided location, what they provide is the directory we should use if we append something we will only get a request from someone to not do that which will require more config.

**Comment by hlhoots** [comment]
Thanks @NottyCode  

Sounds good.  Will make those changes.  Please let me know about approving the No Design Approval Request tag -> No Design Approved tag.

**Comment by hlhoots** [comment]
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)
 
Instructions:
 - Do the actions below and mark them complete in the checklist when they are done.
 - Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **Before Development Starts or 8 weeks before Onboarding** 
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.

- [ ]  Add "Design Approval Request" tag
- [ ] Design / UFO Approval (Alasdair Nottingham) or N/A.
- [ ] No Design / No UFO Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [ ] Create a child task of the epic entitled "FAT Approval Test Summary".  Add and fill in the template as described here: https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process . Mark "FAT complete" on the Epic when it's ready for review
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **3 weeks before Onboarding** 
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE ** 3 weeks before Onboarding** 
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **2 weeks before Onboarding** 
- [ ] Implementation complete. (Epic owner / Feature owner) 
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## APPROVALS with TARGET COMPLETION DATE **2 to 1 week before Onboarding** 

 
### Prerequisites
- You must have the Design Approved or No Design Approved label on the GitHub Epic.

- If the feature is not part of Liberty, set `target:ga` label in this epic so it is on the approvers' radar.

### Approvals
- [ ] **Accessibility** - (G Scott Johnston). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **FAT Liberty SOE** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Globalization** (Sam Wong - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.
- [ ] **ID** - (Kareen Deen). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - (Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - (Don Bourne). Serviceability has been addressed. 
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - (Greg Ecock - Cloud, Brian Hanczaryk- APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.
- [ ] **Demo** - (Tom Evans or Chuck Bridgham). Demo is scheduled for an upcoming EOI. (If Feature is not easily demoable - please present slide explaining enhancement) Approver adds label focalApproved:demo to the Epic in Github.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## TARGET COMPLETION DATE **1 week before Onboarding** 
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / Backlog Subtribe PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## NOT REQUIRED FOR A FEATURE
- [ ] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A. 
- [ ] **WDT** - (Erin Harris). WDT work complete or N/A.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Related Deliverables TARGET COMPLETION DATE **General Availability** 
- [ ] Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by hlhoots** [comment]
OL docs update issue created here: https://github.com/OpenLiberty/docs/issues/3521

**Comment by hlhoots** [comment]
This item requires that #15958 be closed before delivering to GA.

**Comment by hlhoots** [comment]
Removed beta fence in pr #16131.  This item is ready to GA.

**Comment by hlhoots** [comment]
Closing as work is done
