### ISSUE TITLE
Beta and later GA the HandleList function

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#15158]
For Beta and/or GA of HandleList
- [x] remove dependency on noShip feature from
  /com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.emptyHandleListContext-1.0.feature
- [x] remove usage of noShip feature from
  /com.ibm.ws.concurrent_fat_db/publish/servers/concurrent_fat_db/server.xml
- [x] metatype
   autoCloseConnections switch from internal --> beta --> ga
   autoCloseConnections specify default value (upon ga, not beta)
- [x] ConnectionManagerServiceImpl
   interpret null autoCloseConnections (possible for DataSourceDefintion/ConnectionFactoryDefinition) as default value
- [x] check test buckets for TODO comments that might have been missed
   /com.ibm.ws.jca_fat
   /com.ibm.ws.jca_fat_derbyra
   /com.ibm.ws.jdbc_fat_loadfromapp
   /com.ibm.ws.jdbc_fat_v43
   /com.ibm.ws.concurrent_fat_db
