### ISSUE TITLE
KRB5: GA checklist for Kerberos feature for LdapRegistry

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#15722]
For #12794

When we've met all approvals, make sure we've:

- [x] Remove all the beta fencing (`LdapConnection` and `com.ibm.ws.kernel.boot.core;version=latest` from the wim.adapter.ldap bnd.bnd file and remove `testBetaFenceForBindAuthMech` from `LdapRegressionTests` and remove `CWWKE0701E` from teardown
- [x]  Update the metatype to have the appropriate tags and messages
- [x]  Enable simple as the default on the bindAuthMechanism
- [x]  Enable `ContextManagerTest.testToStringKRB5`
- [x]  Remove beta jvm options from `com.ibm.ws.security.wim.adapter.ldap_fat.krb5` `jvm.options`
- [x]  Check `com.ibm.ws.security.wim.adapter.ldap_fat.krb5` `bootstrap.properties`
- [x]  Run all LDAP security tests as regression
- [x] Run all DB Auth Kerberos tests as regression
- [x] Run all spnego tests as regression
- [x] Remove runtime `-Dcom.ibm.ws.beta.edition=true` in krb fat tests

On 4/15, ran PB with lite FATs and these Full FATs: `com.ibm.ws.security.wim.adapter.ldap_fat.krb5,com.ibm.ws.security.wim.adapter.ldap_fat,com.ibm.ws.security.wim.scim_fat,com.ibm.ws.security.wim.core_fat,com.ibm.ws.security.wim.registry_fat,com.ibm.ws.jdbc_fat_krb5,com.ibm.ws.security.spnego_fat,com.ibm.ws.security.spnego_fat.1,com.ibm.ws.security.spnego_fat.2`
