### ISSUE TITLE
LG-303: Provide format option for messages.log/console that looks like WAS basic

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#15910]
## Description of the high level feature, including any external spec links:  
The description needs to be detailed enough such that it can be [prioritized on the backlog](https://github.com/orgs/OpenLiberty/projects/2) and implemented by the development team.

see https://github.com/OpenLiberty/open-liberty/issues/15626

This will enable people that have log parsers that work with tWAS basic format to use the same parsers with OL logs.

The OL trace "basic" format already matches the tWAS basic format, so may be able to reuse that formatter.

Need to decide what to name this new format ("basic" would conflict with what we used to call "basic", and now call "simple" for messages.log)

------
Design:

A new logging format option, **TBASIC**, is added to match the tWAS basic logging format. This is a new format for both consoleFormat and messageFormat and is added as an alias for the BASIC format option for traceFormat. 

The three options being added are the following:
```
trace.tbasic=Alias for the basic trace format.
message.format.tbasic=Use the tbasic logging format.
console.format.tbasic=Use the tbasic logging format.
```
Using the TBASIC format will allow customers who have tWAS log parsers to easily parse Liberty logs without any changes required.  

TBASIC Logs Example:
```
[24/03/21 15:04:10:331 EDT] 00000001 FrameworkMana A   CWWKE0001I: The server defaultServer has been launched.
[24/03/21 15:04:11:338 EDT] 00000001 FrameworkMana I   CWWKE0002I: The kernel started after 1.177 seconds
[24/03/21 15:04:11:465 EDT] 0000003e FeatureManage I   CWWKF0007I: Feature update started.
[24/03/21 15:04:11:635 EDT] 00000033 DropinMonitor A   CWWKZ0058I: Monitoring dropins for applications.
```

This format will also include the method and class names in the logs when supplied:
```
[17/03/21 13:42:12:303 EDT] 0000003e FeatureManage A   CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 25.975 seconds.
[17/03/21 13:42:33:328 EDT] 00000063 servlet       I com.ibm.ws.webcontainer.servlet.ServletWrapper init SRVE0242I: [badapp] [/badapp] [com.ibm.ws.lumberjack.badness.Angry]: Initialization successful.
[17/03/21 13:42:33:333 EDT] 00000063 Angry         W   BADAP0001W: quit bugging me.
[17/03/21 13:42:33:334 EDT] 00000063 Angry         I com.ibm.ws.lumberjack.badness.Angry dummyMethod BADAP0001W: Message test
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:
- FTS: https://github.com/OpenLiberty/open-liberty/issues/17938
- Beta Blog Post (if applicable):  https://github.com/OpenLiberty/open-liberty/issues/17152
- Blog Post:  https://openliberty.io/blog/2021/07/12/logging-format-21008-beta.html#tbasic (already included in 21008 beta blog)
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [x] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [x] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [x] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [x] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [x] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)
-Issue created: #18295 

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by tonyreigns** [comment]
Customers are currently looking to have a similar configurable format to the "basic" format that is currently found in the traceFormat options. This is required in order to have a similar log format as traditional WAS logs.

Due to the "basic" keyword being a deprecated alias for the "Simple" keyword, the new format option will be "**tbasic**" for both messageFormat and consoleFormat and will also be made an alias for "basic" in traceFormat to keep consistency.

The three options being added are the following:
`trace.tbasic=Alias for the basic trace format.
message.format.tbasic=Use the tbasic logging format.
console.format.tbasic=Use the tbasic logging format.
`

**Comment by tonyreigns** [comment]
When the tbasic format option is used for messageFormat, thee messages.log will appear in this format:
```
[12/03/21 10:19:45:462 EST] 00000001 FrameworkMana                                                A CWWKE0001I: The server defaultServer has been launched.
[12/03/21 10:20:19:500 EST] 00000001 FrameworkMana                                                I CWWKE0002I: The kernel started after 34.376 seconds
```

When the tbasic format option is used for consoleFormat, the console.log will appear in this format:
`[12/03/21 10:28:01:858 EST] 0000003e FeatureManage                                                A CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 14.582 seconds.
`

**Comment by fmhwong** [comment]
@tonyreigns  Do we need the long white space between the class name and the log level in the messages.log?

**Comment by fmhwong** [comment]
If we are going to match tWAS, here are a few lines from SystemOut.log

```
[3/12/21 13:52:52:626 EST] 0000004c SchedulerServ I   SCHD0077I: The Scheduler Service is starting the Schedulers.
[3/12/21 13:52:52:626 EST] 0000004c SchedulerServ I   SCHD0078I: The Scheduler Service has completed starting the Schedulers.
[3/12/21 13:52:52:689 EST] 00000001 GridConfigura I   CWLRB5873I: The GridConfiguratorMBean was activated successfully.
[3/12/21 13:52:52:704 EST] 00000001 BatchSensorCo I   CWLRB5904I: BatchSensorComponent starting...
[3/12/21 13:52:52:766 EST] 00000001 BatchSensorCo I   CWLRB5905I: Successfully activated GridEndpointSensorMBean.
[3/12/21 13:52:52:814 EST] 00000001 RMIConnectorC A   ADMC0026I: The RMI Connector is available at port 2809
[3/12/21 13:52:52:829 EST] 00000001 JMXConnectors I   ADMC0058I: The JMX JSR160RMI connector is available at port 2809
[3/12/21 13:52:52:907 EST] 00000001 WsServerImpl  A   WSVR0001I: Server server1 open for e-business
```

**Comment by tonyreigns** [comment]
> @tonyreigns Do we need the long white space between the class name and the log level in the messages.log?

I just spoke to Don about it and no we don't need those and they'll be removed. I'm just checking on something else first to make sure the format is the same in another case.

**Comment by fmhwong** [comment]
@tonyreigns Can you re-post the messages.log and console.log after you adjusted the spaces?

**Comment by tonyreigns** [comment]
```
[15/03/21 12:19:15:766 EDT] 00000001 FrameworkMana A   CWWKE0001I: The server defaultServer has been launched.
[15/03/21 12:19:31:744 EDT] 0000006f DropinMonitor A   CWWKZ0058I: Monitoring dropins for applications.
[15/03/21 12:19:33:181 EDT] 0000003e FeatureManage A   CWWKF0012I: The server installed the following features: [el-3.0, jsp-2.3, osgiConsole-1.0, servlet-3.1].
[15/03/21 12:19:33:182 EDT] 0000003e FeatureManage A   CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 17.610 seconds.
[15/03/21 12:20:41:764 EDT] 0000002e ServerCommand A   CWWKE0055I: Server shutdown requested on Monday, March 15, 2021 at 12:20 PM. The server defaultServer is shutting down.
[15/03/21 12:20:41:774 EDT] 0000007a RuntimeUpdate A   CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[15/03/21 12:20:43:992 EDT] 00000001 FrameworkMana A   CWWKE0036I: The server defaultServer stopped after 1 minutes, 28.419 seconds.

```

**Comment by tonyreigns** [comment]
Added a change to include class/method names when provided.

Example:

```
[17/03/21 13:42:12:303 EDT] 0000003e FeatureManage A   CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 25.975 seconds.
[17/03/21 13:42:33:328 EDT] 00000063 servlet       I com.ibm.ws.webcontainer.servlet.ServletWrapper init SRVE0242I: [badapp] [/badapp] [com.ibm.ws.lumberjack.badness.Angry]: Initialization successful.
[17/03/21 13:42:33:333 EDT] 00000063 Angry         W   BADAP0001W: quit bugging me.
[17/03/21 13:42:33:334 EDT] 00000063 Angry         I com.ibm.ws.lumberjack.badness.Angry dummyMethod BADAP0001W: Message test
```

**Comment by NottyCode** [comment]
I'd like to have a single comment with the design post discussion so I can make sure I haven't misunderstood before giving no design approval? Thanks

**Comment by tonyreigns** [comment]
I've updated the original issue comment with our final design. @NottyCode

**Comment by pgunapal** [comment]
Updated first comment with the Feature complete checklist.

**Comment by sabolo** [comment]
If this feature is ready for review, please can you complete all the links in the template to things like the FTS and UFO.  Thanks

**Comment by tonyreigns** [comment]
> If this feature is ready for review, please can you complete all the links in the template to things like the FTS and UFO. Thanks

Sorry about that, I've included all the links now. We don't have a UFO but we have a no design approval. Everything is approved aside from the FTS. Just a note that this feature was included in both 21008 and 21009 betas.
