### ISSUE TITLE
Fix identified bugs

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1591]
- [x] produce document for ear apps (#1545)
- [x] Default global server specified by the /openapi document is not consistent - Changing the port also is not handled correctly until server restarts - https://github.ibm.com/was-liberty/WS-CD-Open/issues/9695
- [x] When two apps with OpenAPI doc are deployed, doc from the first one is picked up. But when this app is removed, the doc from the second one isn't being picked up. (This issue and above could be related - same cause/fix) -
 https://github.ibm.com/was-liberty/WS-CD-Open/issues/9696
- [x] SVT: @ApplicationPath("/weather") doesn't show in paths in api documentation -
 https://github.ibm.com/was-liberty/WS-CD-Open/issues/9896
- [x] Hitting /api/explorer in Chrome throws warning messages: [WARNING ] SRVE0190E: File not found: /favicon-16x16.png or [WARNING ] SRVE0190E: File not found: /favicon-32x32.png.
- [x] Hitting localhost:9080/openapi/explorer works the same as localhost:9080/openapi, it returns the openapi document. In CL you get Error 404: javax.servlet.ServletException: java.io.FileNotFoundException: SRVE0190E: File not found: /explorer

**Comment by mrglavas** [comment]
@leochr Can this epic be closed? I see one task that wasn't started. Perhaps move under a technical debt epic from 1Q2018.

**Comment by leochr** [comment]
Moved the issue under technical debt. Closing this.
