### ISSUE TITLE
Enable JPA bind literal as parameter at a server scope

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#15979]
## Issue
Enabling EclipseLink to bind a literal as a parameter requires a `persistence.xml` to be updated:

```xml
    <persistence-unit name="TestPU" transaction-type="JTA">
        <jta-data-source>jdbc/jpaDataSource</jta-data-source>  
        <properties>
            <property name="eclipselink.target-database-properties" value="shouldBindLiterals=true"/>
        </properties>
    </persistence-unit>
```

There may be many `persistence.xml` files, spread across several applications, in a Liberty server. This makes it very difficult to add a persistence property to all `persistence.xml` files; requiring repackaging/rebuilding of possibly hundreds of applications. It would be good to be able to configure this for all `persistence.xmls` in the server.

## Description of the high level feature, including any external spec links: 

This feature will enable the configuration of default persistence properties in server.xml, using the existing JPA container configuration `<jpa>`. The new `defaultProperties` format will follow the format used in `persistence.xml` as follows:

```xml
    <jpa>
        <defaultProperties>
            <property name="javax.persistence.lock.timeout" value="10000"/>
            <property name="eclipselink.target-database-properties" value="shouldBindLiterals=true"/>
        </defaultProperties>
    </jpa>
```

The new properties will be described as:

> Default, integration-level persistence properties for use by the persistence provider when a container managed entity manager factory is created. Specified persistence properties will be included when the PersistenceProvider.createContainerEntityManagerFactory method is called.

According to the JPA specification (3.4.4.3):
```
If the same property or hint is specified more than once, the following order of overriding applies, in
order of decreasing precedence:
    • argument to method of EntityManager, Query, or TypedQuery interface
    • specification to NamedQuery (annotation or XML)
    • argument to createEntityManagerFactory method
    • specification in persistence.xml
```

This means these `defaultProperties` values will override the same properties specified in `persistence.xml`. However, property values specified through PersistenceContext annotation, or the _persistence-context-ref_ deployment descriptor element, will override these `defaultProperties`.

Basically, the new `defaultProperties` provide a mechanism to apply a persistence property to all `EntityManager` instances that do not currently have the property specifically configured.

In the event a default property is configured incorrectly (empty name or value), the following warning will be logged and the property ignored:

> CWWJP0056W: A JPA default property configured in the server.xml file contains an empty name or empty value: name = [No Value], value = []. The property will be ignored.

Note: the ability to override an entire persistence unit could also be useful, but that would really need to be done on a per application basis, and should involve supporting the entire contents of `persistence.xml` in `server.xml` under the `application` element.... and will NOT be addressed as part of this issue. Overriding all persistence units would be more complex and not resolve the requested support to easily add a property to all container managed persistence contexts.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO: None (See description above)
- FTS: #17551
- Beta Blog Post (if applicable):
- Blog Post: 
- Aha: https://cloud-platform.ideas.aha.io/ideas/TWAS-I-18            ([Old RFE Link](https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=148566))
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [x] POC Design / UFO Review Scheduled (David Chang) or **N/A**.
- [x] POC Design / UFO Reviewed (Feature Owner) or **N/A**.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or **N/A**.
- [x] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [x] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point) or **N/A**
- [x] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [x] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [x] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [x] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update) : https://github.com/OpenLiberty/open-liberty/issues/19398

## **Legal**
3 weeks before Onboarding
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or **N/A**. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [x] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [x] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)
https://github.com/OpenLiberty/open-liberty/issues/19398

## **Other deliverbles**
- [x] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or **N/A**.
- [x] **WDT** - (Leonard Theivendra). WDT work complete or **N/A**.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by NottyCode** [comment]
@tkburroughs @dazey3 I know this is probably too late and I've approved, but have you considered configuration like this:

    <jpa defaultJtaDataSourceJndiName="jdbc/JTA_DS1">
        <defaultProperties javax.persistence.lock.timeout="10000" 
                           eclipselink.target-database-properties="shouldBindLiterals=true" />
    </jpa>
    
it wouldn't support property names that aren't valid attribute names, but I think he two cited arguments are and this would be more concise?

**Comment by dazey3** [comment]
@NottyCode I believe we did consider that as an alternative. One mark in favor of that option was that we could provide tooltip descriptions for the properties for EclipseLink IDE!

However, we felt that keeping the format in sync with persistence.xml property format was cleaner and more succinct. 

Also, the benefit of tooltips is only as valuable as the information we input. We had to weight the expectation of customers that all "javax.persistence.*" properties would be documented + EclipseLink properties. We might have decided to add progressively over a long term, but it started to feel outside the bounds of this feature.

**Comment by tkburroughs** [comment]
@NottyCode Yes, I actually did two rough prototypes of this function and demo'd  them to the team before we decided on the documented design above.  The first was pretty much as shown in your comment and the second is the selected current design.

While the example in your comment is more concise, we felt the user experience would be better if the format between server.xml and persistence.xml was the same.  Basically, this is comparable to a user being able to add `ejb-jar.xml` or `web.xml` in server.xml.  Technically, this would only be a portion of persistence.xml; but we also considered that in the future it may be desirable to alllow the full persistence.xml in server.xml, though it would be under `<application>`, the same as ejb-jar.xml and web.xml appear in server.xml. A user would be able to copy properties between persistence.xml, and both sections in server.xml (assuming we ever supported the application level) without changing format.

Also, while the more concise design would allow tooltips, and even different properties per vendor (open jpa, ecliselink, hybernate), we felt it may cause issues going forward as likely not all properties would be accounted for and become out of sync rapidly.

**Comment by jkleinlercher** [comment]
Are there any news on this? We are heavily waiting for this feature ..

**Comment by tkburroughs** [comment]
> Are there any news on this? We are heavily waiting for this feature ..

@jkleinlercher development for this issue is proceeding and a preview of the feature should be available in the 22.0.0.1-beta release tentatively scheduled for November 26.

**Comment by tkburroughs** [comment]
@tevans78 or @cbridgha This feature has been added to the next EOI agenda for a demo.

**Comment by dazey3** [comment]
The only thing left is the blog post to be created!
