### ISSUE TITLE
Standalone (Java SE) REST Client

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#16684]
## Description of the high level feature, including any external spec links:  
<br/><br/><br/>  
The idea of this feature is to create a single maven-accessible artifact that includes a Liberty REST client. Users would be able to develop and run a REST client (either JAX-RS Client or MicroProfile Rest Client) outside of a managed runtime (i.e. Java SE).  As much as possible, code running with this standalone client should behave the same as if that code were running inside a Liberty server (with the appropriate features enabled - such as `jaxrsClient-2.1`, `mpRestClient-2.0`, etc.).

Related design issue #16326

##
#### Before proceeding to any items below (active development), this feature must be prioritized on the backlog, and have either the "Design Approved" or "No Design Approved" labels.  Follow the Feature and UFO Approval Process.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), and blogs post issues(s):
- UFO: https://ibm.box.com/s/bi2yug7lyno0aw86zllbmsv5mnx7xgge
- FTS:
- Beta Blog Post (if applicable):
- Blog Post: 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [ ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by cthigh** [comment]
UFO Review Notes for Part 1 - June 21, 2021.

Slide 8: 
Does this include HTTP only?  No - includes HTTPS.  Not JMS or KAFKA.  Clarify that HTTPS is supported.


- [x] Slide 10 - To-Be

  - Related to bullet 2, document what will and will not work in a Java SE environment.
  - Clarify/document that this new client will be EE 8 and later and will not work with EE7 or older.  Intended for a Java SE environment. 

- [x] Slide 11 - Feature Design

  - Discussion whether the new JAR included in the Open Liberty image.  Update slide to say that JAR will not including it in the install image.
  - Every version of Open Liberty will produce a new JAR to the Maven Repository.  Continuous update.  Versioning to follow Liberty versioning. Define the versioning.
  - How is the artifact naming going to to be different for Java EE versus Jakarta?  

- [x] Slide 13 - Java APIs/SPIs
  - Add MicroProfile REST Client 2.0
  - Anything to help JWT?  No.  Separate dependency.
  - Discussion around the EE features for a Java SE client - CDI in particular.  Not sure the dependencies can be carved out.  Andy to investigate.  Might have to ship APIs but not support or figure out how to carve it out. Be clear what is supported. 

- [x] Slide 15 - Admin / Config / Command Line
  - Document how to consume this artifact with Maven and Gradle.  Give details of the artifact name.

- [x] Slide 20  - Beta 
  -  Will Beta labeling be used?  Beta labeling is published to a different group. ID. Normally early releases are provided as snapshots in the Maven repository.

- [ ] Slide 21 - Automated Tests 
  - Concerns over the test strategy if too much is added to the class path.  
  - Will automated tests be added for standalone CDI, JWT? 
  - Be clear what will and will not being tested.  I.e., clarify what’s supported.

**Comment by cthigh** [comment]
UFO Review Notes for Part 2 - June 29 

Part 1 ended with the System Test page.

- [ ] Page 15 - Maven coordinates normally use dashes instead of dots.    [Tom]

	- For example:  standalone-rest-client-jakartaee8 
	- Should this have a different groupId?  Io.openliberty.client
        - Note: Features tend to use dots except for before the version number.  https://search.maven.org/search?q=openliberty

- [ ] Page 26 - Serviceability - will take salesforce case but this is an Open Liberty artifact not shipped with Open Liberty or WebSphere Liberty. Add note to page. [Tom]

General discussion at the end:

- [ ] Page 13 - Discussion came back up on whether all the APIs and implementations should be packaged in a single JAR for convenience.  Why not provide a POM dependency versus provide a single JAR?  During design issues discussions, Alasdair advocated for a single JAR file.  Some advocate that it is cleaner to package the APIs as a single jar and bring in the dependencies as separate dependencies.  Doesn’t help for a java command line app and might have mixed dependencies. How will Java 11 module-info affect all this with APIs and implementations in the same uber jar? Will take this to a design issues call for follow-up. [Emily, Andrew]

**Comment by scottkurz** [comment]
I missed the Part 2 discussion, but one thought I had that might overlap the single JAR vs. POM dependency discussion is whether we want to provide a simple, transparent build to allow a user to compose their own customized aggregate client JAR using standard maven dependency mechanisms:  dependencyManagement, exclusions, etc. 

I'm not sure I'm even taking a side on single JAR vs. POM ... I might just be expressing a separate use case, and just suggesting we have a more transparent build and not one that does some opaque custom packaging that's harder to integrate with things like exclusions.        E.g. "I don't want to wait for Open Liberty to pull in depABC version X.Y.Z so I'll built my own JAR in the meantime".

Of course, that's not to say a user's custom composition should be "supported".
