### ISSUE TITLE
MicroProfile 5.0 Release

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#16991]
## MicroProfile 5.0 Release
<br/><br/><br/>  

This feature will align with Jakarta EE 9 with jakarta namespace change. Most of MP features imports javax packages will need to be updated to import jakarta packages instead. This potentially forces a number of 8 MP features to do a major release.

Although these are major version releases, most of the implementations are just transformations of the previous version. Therefore, 7 of the components will simply be included as part of this umbrella feature. The 8th component, MP Rest Client 3.0, has some additional changes and therefore has its own top level feature.

Component features:
- [ ] Support Rest Client 3.0 - [issue](https://github.com/OpenLiberty/open-liberty/issues/17947)

Component stories:
- [ ] Support Config 3.0 - [issue](https://github.com/OpenLiberty/open-liberty/issues/17766)
- [ ] Support Fault Tolerance 4.0 - [issue](https://github.com/OpenLiberty/open-liberty/issues/17767)
- [ ] Support Metrics 4.0 -  [issue](https://github.com/OpenLiberty/open-liberty/issues/17794)
- [ ] Support Health 4.0 -  [issue](https://github.com/OpenLiberty/open-liberty/issues/17795)
- [ ] Support Open Tracing 3.0 -  [issue](https://github.com/OpenLiberty/open-liberty/issues/17796)
- [ ] Support Open API 3.0 - [issue](https://github.com/OpenLiberty/open-liberty/issues/17772)
- [ ] Support JWT 2.0 - [issue](https://github.com/OpenLiberty/open-liberty/issues/17844)

Additionally a Liberty value-add feature depends on mpJWT API.  This will be covered under the following story:
- [ ] Support EE9 and MP 5 for jwtSso-1.0 - [issue](https://github.com/OpenLiberty/open-liberty/issues/19150)

The release date has not been finalised. I would like to propose to target October release.

##
#### Before proceeding to any items below (active development), this feature must be prioritized on the backlog, and have either the "Design Approved" or "No Design Approved" labels.  Follow the Feature and UFO Approval Process.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), and blogs post issues(s):
- UFO: https://ibm.box.com/s/63qgphboznsmk0z7s287dh051c3ke2zb
- FTS: https://github.com/OpenLiberty/open-liberty/issues/19080
- Beta Blog Post (if applicable):
- Blog Post: 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [ ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [x] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by Emily-Jiang** [comment]
Minor ID: https://github.com/OpenLiberty/open-liberty/issues/18976

**Comment by NottyCode** [comment]
@Emily-Jiang we should probably talk about this having a no design approval. I know I said we didn't generally need one, but I'm not sure that having no design discussion about anything in MP 5.0 isn't a good idea.

**Comment by Emily-Jiang** [comment]
@NottyCode sure, originally I put this one with UFO design before our chat. I am ok to do a design socialisation for people's awareness.

**Comment by tjwatson** [comment]
From the review.  Only small suggestions.  Nothing that changes the design:

- Perhaps label the layers on slide 3
- Could mention the package version strategy (semantic versioning)
- Existing tests are used to test MicroProfile 5.0 using the Jakarta repeat rule.

**Comment by Emily-Jiang** [comment]
> From the review. Only small suggestions. Nothing that changes the design:
> 
>     * Perhaps label the layers on slide 3
> 
>     * Could mention the package version strategy (semantic versioning)
> 
>     * Existing tests are used to test MicroProfile 5.0 using the Jakarta repeat rule.

UFO updated to address the above comments.

**Comment by chirp1** [comment]
Emily provided the info to doc at https://github.com/OpenLiberty/docs/issues/4879 Approving.

**Comment by Emily-Jiang** [comment]
@samwatibm please can you approve this? This is not applicable as there is no message update.

**Comment by Emily-Jiang** [comment]
@steven1046 please can you approve this? This is not applicable as there is no UI.

**Comment by Emily-Jiang** [comment]
Swati, please can you add approval? This feature is just an aggregation of the other MP 5.0 component features. It does not add any functionalities, so there is no need for STE as usual. I went extra miles and pulled together a STE [deck](https://ibm.box.com/s/nf1q5plr0zos7uqad1f0ze3c2lt236j5) since most specs have no STE deck.

**Comment by dave-waddling** [comment]
Hi! All child MP 5.0 features have been granted FAT Focal Approval thus I'm adding it to this umbrella epic now.

**Comment by skasund** [comment]
@Emily-Jiang  I've provided the STE approval.

**Comment by tevans78** [comment]
This feature also includes Support for MP Context Propagation 1.3. Not part of MP 5.0 but depends on it.
https://github.com/OpenLiberty/open-liberty/issues/18001
