### ISSUE TITLE
featureUtility could check signatures on download

### ISSUE THREAD

**Issue by bmarwell** [OpenLiberty/open-liberty#17220]
**Is your feature request related to a problem? Please describe.**

IBM Liberty and OpenLiberty is available on Maven Central.
MC requires signed artifacts.
Once a copy of either (OL/WLP) is obtained, we can verify the archive using OpenPGP.

However, as further features are being downloaded, we lay our trust into the hands of the `featureUtility`.
As you can see from access logs of your favourite artifact mirror software, the downloads (`.esa` files) made by `featureUtility if` are not checked. Not even sure about the `.sha1` or `.sha256` files.

**Describe the solution you'd like**

`featureUtility if --verify=VERIFICATION_TYPE name [...]`

`--verify=never` (old behaviour)
`--verify=optional` (default)
`--verify=force`

`never` is the current behaviour. No download and verification attempts made.
`optional` and `force` will try to verify the signature by either BouncyCastle, gnupg or pgp binaries installed. The latter will fail if either none of these options is available. Both will fail if the signature does not match. But optional will continue if neither BC, gnupg or pgp is available.
As featureUtility should ship with BC, this should never happen and thus should be equal to force.

Please note that OL would need to ship the public sigs it is signed with.

**Describe alternatives you've considered**

None

**Additional context**

./.

**Comment by jjiwooLim** [comment]
## Description

This feature is to verify the signatures of the features downloaded from the Maven Central using the featureUtility command line tool. The new command parameter `--verify` will allow users to choose the installation behaviour upon verification failure. 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Documents

When available, add links to required feature documents. Use "N/A" to mark particular documents which are not required by the feature.

- UFO: https://ibm.box.com/s/6kme3km2f3zu7s90xd3ufebwjvsq81v8
- FTS: https://github.com/OpenLiberty/open-liberty/issues/22734
- Beta Blog: Link to Beta Blog Post GH Issue
- GA Blog: https://github.com/OpenLiberty/open-liberty/issues/26535

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Process Overview

- [Prioritization](#prioritization)
- [Design](#design)
- [Implementation](#implementation)
- [Legal and Translation](#legal-and-translation)
- [Beta](#beta)
- [GA](#ga)
  - [Focal Point Approvals](#focal-point-approvals-complete-by-feature-complete-date)
- [Other Deliverables](#other-deliverables)

### General Instructions

The process steps occur roughly in the order as presented. Process steps occasionally overlap.

Each process step has a number of tasks which must be completed or must be marked as not applicable ("N/A").

Unless otherwise indicated, the tasks are the responsibility of the Feature Owner or a Delegate of the Feature Owner.

If you need assistance, reach out to the [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect).

**Important: Labels are used to trigger particular steps and must be added as indicated.** 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Prioritization** (Complete Before Development Starts)

The ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) and area leads are responsible for prioritizing the features and determining which features are being actively worked on.

### **Prioritization**
- [x] Feature added to the "New" column of the [Open Liberty project board](https://github.com/orgs/OpenLiberty/projects/2)
  - Epics can be added to the board in one of two ways:
    - From this issue, use the "Projects" section to select the appropriate project board.
    - From the appropriate project board click "Add card" and select your Feature Epic issue
- [x] Priority assigned
  - Attend the Liberty Backlog Prioritization meeting

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Design** (Complete Before Development Starts)

Design preliminaries determine whether a formal design, which will be provided by an [Upcoming Feature Overview (UFO)](https://ibm.box.com/v/UFO-Template) document, must be created and reviewed.  A formal design is required if the feature requires any of the following: UI, Serviceability, SVT, Performance testing, or non-trivial documentation/ID.

### **Design Preliminaries**
- [ ] UI requirements identified. (Owner and [UI focal point](https://github.com/orgs/OpenLiberty/teams/ui-approvers))
- [ ] ID requirements identified. (Owner and [ID focal point](https://github.com/orgs/OpenLiberty/teams/id-approvers))
   - Refer to [Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty).
   - Feature Owner adds label `ID Required`, if non-trivial documentation needs to be created by the ID team.
   - ID adds label `ID Required - Trivial`, if no design will be performed and only trivial ID updates are needed.
- [ ] Serviceability Requirements Identified. (Owner and [Serviceability focal point](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
- [ ] SVT Requirements Identified. (Owner and [SVT focal point](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
- [ ] Performance testing requirements identified. (Owner and [Performance focal point](https://github.com/orgs/OpenLiberty/teams/performance-approvers))

### **Design**
- [x] POC Design / UFO review requested.
  - Owner adds label `Design Review Request`
- [x] POC Design / UFO review scheduled.
  - Follow the instructions in POC-Forum repo
- [x] POC Design / UFO review completed.
- [x] POC / UFO Review follow-ons completed.
- [x] Design / UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) adds label `Design Approved`
  - Add the public link to the UFO in Box to the [Documents](#documents) section.
  - The UFO must always accurately reflect the final implementation of the feature. Any changes must be first approved. Afterwards, update the UFO by creating a copy of the original approved slide(s) at the end of the deck and prepend "OLD" to the title(s). A single updated copy of the slide(s) should take the original's place, and have its title(s) prepended with "UPDATED".

### **No Design**
- [ ] No Design requested.
  - Owner adds label `No Design Approval Request`
- [ ] No Design / No UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - Approver adds label `No Design Approved`

### **FAT Documentation**
- [x] "Feature Test Summary" child task created
  - Use the [Feature Test Summary Template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=)
  - Add FTS issue link to the [Documents](#documents) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Implementation**

A feature must be [prioritized](https://github.com/orgs/OpenLiberty/projects/2) before any implementation work may begin to be delivered (inaccessible/no-ship).  However, a design focused approach should still be applied to features, and developers should think about the feature design prior to writing and delivering any code.  
Besides being prioritized, a feature must also be socialized (or No Design Approved) before any beta code may be delivered.  All new Liberty content must be inaccessible in our GA releases until it is [Feature Complete](#feature-complete) by either marking it `kind=noship` or [beta fencing](#beta-code) it.  
Code may not GA until this feature has obtained the "Design Approved" or "No Design Approved" label, along with all other tasks outlined in the [GA](#ga) section.

### **Feature Development Begins**
- [x] Add the `In Progress` label

## **Legal and Translation**

In order to avoid last minute blockers and significant disruptions to the feature, the **legal items need to be done as early in the feature process as possible**, either in design or as early into the development as possible.  Similarly, translation is to be done concurrently with development.  Both **MUST** be completed before Beta or GA is requested.

### **Legal** (Complete before Feature Complete Date)
- [ ] Changed or new open source libraries are cleared and approved, or N/A. (Legal Release Services/Cass Tucker/Release PM).
- [ ] Licenses and Certificates of Originality (COOs) are updated, or N/A

### **Translation** (Complete 1 week before Feature Complete Date)
- [ ] PII updates are merged, or N/A. Note timing with translation shipments.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Beta**

In order to facilitate early feedback from users, all new features and functionality should first be released as part of a beta release.

### **Beta Code**
- [ ] Beta fence the functionality
  - `kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`
- [ ] Beta development complete and feature ready for inclusion in a beta release
  - Add label `target:beta` and the appropriate `target:YY00X-beta` (where YY00X is the targeted beta version).
- [ ] Feature delivered into beta
  - ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager)) adds label `release:YY00X-beta` (where YY00X is the first beta version that included the functionality).

### **Beta Blog** (Complete 1.5 weeks before beta eGA)
- [ ] Beta blog issue created and populated using the [Open Liberty BETA blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the beta blog issue in the [Documents](#documents) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **GA**

A feature is ready to GA after it is Feature Complete and has obtained all necessary Focal Point Approvals. 

### **Feature Complete**
- [ ] Feature implementation and tests completed.
  - [ ] All PRs are merged.
  - [ ] All epic and child issues are closed.
  - [ ] All stop ship issues are completed.
- [ ] Legal: all necessary approvals granted.
- [ ] Translation: All messages translated or sent for translation for upcoming release 
- [x] GA development complete and feature ready for inclusion in a GA release
  - Add label `target:ga` and the appropriate `target:YY00X` (where YY00X is the targeted GA version).
  - Inclusion in a release requires the completion of all Focal Point Approvals.

### **Focal Point Approvals** (Complete by Feature Complete Date)

These occur only after GA of this feature is requested (by adding a `target:ga` label).  GA of this feature may not occur until all approvals are obtained.

### **All Features**
- [x] **APIs/Externals** Externals have been reviewed or N/A.  ([OpenLiberty/externals-approvers](https://github.com/orgs/OpenLiberty/teams/externals-approvers))
  - Approver adds label `focalApproved:externals` 
- [x] **Demo** Demo is scheduled for an upcoming EOI or N/A. ([OpenLiberty/demo-approvers](https://github.com/orgs/OpenLiberty/teams/demo-approvers))
  - Add comment `@OpenLiberty/demo-approvers Demo scheduled for EOI [Iteration Number]` to this issue.
  - Approver adds label `focalApproved:demo`.
- [x] **FAT** All Tests complete and running successfully in SOE or N/A. ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers))
  - Approver adds label `focalApproved:fat`.
- [x] **Globalization** Translation and TVT are complete or N/A. ([OpenLiberty/globalization-approvers](https://github.com/orgs/OpenLiberty/teams/globalization-approvers))
  - Approver adds label `focalApproved:globalization`.

### **Design Approved Features**
- [x] **Accessibility** Accessibility testing completed or N/A. ([OpenLiberty/accessibility-approvers](https://github.com/orgs/OpenLiberty/teams/accessibility-approvers))
  - Approver adds label `focalApproved:accessibility`.
- [x] **ID** Documentation is complete or N/A. ([OpenLiberty/id-approvers](https://github.com/orgs/OpenLiberty/teams/id-approvers))
  - Approver adds label `focalApproved:id`.
  - > **_NOTE:_**  If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [x] **Performance** Performance testing is complete or N/A. ([OpenLiberty/performance-approvers](https://github.com/orgs/OpenLiberty/teams/performance-approvers))
  - Approver adds label `focalApproved:performance`.
- [x] **Serviceability** Serviceability has been addressed or N/A. ([OpenLiberty/serviceability-approvers](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
  - Approver adds label `focalApproved:sve`.
- [x] **STE** Skills Transfer Education chart deck is complete or N/A. ([OpenLiberty/ste-approvers](https://github.com/orgs/OpenLiberty/teams/ste-approvers))
  - Approver adds label `focalApproved:ste`.
- [x] **SVT** System Verification Test is complete or N/A. ([OpenLiberty/svt-approvers](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
  - Approver adds label `focalApproved:svt`.

### **Remove Beta Fencing** (Complete by Feature Complete Date)
- [ ] Beta guards are removed, or N/A
  - Only after all necessary Focal Point Approvals have been granted.

### **GA Blog** (Complete by Feature Complete Date)
- [x] GA Blog issue created and populated using the [Open Liberty GA release blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the GA Blog issue in the [Documents](#documents) section.

### **Post GA**
- [ ] Replace `target:YY00X` label with the appropriate `release:YY00X`. ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager))

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Other Deliverables**

- [ ] **Standalone Feature Blog Post** A blog post specifically about your feature or N/A.  ([OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect))
  - This should be strongly considered for larger or more prominent features.
  - Follow [instructions](https://github.com/OpenLiberty/blogs/tree/draft#writing-and-publishing-blog-posts-on-the-openlibertyio-blog) in the blogs repo.
- [ ] **OL Guides** OL Guides assessment is complete or N/A. ([OpenLiberty/guide-assessment](https://github.com/orgs/OpenLiberty/teams/guide-assessment/members))
- [ ] **Dev Experience** Developer Experience & Tools work is complete or N/A. ([OpenLiberty/dev-experience-assessment](https://github.com/orgs/OpenLiberty/teams/dev-experience-assessment/members))
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by follis** [comment]
Review comments from POC review Sep 23, 2022

There was some concern about trying to pull in multiple user features that had different keys that might require different featureUtility.properties files.  We seemed to have just decided that probably wasn’t worth bothering with.
 
There was a question about whether the force/skip/etc option could be specified in the .properties file. 
 
A lot of discussion about what the default behavior should be.  Secure by default is nice, but is it worth possibly breaking people that are working fine now?  Should there be a different default for Liberty features vs user features?  Should we ship our public key as part of the product for people who can’t get to it in their non-connected environment?  Is forcing the check worth it (is this a big enough problem to be secure by default about)?
 
Keyword should be ‘enforce’ instead of ‘force’ which suggests skipping a failed check.  Also discussion about whether ‘optional’ should be ‘warn’.
 
Chart 18 – say whether maven/gradle/docker buildpak are affected or not
 
Chart 22 – Verify the license is ok (probably is because we’re using it already, but maybe only in test which we’d care about differently than if we ship it).  Current use and this use should be the same version, either the one we have already or a new one, but keep them the same
 
Chart 26 – Verifying the signature adds CPU cost which should be noted.  Concern again about making enforcement the default and the overhead.  Do we need to measure it help make the decision?
 
Chart 28 – Remove the bit about updating the application since this is featureUtility and not running in the server.
 
Chart 29 – If failures happen in docker build how would you find the errors?
 
Chart 31 – Update migration impact based on decision about default
 
No re-review required, but open design issues as necessary.

**Comment by bmarwell** [comment]
Hey, some more thoughts to make it easier. There's already the https://github.com/s4u/pgpverify-maven-plugin which can do what I would like to see.

That means, if I created a pom project with the esa files, executed dependency:go-offline and ran the plugin, that should do it.
This could also be adapted (and automated) into official docker images (if you are interested).

So, maybe this feature request could be solved by using documentation only. Will try this and get back to you whether it works or not and instructions on how to use it.

**Comment by jjiwooLim** [comment]
Follow-ons: 
Updated UFO powerpoint

> There was a question about whether the force/skip/etc option could be specified in the .properties file.

Added chart 19 -  users can specify the option using the environment variable and featureUtility.properties file. 

> A lot of discussion about what the default behavior should be. Secure by default is nice, but is it worth possibly breaking people that are working fine now? Should there be a different default for Liberty features vs user features? Should we ship our public key as part of the product for people who can’t get to it in their non-connected environment? Is forcing the check worth it (is this a big enough problem to be secure by default about)?

Default behaviour - secure by default, but only for Liberty features. Added a new option to verify both Liberty feature and user feature. 

Will ship the key as part of the product, but will check the keyserver when the key is revoked or expired (for connected environment). 


> Keyword should be ‘enforce’ instead of ‘force’ which suggests skipping a failed check. Also discussion about whether ‘optional’ should be ‘warn’.
> 
> Chart 18 – say whether maven/gradle/docker buildpak are affected or not

Updated Chart 19 


> Chart 22 – Verify the license is ok (probably is because we’re using it already, but maybe only in test which we’d care about differently than if we ship it). Current use and this use should be the same version, either the one we have already or a new one, but keep them the same

Updated Chart 23

> Chart 26 – Verifying the signature adds CPU cost which should be noted. Concern again about making enforcement the default and the overhead. Do we need to measure it help make the decision?

Updated Chart 27

> Chart 28 – Remove the bit about updating the application since this is featureUtility and not running in the server.

Updated Chart 29

> Chart 29 – If failures happen in docker build how would you find the errors?

Updated Chart 30

> Chart 31 – Update migration impact based on decision about default

Updated Chart 32

**Comment by NottyCode** [comment]
@jjiwooLim Questions on the design:

1. I was confused by slide 9 because I read it as saying that verify=skip would be the default, but I realized on 3rd reading after the comment above this isn't what it is saying. Can you pull out in slide 9 explicitly that this is a behaviour change?
3. Slide 9 says that a valid value for verify is warn, but slide 18 and 27 do not show it. It does show an optional value here.
4. When you say the maven and gradle tools are not affected does that mean that they will not verify the signatures? If so it seems that we either need to do that work, or we need a work item to update them to verify.
5. Do we use signatures from the local .m2 repository or do we always download them from the server?
6. If the certificate doesn't validate what error code will be returned by the process?
7. I don't think the response to the docker failure addresses the question. I know some errors are hard to diagnose via the docker containers because the output from feature.sh or configure.sh doesn't get sent to the docker build output. I think a signature failure is something that needs to be very obvious on how to resolve (or to realize you cannot resolve). Saying a runtime error will be thrown doesn't really address the feedback.

**Comment by jjiwooLim** [comment]
@NottyCode 
Updated UFO slides.

3. When you say the maven and gradle tools are not affected does that mean that they will not verify the signatures? If so it seems that we either need to do that work, or we need a work item to update them to verify.
- Created seperate work items for plugins. It would be easier to test and implement after the runtime code is released. https://github.com/OpenLiberty/ci.maven/issues/1605 and https://github.com/OpenLiberty/ci.gradle/issues/785
4. Do we use signatures from the local .m2 repository or do we always download them from the server?
 - If the signature file (.asc) and feature (.esa) file are already in local .m2 repo, then we don't download from the server. 
5. If the certificate doesn't validate what error code will be returned by the process?
- New error code 37 - signature verification failed. 
8. I don't think the response to the docker failure addresses the question. I know some errors are hard to diagnose via the docker containers because the output from feature.sh or configure.sh doesn't get sent to the docker build output. I think a signature failure is something that needs to be very obvious on how to resolve (or to realize you cannot resolve). Saying a runtime error will be thrown doesn't really address the feedback.
- Throw exit code 37 - signature verification failed. Add VERBOSE=true to see the detailed error message (stdout) from features.sh.

**Without** verbose:
```
…
 => ERROR [7/7] RUN features.sh                                            10.9s
------
 > [7/7] RUN features.sh:
------
executor failed running [/bin/sh -c features.sh]: exit code: 37
```
**With** verbose (case where public key could not be downloaded)
```
…
=> ERROR [7/7] RUN features.sh                                            12.0s
------                                                            
 > [7/7] RUN features.sh:
…
…
#11 10.36 Starting installation ...
#11 10.36 <============---------> 60.00%
#11 11.03 Finished downloading the public key https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x46102B8E to /opt/ol/wlp/signature3869020805337169056.asc
#11 11.05 <============---------> 60.00%
#11 11.06 public key could not be downloaded : java.io.FileNotFoundException: /opt/ol/temp/myPublicKey.asc (No such file or directory)
```

**Comment by jjiwooLim** [comment]
@OpenLiberty/demo-approvers Demo scheduled for EOI 23.10

**Comment by chirp1** [comment]
The doc issue for the feature is https://github.com/OpenLiberty/docs/issues/6649 . Developer has technical reviewed/approved the updates. Approving this feature.

**Comment by jjiwooLim** [comment]
Accidentally removed `focalApproved:performance` label last week. Adding back in..

**Comment by jjiwooLim** [comment]
@OpenLiberty/ste-approvers slides uploaded to STE-archive

**Comment by malincoln** [comment]
> @OpenLiberty/ste-approvers slides uploaded to STE-archive

I followed up with @tngiang73 and they will review.

**Comment by tngiang73** [comment]
L2 is good with STE slides. STE approved!

**Comment by jjiwooLim** [comment]
@OpenLiberty/serviceability-approvers 

UFO: Does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR? Have these issues been addressed in the implementation?

> Yes

Test and Demo: As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team). a) What problem paths were tested and demonstrated? b) Who did you demo to? c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?

> a) Scenario where Liberty public key is revoked or expired. Network failure downloading user's public key. Typo in user inputs (invalid verify option, invalid url of the public key server, invalid key ID)
b) EOI meeting/ Install team
c) Yes

SVT: SVT team is often the first team to try new features and often encounters problems setting up and using them. Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered. a) Who conducted SVT tests for this feature? b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?
> SVT: Brian Hanczaryk
SVT found no concerns regarding serviceability

Service: Which L2 / L3 queues will handle PMRs for this feature? Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it. Ask Don Bourne if you need links or more info.
> WAS: L3 Liberty Install

Metrics: Does this feature add any new metrics or emit any new JSON events? If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?
> No new metrics / No JSON events

**Comment by chirp1** [comment]
Doc update at the following URL technically approved: https://github.com/OpenLiberty/docs/issues/6649 . Approving.

**Comment by jjiwooLim** [comment]
Feature complete, closing the issue.

**Comment by bmarwell** [comment]
Thanks!
