### ISSUE TITLE
Open Liberty automated MVT

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#17818]
## Description of the high level feature, including any external spec links:  

The Open Liberty build creates a number of images;

- kernel - kernel only
- runtime - all GA features
- webProfile8 - JEE8 Web Profile GA features
- jakartaee8 - JEE8 Full Profile GA features
- microProfile4 - MicroProfile 4 GA features
- microProfile5 - MicroProfile 5 GA features
- all beta - all GA + beta features
- jakartaee9 - JEE9 beta features
- microProfile6 or 7 -MicroProfile 6 or 7 GA features (added 19-Jan-2023)
- jakartaee10 - JEE10 beta features (added 19-Jan-2023)
- webProfile10 JEE10 Web Profile GA features (added 19-Jan-2023)

We need some automated tests to
- Validate that the image contains the correct features (nothing missing, nothing extra)
- Check that a server starts using the default server.xml for each image.

Note that it may be appropriate to migrate the WebSphere Liberty MVT mechanism to Open Liberty.

Implementation plan and test prioritization:

(1) Initial port; extract/create/run (#20215)
-- open-liberty/dev/build.image/build/libs/distributions/.zip
(2) verify profile features (#20216)
-- open-liberty/dev/build.image/profiles/
(3) feature install from kernel (#20217)
-- TBD
(4) Explicit script verification (#20661)
-- requested per Adam Yoho.
(5) MVT: File permission verification #29865

<br/><br/><br/>  
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:
- FTS:
- Beta Blog Post (if applicable):
- Blog Post: 
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [ ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [ ] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by malincoln** [comment]
paused for now, removing in progress.  @tbitonti will add back when work resumes.

**Comment by tevans78** [comment]
Note that I will shortly be creating new OL zips for `microProfile6`, `webProfile10` and `jakartaee10`.

**Comment by malincoln** [comment]
Per @hlhoots waiting on feedback from CI/CD team to progress.

**Comment by tevans78** [comment]
@hlhoots @tbitonti @malincoln Any updates on this feature?

**Comment by hlhoots** [comment]
@tevans78 I think the next step is a meeting with @wraschke to move forward with the creating of a build definition for this MVT code to run.  Will setup a meeting.

**Comment by hlhoots** [comment]
I think it should be paused for the time being.  Its been sitting for over a year and a half.  We need to get it prioritized on the build/infra team to create a build definition for it to move it forward.

**Comment by malincoln** [comment]
Per Tom, Yasmin is currently going through the pain of manually testing the zips to check that MP 7.1 has been added correctly. I have asked her to keep track of the time she spends on it.

**Comment by malincoln** [comment]
Per discussion with Alasdair, We should follow-up with CC/CD team as this should be tracked on their board.

**Comment by cbridgha** [comment]
So the Epic on the CC/CD side is here:  https://github.ibm.com/WAS-CD-Area/WAS-CD-Area/issues/488

**Comment by malincoln** [comment]
Will track via CC/CD issue.
