### ISSUE TITLE
Ensure UserInfo claims validation is spec-compliant

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#17869]
https://github.com/OpenLiberty/open-liberty/issues/17072 mentions two places where we obtain claims from an OP's UserInfo endpoint. Both of those instances need to be re-evaluated to ensure they're compliant with https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse.

- [ ] The UserInfo Claims MUST be returned as the members of a JSON object unless a signed or encrypted response was requested during Client Registration.
- [ ] The `sub` (subject) Claim MUST always be returned in the UserInfo Response.
- [ ] The `sub` Claim in the UserInfo Response MUST be verified to exactly match the `sub` Claim in the ID Token; if they do not match, the UserInfo Response values MUST NOT be used.
- [ ] The UserInfo Endpoint MUST return a content-type header to indicate which format is being returned.
- [ ] The content-type of the HTTP response MUST be `application/json` if the response body is a text JSON object; the response body SHOULD be encoded using UTF-8.
- [ ] If the UserInfo Response is signed and/or encrypted, then the Claims are returned in a JWT and the content-type MUST be `application/jwt`.
- [ ] The response MAY be encrypted without also being signed.
- [ ] If both signing and encryption are requested, the response MUST be signed then encrypted, with the result being a Nested JWT, as defined in [JWT](https://tools.ietf.org/html/rfc7519).
- [ ] If signed, the UserInfo Response SHOULD contain the Claims `iss` (issuer) and `aud` (audience) as members. The `iss` value SHOULD be the OP's Issuer Identifier URL. The `aud` value SHOULD be or include the RP's Client ID value.
