### ISSUE TITLE
When transaction recovery log fails, reset the recovery service internally rather than bringing down the server

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#17910]
## Description of the high level feature, including any external spec links:  
Support reset of the recovery service rather than brining down the server.  This would avoid outages due to all servers restarting during DB failover.
<br/>
When Liberty detects a failure in its recovery logs, it shuts down completely. This means applications have to be reloaded when the server restarts. This can take a considerable amount of time for some applications (e.g. BAW). 
<br/>
Under certain circumstances, such as when the recovery log failure is caused by transient database connection errors, the recovery service could be internally reset avoiding the need to shutdown the server and reload the apps.
<br/><br/>  
## Current Liberty Design
-> If a tranlog access receives a SQLTransientException, then we will retry the call a configured number of times with a configured time interval. If the call still hasn't succeeded, we FFDC & bring down the server. Each retry acquires a new Connection.

-> If a tranlog access receives a non-transient SQLException, then we FFDC and immediately bring down the server. 

There are 3 scenarios in which these exceptions can occur: 

  During 2PC processing: An RMLT may comprise a set of inserts, updates and deletes. When a SQLTransientException was thrown but the commit operation was completed by the RDBMS, then, after acquiring a new Connection and taking the HADB lock...
 - retrying inserts would result in a set of duplicate rows in the db table
 - retrying the updates would be a no-op, ie setting columns in a row to identical values
 - retrying the deletes would also be a no-op, the second attempt would simply delete no rows

  Subsequent recovery takes care of the duplicate rows.

  Opening the logs: An RMLT comprises an update against the HADB lock row and a query to retrieve the set of log records from the database table.
 - one set of runtime objects results irrespective of how many times the query is tried

  Peer recovery processing: An RMLT comprises an update against the HADB lock row.
 - retrying leads, harmlessly, to a more recent timestamp in the row.

## Proposal
Apply retry logic to all SQLExceptions, not just instances of SQLTransientException.
Expose & extend configuration of retry intervals and limits.
Internally we will provide a means to specify a list of SQL error codes for which the old behaviour will be preserved.

## Defaults and Configuration
Introduce new transaction service config attributes (with defaults as currently implemented for transients):

**enableLogRetries (false)**
 - by default the new functionality is disabled and an operation on the transaction logs which throws a non-transient SQLException will not be retried and the server will be halted 
 - when true, an operations on the transaction logs which throws a non-transient SQLException will be retried.

**logRetryInterval (10s)**
 - the number of seconds between repeated attempts to retry an operation on the transaction logs which has thrown a SQLException.

**logRetryLimit (180)**
 - the number of times an operation on the transaction logs which has thrown a SQLException will be retried. If this limit is reached, the server will be halted.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO: N/A
- FTS: https://github.com/OpenLiberty/open-liberty/issues/19225
- Beta Blog Post (if applicable):
- Blog Post: https://github.com/OpenLiberty/open-liberty/issues/19978
- Aha: https://bigblue.aha.io/ideas/ideas/LIBERTY-I-6
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [x] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [x] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [x] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [x] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [x] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by jonhawkes** [comment]
## Current Liberty Design
-> If a tranlog access receives a SQLTransientException, then we will retry the call a configured number of times with a configured time interval. If the call still hasn't succeeded, we FFDC & bring down the server. Each retry acquires a new Connection.

-> If a tranlog access receives a non-transient SQLException, then we FFDC and immediately bring down the server. 

There are 3 scenarios in which these exceptions can occur: 

  During 2PC processing: An RMLT may comprise a set of inserts, updates and deletes. When a SQLTransientException was thrown but the commit operation was completed by the RDBMS, then, after acquiring a new Connection and taking the HADB lock...
    - retrying inserts would result in a set of duplicate rows in the db table
    - retrying the updates would be a no-op, ie setting columns in a row to identical values
    - retrying the deletes would also be a no-op, the second attempt would simply delete no rows

    Subsequent recovery takes care of the duplicate rows.

  Opening the logs: An RMLT comprises an update against the HADB lock row and a query to retrieve the set of log records from the database table.
    - one set of runtime objects results irrespective of how many times the query is tried

  Peer recovery processing: An RMLT comprises an update against the HADB lock row.
    - retrying leads, harmlessly, to a more recent timestamp in the row.

## Proposal
Apply retry logic to all SQLExceptions, not just instances of SQLTransientException.
Expose & extend configuration of retry intervals and limits.
Internally we will provide a means to specify a list of SQL error codes for which the old behaviour will be preserved.

## Defaults and Configuration
Introduce new transaction service config attributes (with defaults as currently implemented for transients):

enableLogRetries (false)
logRetryInterval (10s)
logRetryLimit (180)

**Comment by NottyCode** [comment]
@jonhawkes Sorry for the delay, but can you update the design section to describe what the 3 new configuration settings will do and how the interrelate?
