### ISSUE TITLE
netty - z/OS WOLA support

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#18089]
Implement the functionality provided by `zosLocalAdapters` - WebSphere Optimized Local Adapters - to work with netty

**Comment by hutchig** [comment]
For WOLA we are in closed Liberty.
Further detailed discussion at: https://github.ibm.com/websphere/WS-CD-Open/issues/25549

**Comment by hutchig** [comment]
There is a great page on WOLA here: https://www.ibm.com/support/pages/websphere-zos-optimized-local-adapters

**Comment by hutchig** [comment]
Tracking complete CF import removal (or class replacement) in [PR](https://github.ibm.com/websphere/WS-CD-Open/pull/27131)

14/61 complete

### websphere channelfw package imports removed (or minimal interface implementer subclass class constrained to cfw package)

**Local Channel bundle**

LocalCommChannel.java     
> - [x] com.ibm.websphere.channelfw.ChannelData;

LocalCommChannelFactory.java
> - [x]    com.ibm.websphere.channelfw.ChannelData;
> - [x]    com.ibm.websphere.channelfw.ChannelFactoryData;
> - [ ]   ~~ com.ibm.websphere.channelfw.OutboundChannelDefinition ~~ <- Mistakenly listed

LocalCommChannelFactoryProvider.java
> - [x]    com.ibm.websphere.channelfw.osgi.ChannelFactoryProvider;


**WOLA bundle**

WOLAChainBuilder.java
> - [x]    com.ibm.websphere.channelfw.ChainData;
> - [x]    com.ibm.websphere.channelfw.FlowType;
> - [x]    com.ibm.websphere.channelfw.osgi.CHFWBundle;

WOLAChannel.java
> - [x]    com.ibm.websphere.channelfw.ChannelData;

WOLAChannelFactory.java
> - [x]    com.ibm.websphere.channelfw.ChannelData;
> - [x]    com.ibm.websphere.channelfw.ChannelFactoryData;
> - [x]    com.ibm.websphere.channelfw.OutboundChannelDefinition;

WOLAChannelFactoryProvider.java
> - [x]    com.ibm.websphere.channelfw.osgi.ChannelFactoryProvider;

WOLAEndpoint.java
> - [x]    com.ibm.websphere.channelfw.osgi.CHFWBundle;
> - [x]    com.ibm.websphere.channelfw.osgi.ChannelFactoryProvider;

### wsspi channelfw package imports

**Local Channel bundle**
LocalCommChannel.java
> - [x] com.ibm.wsspi.channelfw.ChannelFrameworkFactory;
> - [x] com.ibm.wsspi.channelfw.ConnectionLink;
> - [x] com.ibm.wsspi.channelfw.DiscriminationProcess;
> - [x] com.ibm.wsspi.channelfw.Discriminator;
> - [x] com.ibm.wsspi.channelfw.InboundChannel;
> - [x] com.ibm.wsspi.channelfw.VirtualConnection;
> - [x] com.ibm.wsspi.channelfw.VirtualConnectionFactory;
> - [x] com.ibm.wsspi.channelfw.exception.ChainException;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelException;

LocalCommChannelFactory.java
> - [x] com.ibm.wsspi.channelfw.Channel;
> - [x] com.ibm.wsspi.channelfw.ChannelFactory;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelException;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelFactoryException;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelFactoryPropertyIgnoredException;

LocalCommChannelFactoryProvider.java
> - [x] com.ibm.wsspi.channelfw.ChannelFactory;

LocalCommClientConnHandleMapImpl.java
> - [x] com.ibm.wsspi.channelfw.ConnectionReadyCallback;

LocalCommConnLink.java
> - [x] com.ibm.wsspi.channelfw.ConnectionReadyCallback;
> - [x] com.ibm.wsspi.channelfw.DiscriminationProcess;
> - [x] com.ibm.wsspi.channelfw.VirtualConnection;
> - [x] com.ibm.wsspi.channelfw.base.InboundProtocolLink;

LocalChannelProvider.java
> - [x] com.ibm.wsspi.channelfw.exception.ChannelException;

LocalCommClientConnHandleMap.java [Moved as returns cf type]
> - [NA] com.ibm.wsspi.channelfw.ConnectionReadyCallback;

**WOLA bundle**

WOLAChainBuilder.java
> - [x] com.ibm.wsspi.channelfw.ChainEventListener;
> - [x] com.ibm.wsspi.channelfw.ChannelFramework;
> - [x] com.ibm.wsspi.channelfw.exception.ChainException;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelException;

WOLAChannel.java
> - [x] com.ibm.wsspi.channelfw.ChannelFramework;
> - [x] com.ibm.wsspi.channelfw.ConnectionLink;
> - [x] com.ibm.wsspi.channelfw.DiscriminationProcess;
> - [x] com.ibm.wsspi.channelfw.Discriminator;
> - [x] com.ibm.wsspi.channelfw.InboundChannel;
> - [x] com.ibm.wsspi.channelfw.VirtualConnection;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelException;

WOLAChannelFactory.java
> - [x] com.ibm.wsspi.channelfw.Channel;
> - [x] com.ibm.wsspi.channelfw.ChannelFactory;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelException;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelFactoryException;
> - [x] com.ibm.wsspi.channelfw.exception.ChannelFactoryPropertyIgnoredException;

WOLAChannelFactoryProvider.java
> - [x] com.ibm.wsspi.channelfw.ChannelFactory;  ~~ <- moved wholesale

WolaConnLink.java   ~~ <- super class already occupied, moved to cfw
> - [x] com.ibm.wsspi.channelfw.ConnectionLink;
> - [x] com.ibm.wsspi.channelfw.VirtualConnection;
> - [x] com.ibm.wsspi.channelfw.base.InboundProtocolLink;

WOLADiscriminator.java
> - [x] com.ibm.wsspi.channelfw.Channel;
> - [x] com.ibm.wsspi.channelfw.Discriminator;
> - [x] com.ibm.wsspi.channelfw.VirtualConnection;

WOLAEndpoint.java
> - [x] com.ibm.wsspi.channelfw.ChannelFactory;

**Comment by hutchig** [comment]
WOLA Netty Implementation Chunks

[Initial number is strawman sizing]
#### ChannelLocal

Package com.ibm.ws.zos.channel.local is just utility/data classes and will be covered by main tasks below:

(The first work item here was ticked in error (wrongly using the removal on non wsspi class references as the criteria rather than implementation complete of netty equivalent code).

- [ ] 3 - LocalCommChannel(Handler) (start&stop events, get upstream and downstream links, no real equivalent of discrimination is needed)
- [ ] 1 - LocalCommChannel(Handler) creation pattern (cached-factory (and factory provider equivalent) and lifecycle)
- [ ] 1 - LocalChannel((Virtual)Connection)Factory (nativeWorkRequest handling->ready)
- [ ] 2 - Service Context Impl (non CF interfaces)
- [ ] 1 - ServiceContextHandling (see LocalCommServiceContextImpl uses)
- [ ] 1 - OSGi service @Component tie in to core/executor when feature active
- [ ] 1 - Application Callback handling callback registrations
- [ ] 1 - Application Callbacks calling, and testing of outbound over JCA
- [ ] 2 - Upside connection link (to WOLA) ready-ready, disconnect, close, close-native
- [ ] 1 - LocalCommConnLink - native request handler
- [ ] 1 - LocalCommConnLink - connectAccepted
- [ ] 3 - Unit Test into build
- [ ] 1 - (User)Config digestion metatype + unit test

19 working days

#### ChannelWola

Again, the core com.ibm.ws.zos.channel.wola package has mostly data facades and has very little use of CF calls. The bridges to IMS Interrupts/OTMA and JCA should be unchanged. 
- [ ] 1 ChainBuilder
- [ ] 1 WOLAHandler (Channel)
- [ ] 1 WOLAHandler creation pattern (cached-factory and lifecycle)
- [ ] 2 WOLA Inbound protocol encoder (ConnLink ready-read, outboundRequestService, deviceLink)
- [ ] 2 WolaJCABridge (& jcaInvoke)
- [ ] 2 OSGi DS activation
- [ ] 1 otmaInvoke (covers InterruptObjectBridge for OTMA C/I or WOLA registration - there should be few changes needed)
- [ ] 3 Unit Test into build
- [ ] 2 ContextHandling
- [ ] 2 Config digestion metatype + unit test

17 working days

#### Bootstrap

- [ ] 3 'Other' Channel Framework function replacement for WOLA
- [ ] 3 Bootstrap/startup
- [ ] 3 Executor impl/check
- [ ] 1 Beta switching
- [ ] 1 RAAS - logging check
- [ ] 1  RAAS - dump contribution (chase all new netty objects to be dumped correctly)
- [ ] 1 bnd file check

13 working days

#### Functional Test 

- [ ] 1 com.ibm.ws.jbatch.wola_zfat (0/80 passing),
-- [ ] MQ Tests passing
-- [ ] Native Batch Job Client tests passing 
-- [ ] jdbc DBServlet test passing
- [ ] com.ibm.ws.zos.channel.wola_zfat (0/2 passing) 
-- [ ] Chain Activation passing
-- [ ] EJB Tests passing 
- [ ] com.ibm.ws.zos.connect.wola_zfat (0/22 passing) 
-- [ ] CICS test passing
-- [ ] Batch Service tests passing
- [ ] com.ibm.ws.zos.ola.ims.svt_zfat (0/9 passing)
-- [ ] IMS inbound passing
-- [ ] IMS Outbound passing 
- [ ] 3 com.ibm.ws.zos.ola_zfat (0/416 passing)
-- [ ] CICSLink
-- [ ] Angel tests passing
-- [ ] OTMA tests passing
- [ ] ALCS test passing (System Test??)


5 working days

Total sizing of remaining work = 55 working days = 11 weeks.

**Comment by hutchig** [comment]
Review of SIP, JMS and HTTP2 Netty based implementation PRs notes that wsspi
has been retained as-is - which is the approach in stage 1. So we will retain the
use of the com.ibm.ws.channelfw/src/com/ibm/wsspi/channelfw package without
changing the method signatures. This means that classes that are used in these
method signatures will also be retained: these are: 
{ CFEndPoint, CFEndPointCriteria, ChainData, ChainGroupData, ChannelData, ChannelFactoryData, FlowType, OutboundChannelDataDefinition, RegionType, osgi.ChannelFactoryProvider, internal.ChannelFrameworkConstants }

This will be discussed in https://github.com/OpenLiberty/open-liberty/issues/25140

**Comment by hutchig** [comment]
Projects cleared of non-wsspi+signature+utilised classes:

com.ibm.ws.zos.channel.local 

- [x] com.ibm.ws.zos.channel.local 
- [x] com.ibm.ws.zos.channel.wola
- [x] com.ibm.ws.zos.channel.wola.internal (All classes are wsspi or on the #25140 list except):
com.ibm.websphere.channelfw.osgi.CHFWBundle in WOLAEndPoint.java
