### ISSUE TITLE
Add remote port option to the HTTP access log formats

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/open-liberty#18132]
## Description of the high level feature, including any external spec links:  

When using the [HTTP access log](https://openliberty.io/docs/latest/access-logging.html#_http_access_log_format) instead of diagnostic trace to investigate response time issues with minimal overhead and investigating network or latency issues, it would be useful to print the remote port of the request to correlate to network trace. A TCP socket is uniquely identified by the tuple (local IP, local port, remote IP, remote port). In the case of Liberty as an HTTP server, the client uses a local ephemeral port and this is the part that would be useful to have to correlate to network trace.

The proposed solution is an additional `%{remote}p` option (which matches [httpd syntax](https://httpd.apache.org/docs/trunk/mod/mod_log_config.html#formats)) that prints the remote port of the request. For example, given the following:

```
<accessLogging filepath="${server.output.dir}/logs/http_access.log" maxFileSize="100" maxFiles="4" logFormat="%h %u %t &quot;%r&quot; %s %b %D %{R}W %p %{remote}p" />
```

The following is example output with `9080` being the Liberty port and `62719` being the ephemeral client port:

```
127.0.0.1 - [10/Aug/2021:12:09:53 -0700] "GET / HTTP/1.1" 200 21983 84420 76654 9080 62719
```

**Alternatives considered**
Time-based correlation is the main alternative but breaks down under high volume and the fact that [non-JSON based timestamps only have second-level resolution](https://github.com/OpenLiberty/open-liberty/issues/18112). Even with non-TLS traffic, some applications and products use the same URI to handle multiple different types of requests which makes disambiguating them difficult. The other alternative is diagnostic trace which can be excessive under high load.

**Additional context**
* There is already the [local port format option `%p`](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogLocalPort.java) for the server's port although it's undocumented.
* The access log is disabled by default and it would be a conscious decision to add the remote port in the custom [`accessLogFormat`](https://openliberty.io/docs/latest/access-logging.html#_http_access_log_format).
* For reference, [httpd's LogFormat](https://httpd.apache.org/docs/trunk/mod/mod_log_config.html#formats) supports this with `%{remote}p`:
   > %{format}p: The canonical port of the server serving the request, or the server's actual port, or the client's actual port. Valid formats are canonical, local, or remote.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):

- Feature Test Summary: https://github.com/OpenLiberty/open-liberty/issues/18641

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Design**
Before Development Starts or 8 weeks before Onboarding
- [X] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [X] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [X] Complete any follow-ons from the POC Review.
- [X] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [X] No Design / No UFO Approval ([Arthur De Magalhaes](https://github.com/arthurdm) - cloud / [Alasdair Nottingham](https://github.com/NottyCode) - server) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [x] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [x] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [x] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [x] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [x] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [x] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [x] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [x] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by kgibm** [comment]
Created proof-of-concept: https://github.com/OpenLiberty/open-liberty/pull/18133

**Comment by kgibm** [comment]
Discussed with Brian H and there is no need for SVT.

**Comment by kgibm** [comment]
Added PR to remove beta fence: https://github.com/OpenLiberty/open-liberty/pull/18969

**Comment by kgibm** [comment]
Chatted with YK and updates aren't needed on OL Guides and WDT.
Draft blog post is here: https://github.com/OpenLiberty/open-liberty/issues/18967
Everything seems to be done so closing this epic.
