### ISSUE TITLE
 Create schemaGen wrapper script for ws-schemagen.jar

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#18191]
## Description of the high level feature, including any external spec links:  

Liberty has many executable tool JARs that also have wrapped scripts handling command line help, error codes, env vars etc...

ws-schemagen.jar also needs a script that helps pass supported / documented parameters.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:  N/A
- FTS:  https://github.com/OpenLiberty/open-liberty/issues/19967
- Beta Blog Post (if applicable): N/A
- Blog Post:  https://github.com/OpenLiberty/open-liberty/issues/20929
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ N/A] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ N/A] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ N/A] Complete any follow-ons from the POC Review.
- [ N/A] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ X ] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [ x] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ X ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [x ] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by cbridgha** [comment]
Existing doc issue for documenting ws-schemagen.jar 

https://github.ibm.com/websphere/liberty-docs/issues/2423

**Comment by dmuelle** [comment]
Open Liberty docs issue to document updated schemaGen command (when its ready)

https://github.com/OpenLiberty/docs/issues/4550

**Comment by jimblye** [comment]
### There are 3 ws-schemagen.jar files in the Liberty build image:
****
```
-rw-r--r--  1 jimblye  staff  2510 Nov 10 08:59 ../../../build.image/wlp/bin/tools/ws-schemagen.jar
-rw-r--r--  1 jimblye  staff  2445 Nov 10 09:00 ../../../build.image/wlp/bin/jaxb/tools/ws-schemagen.jar
-rw-r--r--  1 jimblye  staff  2626 Nov 10 09:18 ../../../build.image/wlp/bin/xmlBinding/tools/ws-schemagen.jar
```

The ones in jaxb/tools and xmlBinding/tools already have scripts.   So I believe the **ws-schemagen.jar** we are talking about is in the **bin/tools** directory

### This is the project:

- **com.ibm.ws.config.schemagen.schemagen**

           bnd.bnd has
                  publish.tool.jar=ws-schemagen.jar
                 
                 The following will need to be added to the bnd.bnd:
                 publish.tool.script=schemaGen 
                 

The existing scripts that are generated under the build image wlp/bin directory are built from template scripts under cnf.
cnf/resource/bin/tool
cnf/resource/bin/tool.bat

The **tool** and **tool.bat** files have replacement variables:

- @TOOL_SCRIPT_RELATIVE@ : this is an empty string for scripts in the wlp/bin.  If it's in an immediate subdirectory such as wlp/bin/jaxb, then the value is ".."
- @TOOL_JAR@ :   we want this to be ws-schemagen.jar
- @TOOL_SCRIPT@ :    we want this to be schemaGen 

The above variables in tool & tool.bat are replaced with values of the following variables in bnd.bnd:
```
publish.tool.jar=ws-schemagen.jar
publish.tool.script=schemaGen
```
 
 ### Results of the above bnd.bnd change
 The above resulted in a build that created schemaGen( and schemaGen.bat) scripts in wlp/bin, 
 
 Executing the script resulted in:
 
```
CWWKG0034E: Target file must be specified
```

### Output of ./schemaGen --help

```
Usage: java [JVM options] -jar ws-schemagen.jar [options] outputFile  

Options:

--encoding
The character encoding to use for the output

--ignorePidsFile
A file name containing a list of pids to ignore

--locale
The locale to use for the output
```

### Update output of --help option

The help output above should be updated to include options schemaVersion=1.1 and outputVersion=2.0.   Also the usage message should be updated to reference the script rather than the "java -jar" command.
This is done in ConfigOptions.nlsprops
../../../build.pii.package/nlssrc/com.ibm.ws.config/com/ibm/ws/config/internal/resources/ConfigOptions.nlsprops
../../../com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigOptions.nlsprops
```
Usage: schemaGen [ options ] outputFile
    . . .

```
 
### schemaGen script
The schemaGen script runs the tools/ws-schemagen.jar
The ws-schemagen.jar does NOT contain any source.  However, the META-INF/MANIFEST.MF has 
Class-Path: ../../lib/com.ibm.ws.kernel.cmdline_1.0.60.jar


### Open Liberty online Documentation    
The following page needs to be updated:
https://www.ibm.com/docs/en/was-liberty/core?topic=line-generating-liberty-configuration-schema-from-command

**Comment by jimblye** [comment]
The documentation for this is here:  https://www.ibm.com/docs/en/was-liberty/core?topic=line-generating-liberty-configuration-schema-from-command

It just needs moved(copied?) to open liberty.

The following changes need to be made so that we are documenting the command script rather than the JAR:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/16544901/150196644-9f44e0b8-b990-41d3-9fe7-d714a4acdc7c.png">

**Comment by jimblye** [comment]
For this item, there are 3 parts:

- update **bnd.bnd**:   add a line to cause the new script to be automatically generated by the build
- update **--help output**:   Existing help directs you to use the java -jar ... command.  Now it should direct you to use the script.
- update **--help output**:   Not related to the issue, but the --help output is missing a couple of options.

**Comment by chirp1** [comment]
I discussed the docs updates needed with Jim Blye and David Mueller. Jim added the information to document to https://github.com/OpenLiberty/docs/issues/4550 I approved this epic.

**Comment by hlhoots** [comment]
#20697 should push back in the reverted code for publishing via .mf file as well as the rc=0 scenario.
