### ISSUE TITLE
Improve JDBC Driver Logging

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#18370]
## Description of the high level feature, including any external spec links:  
The description needs to be detailed enough such that it can be [prioritized on the backlog](https://github.com/orgs/OpenLiberty/projects/2) and implemented by the development team.

**User Story:** 
As a user of Open Liberty who is experiencing an Oracle issue, I need Open Liberty to separate its own tracing from the Oracle JDBC driver’s logging, so that the Oracle support team will be willing to work on the case that I report against their driver.

**Background:** 
The OracleDatabaseHelper class already has some properties established to help users in being able to accomplish this goal.  
However, these properties are not honored today.

https://github.com/OpenLiberty/open-liberty/blob/78b12807ebc5982b34618bbaefaea221a570b564/dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java#L72-L78

On TWAS these settings were part of DataSource config. 
So the equivalent in Open Liberty would be: 
```xml
<dataSource id="oracle" jndiName="jdbc/oracle">
  <jdbcDriver libraryRef="DBLib"/>
  <properties.oracle URL="${env.URL}"
      oracleLogFileSizeLimit="5000000"
  oracleLogFileCount="1"
  oracleLogFileName="logs/oracle.log"
  oracleLogTraceLevel="ALL"
  oracleLogFormat="java.util.logging.SimpleFormatter"
  oracleLogPackageName="oracle" />        
</dataSource>
```

**Plan**
Since this user story could be generalized to fit the needs of any customer using a third party library that logs using `java.util.logging` this feature should also offer a generalized path to enabling customers to customize the logging configuration of those libraries.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:
- FTS:
- Beta Blog Post (if applicable):
- Blog Post: 
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [ ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [ ] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by donbourne** [comment]
@KyleAure , is the intent on this that all logs/trace from package `oracle` be sent to this new side log?  An alternative could be to use Liberty's json logging format and then post-process your trace if you want to find all logs with "oracle" in the module name.

to use json logging format and include trace in messages.log, set bootstrap.properties as follows:

```
com.ibm.ws.logging.message.source=message,trace,ffdc,accessLog,audit
com.ibm.ws.logging.message.format=json
```

to filter for just the records with "oracle" in the module (logger) name:
```
alias oraclelog="jq '. | select(has(\"module\")) | select(.module | contains(\"oracle\"))'"
cat messages.log | oraclelog
```

to make json output more human friendly to read:

```
alias prettylog="jq '.ibm_datetime + \"  \" + .loglevel + \"\\t\" + \" \" + .message' -r"
cat messages.log | prettylog
```

putting it all together:
```
cat messages.log | oraclelog | prettylog
```

**Comment by KyleAure** [comment]
@donbourne 

Here is what logging looks like currently when Liberty and Oracle logs are produced in the same file: 
```
[8/26/21, 16:08:57:092 CDT] 0000003d id=00000000 com.ibm.ws.jdbc.internal.JDBCDriverService                   3 set password = ******
[8/26/21, 16:08:57:092 CDT] 0000003d id=00000000 oracle.jdbc.datasource.impl.OracleDataSource                 3 setPassword 4C0C4468 Enter: "******"
```

What Oracle expects to see when using `java.util.logging` and the simple formatter:
```
Aug 31, 2021 2:52:06 PM oracle.jdbc.driver.T4CDriverExtension getConnection
FINEST: 50777B5F Enter: "jdbc:oracle:thin:@localhost:55262:xe", "[ {oracle.jdbc.enableACSupport=false}  {oracle.jdbc.ignoreReplayContextFromAuthentication=true} ]", oracle.jdbc.datasource.impl.OracleDataSource$1@20fb0ada
Aug 31, 2021 2:52:08 PM oracle.jdbc.driver.T4CDriverExtension getConnection
FINEST: 50777B5F Return: oracle.jdbc.driver.T4CConnection@202c03e0
Aug 31, 2021 2:52:08 PM oracle.jdbc.driver.T4CDriverExtension getConnection
FINEST: 50777B5F Exit: [0.619507 ms]
```

What Oracle provides customers when they request logs:
Reference: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jjdbc/JDBC-diagnosability.html#GUID-5E8CB599-C7D8-48E7-87E7-53559D22D318 
```
.level=SEVERE
oracle.jdbc.level=INFO
oracle.jdbc.handlers=java.util.logging.FileHandler
java.util.logging.FileHandler.level=INFO
java.util.logging.FileHandler.pattern=jdbc.log
java.util.logging.FileHandler.count=1
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
```

Here are the ideas we came up with to separate out the logs today: 
1. JSON logging and post process (see above comment)
2. Binary logging and post process 
    * Reference: https://www.ibm.com/docs/en/was-liberty/zos?topic=logging-binarylog-command-options
3. Overwrite or append to `java.util.logging` properties file.
    * Current testing suggests this does not currently work

I think that if we could get option (3) to work it would be the most ideal.  That is a way for a user to append to the current `java.util.logging` properties file.  Allowing them to specify a new handler and formatter for oracle logging.

Thanks again for helping to look into this.

**Comment by KyleAure** [comment]
**Config Suggestions:** 

Since, `java.util.logging` registers global loggers if this configuration was under the `dataSource` element, then when these properties are evaluated and the logging definition set all oracle datasources will use the new logger, not just the datasource that defined the properties.

Oracle may not be the only JDBC driver that also uses `java.util.Logging` and also not the only JDBC driver that customers might want to customize. 

Therefore, it would make the most sense to configure this as a top-level element , for example:

```xml
    <jdbcDriverLogging 
    	fileSizeLimit="5000000"
        fileCount="1"
	fileName="logs/oracle.log"
	traceLevel="ALL"
	formatter="java.util.logging.SimpleFormatter"
	packageName="oracle" 
    />

    <jdbcDriverLogging 
    	fileSizeLimit="5000000"
        fileCount="1"
	fileName="logs/sqlserver.log"
	traceLevel="ALL"
	formatter="java.util.logging.SimpleFormatter"
	packageName="com.microsoft.sqlserver.jdbc" 
    />

    <dataSource id="oracle" jndiName="jdbc/oracle" jdbcDriverRef="oraceLogging">
    	<properties.oracle URL="${env.URL}" />    		
    </dataSource>

    <dataSource id="oracle2" jndiName="jdbc/oracle2" jdbcDriverRef="oraceLogging">
    	<properties.oracle URL="${env.URL}" />    		
    </dataSource>

    <dataSource id="sqlserver" jndiName="jdbc/sqlserver" jdbcDriverRef="sqlserverLogging">
    	<properties.microsoft.sqlserver URL="${env.URL}" />    		
    </dataSource>
```

**Comment by frowe** [comment]
@malincoln per your request for status, this issue is not in progress and not likely to be worked on until the latter part of this year.

**Comment by KyleAure** [comment]
Closing this issue.  I think the scope of work vs the value added is not reasonable in this case. The customer use case for Oracle was already there, it just wasn't working.  So we fixed that as a serviceability issue, and we can look at a more generic feature later if a need arises.
