### ISSUE TITLE
Checkpoint testing for programming models

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#18664]
Initially checkpoint will be supported for the feature sets included in `webProfile` and `microProfile`.  This epic is to track the two profiles we plan to support for checkpoint.

**Comment by tjwatson** [comment]
The following checklist is used to evaluate if additional work is needed for supporting checkpoint

- [ ] **Does the feature use Liberty configuration values that would require an application restart to take effect?**   For example, an application scope CDI bean is injected with config from mpConfig.  Once this value is read it will require an application restart for it to be read again and noticed by the application.  Such examples need to either cause an error if the situation is detected (e.g. application scope configuration changed) or somehow make the new configuration known to the application without requiring an application restart.

- [ ] **Does the feature make connections to resources outside of the Liberty instance according to credentials from configuration?**   For example, connecting to a datasource.  Such connections need to be established after restore only and need to ensure they use the latest configuration available on restore.  Such configuration is likely not to be available at checkpoint time.

- [ ] **Does the feature make use of timed intervals to do some operation and can these intervals (or timers) get initiated during checkpoint?**   For example, use of scheduled executors to delay some work on behalf of an application.  In many cases it makes sense to have such timers be started after process restore.

- [ ] **Does the feature open channels to allow external incoming connections?**   For example, the ports for http requests.  Such ports must be opened after restore and according to the most up-to-date configuration available on restore.

- [ ] **Does the feature use current time (`java.lang.System.currentTimeMillis()`) or nano time (`java.lang.System.nanoTime()`) to compute timed deltas or timeouts?**  For example, to determine a timeout or to show the overall time it took to start the server or application.  The JVM will ensure nano time is correct and will not include large "gaps" between the time the checkpoint was taken to the time the process was restored.  On the other hand current time must always show what the actual current time is.  This will include the "gap" time between the time the checkpoint was taken to the time the restore happens.  Hint, things like schedule executors from the JVM should handle this "gap" time correctly and should not require additional steps for their usage to be correct for checkpoint.

**Comment by tjwatson** [comment]
Closing this out since it is not really used to track any of our current work.
