### ISSUE TITLE
Jakarta EE 10: Support Jakarta RESTful Web Services 3.1

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#18739]
## Description of the high level feature, including any external spec links:  
Implement the [Jakarta RESTful Web Services 3.1 specification
](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), and blogs post issues(s):
- UFO: [https://ibm.box.com/s/s9ux1xvifyc3pssqm9wpwzljin4uztrz](https://ibm.box.com/s/s9ux1xvifyc3pssqm9wpwzljin4uztrz)
- FTS: https://github.com/OpenLiberty/open-liberty/issues/23382
- Beta Blog Post (if applicable): #21764
- Blog Post:  https://github.com/OpenLiberty/open-liberty/issues/24600

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [x] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [x] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [x] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [x] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [x] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [x] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [x] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [x] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [x] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by jim-krueger** [comment]
Tasks:

- [x] Add Jakarta JAX-RS 3.1 API's into Liberty (io.openliberty.jakarta.restfulWS.3.1 bundle) - Jim
- [x] Evaluate all autofeatures involving Jakarta Rest 3.0 and create for 3.1. - Jim
- [x] Add/tolerate the mpJwt 2.0 auto feature (io.openliberty.mpJwtPropagation-2.0.feature) - Jim
- [x] Evaluate all ibm and resteasy bundles involving Jakarta Rest 3.0 and create for 3.1 (or re-use). - Jim
- [x] Evaluate all ibm bundles involving Jakarta Rest 3.0 and create for 3.1 (or re-use). - Jim
- [x] Evaluate all resteasy bundles involving Jakarta Rest 3.0 and create for 3.1 (or re-use). - Adam
- [x] Upgrade to the latest version of RESTEasy (6.1) - Jim
- [x] Include in beta - Jim
- [x] Create Issue for ID - Jim - [20868](https://github.com/OpenLiberty/open-liberty/issues/20868)
- [x] Make GlobalHandlers optional with protected feature - Adam/Jim [Issue](https://github.com/OpenLiberty/open-liberty/issues/22598)
- [x] Upgrade to use Concurrency APIs - Jim - [Issue 22895](https://github.com/OpenLiberty/open-liberty/issues/22895) - optional
- [x] Add message indicating Liberty doesn't support Java SE. - Jim [Issue 22541](https://github.com/OpenLiberty/open-liberty/issues/22541)
- [x] Enable EE10 testing (Including internal TCK) - Jim [Issue](https://github.com/OpenLiberty/open-liberty/issues/22599)
- [ ] Ensure all existing tests run additional EE10 attempts - Jim
- [x] Add FAT to test EE10 APIs (min jdk 11) - [Issue](https://github.com/OpenLiberty/open-liberty/issues/22566) - Jim
- [x] Support  new spec Multi-part APIs along with corresponding FAT - Jim [Issue 22884](https://github.com/OpenLiberty/open-liberty/issues/22884)
- [ ] Add FAT for new DefaultExceptionMapper
- [x] Add FAT for JSONB context resolvers (This is not needed as it was historically handled under PR [6485](https://github.com/OpenLiberty/open-liberty/pull/6485)
- [ ] Add FAT to register service providers via `jakarta.ws.rs.core.Configuration`
- [x] Upgrading to RESTEasy (6.2.0-Final) - Jim [Issue 22667](https://github.com/OpenLiberty/open-liberty/issues/22667)
- [x] Discuss with RESTEasy community the EE10 plans  - All (example for EE9:  https://lists.jboss.org/pipermail/resteasy-dev/2020-June/thread.html)
- [ ] Include deprecated items in blog
- [ ] Review/update Jakarta Rest Guides [Issue 22890](https://github.com/OpenLiberty/open-liberty/issues/22890)
- [x] Create STE
- [ ] Update [Multi-part documentation](https://docs-draft-openlibertyio.mybluemix.net/docs/22.0.0.4/send-receive-multipart-jaxrs.html#_prerequisites_for_sending_and_receiving_multipartform_data_parts_with_open_liberty)
- [ ] Finalize [Migration/Documentation Issue](https://github.com/OpenLiberty/open-liberty/issues/20868)



Specification changes that must be verified:

- [x] Special handling for consuming multipart/form-data media types - Andy (https://github.com/OpenLiberty/open-liberty/issues/16031) - will need to compare/contrast to RestEasy implementation aka do we keep Andy's or RestEasy's implementation for 3.1?
- [x] Standard Entity Providers `ContextResolver<Jsonb>` - https://github.com/jakartaee/rest/issues/742
- [ ] Services: Added requirement that JAX-RS implementations MUST automatically register certain service providers. - https://github.com/jakartaee/rest/pull/947
- [x] Exception Mapping Providers: Added requirement that JAX-RS implementations have default
exception mappers. (We already have this, primarily used for metrics.  May need to replace ours with RESTEasy's. Will need to work with David Chang to ensure this change wouldn't impact metrics)
- [x] Fields and Bean Properties: Array types may be specified for @CookieParam, @FormParam, @HeaderParam,
@MatrixParam and @QueryParam parameters. (Confirm in TCK)
- [x] New method #hasProperty(String) wherever #getProperty(String) exists (Confirmed in TCK:  Tested under ee/jakarta/tck/ws/rs/signaturetest/jaxrs/JAXRSSigTestIT)
- [x] Response.created(URI) now resolves relative URIs into an absolute URI against the base URI, not against the request URI anymore. - TCK not updated: [23694](https://github.com/OpenLiberty/open-liberty/pull/23694)
- [ ] [Declaring Media Type Capabilities](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#declaring_method_capabilities): Clarified resource matching when Content-Type or Accept are missing in request. - TCK not updated, need a FAT test

**Comment by dmuelle** [comment]
as part of ID for this feature, we should update the following doc to clarify that the` io.openliberty.jaxrs30` Maven/Gradle dependency is not required for multipart form/data in Resftful WS 3.1 and later

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/send-receive-multipart-jaxrs.html#_prerequisites_for_sending_and_receiving_multipartform_data_parts_with_open_liberty

**Comment by mbroz2** [comment]
## UFO Socialization discussions and comments:
**Overview**:
Consider Adding the statement that nothing is being removed, only functionality added in this version
`Done`  
**To-Be**:
Continue to try contributing extension point to RESTEasy to avoid need for overlays on our end.
  `Done`
**Feature Design**:
Lowercase 'o' in PoC
`Done.  In addition the Global Handler bullet has been stricken through since it will not be handled as part of this epic`  
**Java APIs/SPIs**:
'SeBootstrap discussion'
- Should be packaged but not exposed, that way we can pass the TCK, but not externalize it.
    - However, here it can't be hidden by package (any advanced filtering would likely be expensive), so question is what happens in non-SE environment (ok to throw exception that it's an unsupported operation)
    - Another option would be to have an API jar with the class, but not use it at runtime (runtime package would not have SeBootstrap)
- Follow up with a design issue discussion regarding Java SE Client (and find out if there's a signature test)

`The TCK test that were created to test this function have been altered to be optional under issue https://github.com/jakartaee/rest/issues/1128 and PR https://github.com/jakartaee/rest/pull/1131.  Liberty will add an exception if this is attempted under issue https://github.com/OpenLiberty/open-liberty/issues/22541`
  
**Deprecation & Stabilization**:
- Discussion regarding removal of @Context
	  - Are all the RESTful Web Services specific injections CDI Beans now and would work with @Inject?
	  - We need a good understanding which of these objects are injectable via CDI now; consider providing things that the spec doesn't to make migration easier.
	  - Follow https://github.com/jakartaee/rest/issues/951 (drop support for @Context)

`Discussion on this remains active and there are still points that need to be clarified.   For EE10 no real change is taking place other than the statement of direction potentially for Jakarta Rest 4.0 and beyond.`
  
**Automated Testing**:
  Augment existing tests to see how they behave without @Context

`At this point it is not appropriate to make these augmentations as specifics on this are still very much in discussion`
  
**Migration Impact**:
  Lowercase 'o' in PoC

`Done`

**End of UFO**:  
  Will RESTEasy update to using EE10 standard spec APIs for obtaining things like completion stages for managed executors?
  Include which modules we include from RESTEasy on one of the slides (Note: updated version of UFO Template has a OSS slide for this purpose now)

`Added the following to the Java APIs/SPIs chart and ran it past Nathan Rauh:`
`- jakarta.enterprise.concurrent.ManagedExecutorServicemethods  to create completable  futures:Added  in Jakarta  Concurrency  3.0.`

    ` -  Alter Jakarta Rest to use ManagedExecutorServiceAPIs instead ofCompletetableFutureAPIs.`
     `-  ManagedExecutorService itself isn’t new, just the methods relating to completable futures.`

**Comment by donbourne** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?

**Yes, primarily the changes between 3.0 and 3.1 are documented in the specification.  Existing 3.0 applications should not experience issues moving to 3.1.**

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated? **Problems resulting from Jakarta Rest moving to the Core Profile while Servlet and Concurrency remained in Web Profile.  In addition Global Handler configuration has changed for EE10.**
b) Who did you demo to?  **L2 (Thanh Giang and Dalat Bui)**
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3? **Yes**

4.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature? **Brian/Jag/Rumana**
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  **I've met with Brian to relay information concerning potential areas that could be problems.  While there testing is not yet completed, no issues have been relayed to me.**

5.  Which L2 / L3 queues will handle PMRs for this feature?  **WASWIN / WL3JRS**  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info. **Confirmed**

6.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs? **No**

**Comment by chirp1** [comment]
Jim provided the info to be documented in https://github.com/OpenLiberty/docs/issues/5822 The docs have been written. Jim approved the updates. I'm approving this epic.

**Comment by jim-krueger** [comment]
@OpenLiberty/ste-approvers I've loaded `RestfulWebservices 3.1 (EE10 STE.ppt`to the [Box site](https://ibm.ent.box.com/folder/52717109921?s=m5i0kgube9xyxgfckpi8gru69ow17zay).   
Note:  Several of the slides have presentation notes included to explain.

**Comment by gnadell** [comment]
WASWIN L2 is good with the STE slides hence approving.

**Comment by jim-krueger** [comment]
@donbourne  Please see my updates to the template you added back in November.   Thanks

**Comment by jim-krueger** [comment]
Epic delivered in 23.0.0.3 with all sign-offs completed.  Closing
