### ISSUE TITLE
MP Config 1.2: Post review updates including NLS

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#1873]
- [X] 1. There are a number of exceptions being thrown without NLS messages
- [X] 2. WebSphereConfig needs additional JavaDoc
- [X] 3. CompositeConfig line 204 needs splitting up to aid debugging
- [X] 4. CompositeConfig line 207 need to check if the NumberFormatException really needs catching there
- [x] 5. TypedProperty might be better named TypeContainer??
- [x] 6. TypedProperty.getProperty shouldn't have two return statements
- [x] 7. TypedProperty.add can probably be inlined
- [ ] ~8. Check if the default config sources are/should be static or dynamic~ #2106 
- [ ] ~9. Check on the performance implications of dynamic sources alway updating everything ... which invalidates the cache~ #2106 
- [x] 10. Check if the Config listeners are really needed
- [x] 11. Check if PollingDynamicConfig updateCounter and errorCounter are really needed
- [ ] ~12. default values are never cached~ #2106
- [ ] ~13. keys are never cached~ #2106
- [x] 14. move DefaultSources.java from .interface to .sources
- [X] 15. add AbstractConfig.toString to call the dump if trace is enabled

**Comment by tevans78** [comment]
Remaining items will be covered under #2106
