### ISSUE TITLE
Early release (pre-1.0) for devfile application stack for Open Liberty - Devfile 2.1 support (no outer loop)

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#19019]
Early release (pre-v1.0) of the java-openliberty devfile application stack.

![image](https://user-images.githubusercontent.com/4081634/139446231-35cb7208-bd6d-4079-9873-50ef93a469ff.png)

(Image of intended 1.0 support from UFO)

##  WHAT IS BEING DELIVERED?

* devfile 2.1 support
* stack variants for all combinations of:
  * Maven/Gradle devfiles
  * multi-arch: x/p/Z
  * WebSphere / Open Liberty  (maybe only OL in default devfile registry?)
* stack image with 
   * Java 11, Semeru-based 
   * cached maven repository with Open Liberty features & common Jakarta, MicroProfile + Maven dev dependencies
   * in each of  ICR / Docker Hub?  (will have to decide on default)
* supported project formats:
  * simple WAR
  * multi-module(EAR/WAR)
* outer loop will be scaffolded (Dockerfile, deploy template will be present with parameters but you must issue the docker build , kubectl apply cmds manually)
* customizable via:
  *  child/parent, customize via extension
  *  DF variables -LMP version, stack image. etc.
  * can use own caching strategies, (e.g. volumes), with or without our stack image (with well-known images or custom-build ones)
  * stack source template  (or similar approach patterened after our image)
* starter - default (jax-rs)
  * (should be able to use openliberty.io starter too, with Java 11) 
* samples (at least maintained in our own repo, possibly exposed via devfile registry)
  * intro JAX-RS
  * JPA
    * using a service binding to PostgreSQL, possibly DB2  (may or may not use Service Binding Operator)
* doc: 
  *  blog posts / wiki /odo doc

##  WHO USES IT?

* A developer (Jane) - using our devfile directly in her project or customizing or extending ours with her own
* An architect/team lead (Champ) - customizing or extending our devfile, possibly with stack image, and starter(s), and making available via a devfile registry.

## WHAT TOOLS DO YOU USE IT WITH ?

It fits into the devfile ecosystem, allowing use with:
* OpenShift Do (odo) 
* Eclipse Che-like IDE environments.  

Our devfile becomes "content" then for this framework or ecosystem.

## HISTORY

This builds upon work in #9343 delivered as tech preview in IBM Cloud Pak For Applications v4.3 in 4Q20.  It also represents the evolution and replacement the appsody/kabanero-based java-openliberty "stack" technology.

## FUTURE PLANS

This work will be completed at the 1.0 level in feature:  https://github.com/OpenLiberty/open-liberty/issues/14892 where outer loop support will be included, with support for the devfile 2.2 specification.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:
- FTS:
- Beta Blog Post (if applicable):
- Blog Post: 
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [ ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [ ] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by scottkurz** [comment]
UFO link: https://ibm.box.com/s/it02tpqbqnmsixywv2h8boyvkw9us9dr

**Comment by yeekangc** [comment]
Notes from UFO Review Part 1:
- Slide 30: "-app" may not be necessary so we can shorten the names.
- Review feature levels in (starter) slides and ensure they reflect the latest.

We stopped at slide 40 for part 1.  Will continue from there on for part 2.

**Comment by yeekangc** [comment]
Notes from UFO Review Part 2:
- Consider a simple REST starter template that is kept up to date for users to use;
    - Recommended path is to use Liberty Starter to create a starter and then, use odo to bootstrap a devfile.
- Slide 66: Clarify the GH repo where issues should be created.

**Comment by scottkurz** [comment]
Addressed all the Part 1 and Part 2 comments.

@yeekangc  and I elaborated on the point:
> Consider a simple REST starter template that is kept up to date for users to use; 
offline and he suggested we wondered if we could use the  https://github.com/OpenLiberty/project-templates project as a starter.

The app there is very similar to the one we define in our starter at:  https://github.com/OpenLiberty/devfile-stack-starters

   Another issue we'll have to consider then is the fact that this other template includes a (1 phase) Dockerfile whereas we'd been thinking the stack would use its own (2 phase) Dockerfile that would NOT appear in the project.   The Open Liberty starter and MP starter also include a Dockerfile each.

I think we should approve the design as is and revisit this in the 1.0 release.

**Comment by scottkurz** [comment]
Having reached design approval we're going to pause work on this and work on other priorities until we reprioritize this.

**Comment by yeekangc** [comment]
@scottkurz, can you update with a view of where we are with this (or what we have done in terms of early releases/prototyping)?

**Comment by yeekangc** [comment]
Closing per discussion with @NottyCode @gcharters.  Will file new epics for any future devfile work.
