### ISSUE TITLE
Automatically create TCK certification results for MicroProfile specs

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#19118]
## Description of the high level feature, including any external spec links:  

As part of claiming MicroProfile TCK compliance for a particular Liberty release, we need to publish the TCK results in a clear and concise format. Currently we have to manually dig into the results zips attached to release builds, extract the xml files we want and then reformat them for the certification site. This is very time consuming. e.g.

This is the 21.0.0.11 GM build
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_A9jQkDD-EeyF1bm_xnmrjA

Attached to that are many results zips from the SOE. For example, this is the zip for MP Config 3.0 TCK, running on RHEL 8 with IBM Java 8...
```
fatoutput-io.openliberty.microprofile.config.3.0.internal_fat_tck.zip	io.openliberty.microprofile.config.3.0.internal_fat_tck (Asynchronous test build for RHEL8_X86_IBMJDK8_64_EBC, full image (child-f1)) - (_dkI2QDGdEeyF1bm_xnmrjA) FAT output (results and logs)	3.0 MB	October 20, 2021 at 9:15:22 PM
```
https://libfsfe04.hursley.ibm.com/liberty/dev/Xo/release/cl211120211019-1900-_A9jQkDD-EeyF1bm_xnmrjA/child-f1-20211020-0606/fatoutput-io.openliberty.microprofile.config.3.0.internal_fat_tck.zip

Inside that file there are a number of individual results xml files. One of them is a merged version of all the results...
`results/junit/TESTS-TestSuits.xml`
We have to manually extract just the results from that file, discarding other stuff like the environment variables. The results are then embedded into an adoc file for publication on the certification site. e.g. (for 21.0.0.9 MP Config 2.0)
https://raw.githubusercontent.com/OpenLiberty/certifications/prod/microprofile/4.1/config/2.0/21.0.0.9-TCKResults.adoc

The results file above was only for Java 8. We then have to repeat the process for Java 11. The end result looks something like this: https://openliberty.io/certifications/microprofile/4.1/config/2.0/TCKResults.html

This should be automated to make it easier to publish a clear set of results from any given build.
- It should be easy to see how many tests ran and passed
- It currently includes information such as
  - A link to the Open Liberty runtime which was used to test (on maven central and may be a beta)
  - A link to the specification that was being tested (which may be an RC version)
  - A link to itself
  - A summary of the certification environment (Platform, Java version, date, host etc)
- The results should use the original test names and exclude any extraneous information added by our test framework
- The openliberty.io site should only be used to host the certifications we need to pass a certification process.  
  - The results are currently published in asciidoc format
  - If we want to expose certifications generated by continuously running builds, then they should be hosted on DHE (just like we already do for logs and test results of our `nightly builds`).  These could be linked to from openliberty.io.
  - If we chose to host on DHE, then we could consider generating .html versions of the pages instead of or in addition to .adoc (technically, the openliberty.io build process should be able to consume html files instead of adoc, but this would likely need at least some effort, at least regarding styling and headers).
  - For certifications to be hosted on openliberty.io, the automation could open a PR into https://github.com/OpenLiberty/certifications/tree/draft.  For certifications linked from ol.io to DHE, we'd have automation to dynamically list them (again, like we already do for the content of builds).

<br/><br/><br/>  

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:
- FTS:
- Beta Blog Post (if applicable):
- Blog Post: 
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [ ] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [ ] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [ ] Complete any follow-ons from the POC Review.
- [ ] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [ ] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [ ] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [ ] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [ ] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [ ] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [ ] Implementation complete. (Epic owner / Feature owner)
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [ ] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by NottyCode** [comment]
@tevans78 I'm prepared to do a no design approval, but I'd like to know what the design is and right now the description reads more like a set of requirements.

**Comment by tevans78** [comment]
@NottyCode Currently the build uses the FAT results and logs to generate a formatted asciidoc results file. Some additional details have to be hard-coded as it is not currently possible to extract them from the logs. e.g.
```
results_type = MicroProfile
feature_name = Config
feature_version = 3.0
```
The resulting adoc files are internally uploaded to each build result in RTC. The files still need a little hand editing before they can be uploaded anywhere public. Typically spec and download URLs need updating before publication. We should probably drop the requirement to automatically publish the results.

**Comment by NottyCode** [comment]
@tevans78 that still reads to me as if you have updated the requirements list rather than being an expression of a design.

**Comment by tevans78** [comment]
@NottyCode 
Simple design: When a MicroProfile TCK runs within our FAT framework, the results are output in a format which can be published to demonstrate compliance.

**Comment by NottyCode** [comment]
@tevans78 so this would just create the adoc file in the right format in the build, it wouldn't cause the file to be checked into the certification repository or GitHub certification issues to be raised at eclipse?

**Comment by tevans78** [comment]
@NottyCode Correct. That was my original idea but Michal wasn't so keen. As it turned out, we don't currently have enough information available in the build to be able to get everything automatically correct ... it needs manual intervention before being made public.
