### ISSUE TITLE
Support MP Telemetry in Open Liberty

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#19172]
## Description of the high level feature, including any external spec links:  
With the merge of OpenTracing and OpenCensus, here comes [OpenTelemetry](https://opentelemetry.io/). OpenTracing is stabilised. All of the new activities are happening on OpenTelemetry. OpenTelemetry tracing is quite popular and got great support from the communities. 

At the moment, in MP, we are discussing different approaches at the weekly MP OT calls to get OpenTelemetry into MicroProfile. We need to start experiment in Open Liberty so that we can move onto the new technology asap. 

Sandbox proposal:
https://github.com/eclipse/microprofile-sandbox/blob/master/proposals/microprofile-telemetry/microprofile-telemetry-tracing.asciidoc

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Documents

When available, add links to required feature documents. Use "N/A" to mark particular documents which are not required by the feature.

- UFO: https://ibm.box.com/s/m6gabclow0ezgsar7zplpt91q5nfmhji
- FTS: #23143
- Beta Blog: #21847
- GA Blog: #24579

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Process Overview

- [Prioritization](#prioritization)
- [Design](#design)
- [Implementation](#implementation)
- [Legal and Translation](#legal-and-translation)
- [Beta](#beta)
- [GA](#ga)
  - [Focal Point Approvals](#focal-point-approvals-complete-by-feature-complete-date)
- [Other Deliverables](#other-deliverables)

### General Instructions

The process steps occur roughly in the order as presented. Process steps occasionally overlap.

Each process step has a number of tasks which must be completed or must be marked as not applicable ("N/A").

Unless otherwise indicated, the tasks are the responsibility of the Feature Owner or a Delegate of the Feature Owner.

If you need assistance, reach out to the [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect).

**Important: Labels are used to trigger particular steps and must be added as indicated.** 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Prioritization** (Complete Before Development Starts)

The ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) and area leads are responsible for prioritizing the features and determining which features are being actively worked on.

### **Prioritization**
- [x] Feature added to the "New" column of the [Open Liberty project board](https://github.com/orgs/OpenLiberty/projects/2)
  - Epics can be added to the board in one of two ways:
    - From this issue, use the "Projects" section to select the appropriate project board.
    - From the appropriate project board click "Add card" and select your Feature Epic issue
- [x] Priority assigned
  - Attend the Liberty Backlog Prioritization meeting

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Design** (Complete Before Development Starts)

Design preliminaries determine whether a formal design, which will be provided by an [Upcoming Feature Overview (UFO)](https://ibm.box.com/v/UFO-Template) document, must be created and reviewed.  A formal design is required if the feature requires any of the following: UI, Serviceability, SVT, Performance testing, or non-trivial documentation/ID.

### **Design Preliminaries**
- [ ] UI requirements identified. (Owner and [UI focal point](https://github.com/orgs/OpenLiberty/teams/ui-approvers))
- [ ] ID requirements identified. (Owner and [ID focal point](https://github.com/orgs/OpenLiberty/teams/id-approvers))
   - Refer to [Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty).
   - Feature Owner adds label `ID Required`, if non-trivial documentation needs to be created by the ID team.
   - ID adds label `ID Required - Trivial`, if no design will be performed and only trivial ID updates are needed.
- [ ] Serviceability Requirements Identified. (Owner and [Serviceability focal point](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
- [ ] SVT Requirements Identified. (Owner and [SVT focal point](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
- [ ] Performance testing requirements identified. (Owner and [Performance focal point](https://github.com/orgs/OpenLiberty/teams/performance-approvers))

### **Design**
- [x] POC Design / UFO review requested.
  - Owner adds label `Design Review Request`
- [x] POC Design / UFO review scheduled.
  - Follow the instructions in POC-Forum repo
- [x] POC Design / UFO review completed.
- [x] POC / UFO Review follow-ons completed.
- [x] POC Design / UFO approval requested.
  - Owner adds label `Design Approval Request`
- [x] Design / UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) adds label `Design Approved`
  - Add the public link to the UFO in Box to the [Documents](#documents) section.
  - The UFO must always accurately reflect the final implementation of the feature. Any changes must be first approved. Afterwards, update the UFO by creating a copy of the original approved slide(s) at the end of the deck and prepend "OLD" to the title(s). A single updated copy of the slide(s) should take the original's place, and have its title(s) prepended with "UPDATED".

### **FAT Documentation**
- [x] "Feature Test Summary" child task created
  - Use the [Feature Test Summary Template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=)
  - Add FTS issue link to the [Documents](#documents) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Implementation**

A feature must be [prioritized](https://github.com/orgs/OpenLiberty/projects/2) before any implementation work may begin to be delivered (inaccessible/no-ship).  However, a design focused approach should still be applied to features, and developers should think about the feature design prior to writing and delivering any code.  
Besides being prioritized, a feature must also be socialized (or No Design Approved) before any beta code may be delivered.  All new Liberty content must be inaccessible in our GA releases until it is [Feature Complete](#feature-complete) by either marking it `kind=noship` or [beta fencing](#beta-code) it.  
Code may not GA until this feature has obtained the "Design Approved" or "No Design Approved" label, along with all other tasks outlined in the [GA](#ga) section.

### **Feature Development Begins**
- [x] Add the `In Progress` label

## **Legal and Translation**

In order to avoid last minute blockers and significant disruptions to the feature, the **legal items need to be done as early in the feature process as possible**, either in design or as early into the development as possible.  Similarly, translation is to be done concurrently with development.  Both **MUST** be completed before Beta or GA is requested.

### **Legal** (Complete before Feature Complete Date)
- [x] Changed or new open source libraries are cleared and approved, or N/A. (Legal Release Services/Cass Tucker/Release PM).
- [x] Licenses and Certificates of Originality (COOs) are updated, or N/A

### **Translation** (Complete 1 week before Feature Complete Date)
- [ ] PII updates are merged, or N/A. Note timing with translation shipments.

### **Innovation** (Complete 1 week before Feature Complete Date)
- [ ] Consider whether any aspects of the feature may be patentable. If any identified, disclosures have been submitted.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Beta**

In order to facilitate early feedback from users, all new features and functionality should first be released as part of a beta release.

### **Beta Code**
- [x] Beta fence the functionality
  - `kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`
- [x] Beta development complete and feature ready for inclusion in a beta release
  - Add label `target:beta` and the appropriate `target:YY00X-beta` (where YY00X is the targeted beta version).
- [x] Feature delivered into beta
  - ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager)) adds label `release:YY00X-beta` (where YY00X is the first beta version that included the functionality).

### **Beta Blog** (Complete 1.5 weeks before beta eGA)
- [x] Beta blog issue created and populated using the [Open Liberty BETA blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the beta blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [beta release blog post](https://openliberty.io/blog/?search=beta&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **GA**

A feature is ready to GA after it is Feature Complete and has obtained all necessary Focal Point Approvals. 

### **Feature Complete**
- [x] Feature implementation and tests completed.
  - [x] All PRs are merged.
  - [ ] All epic and child issues are closed.
  - [x] All stop ship issues are completed.
- [x] Legal: all necessary approvals granted.
- [x] Translation: All messages translated or sent for translation for upcoming release 
- [x] GA development complete and feature ready for inclusion in a GA release
  - Add label `target:ga` and the appropriate `target:YY00X` (where YY00X is the targeted GA version).
  - Inclusion in a release requires the completion of all Focal Point Approvals.

### **Focal Point Approvals** (Complete by Feature Complete Date)

These occur only after GA of this feature is requested (by adding a `target:ga` label).  GA of this feature may not occur until all approvals are obtained.

### **All Features**
- [x] **APIs/Externals** Externals have been reviewed or N/A.  ([OpenLiberty/externals-approvers](https://github.com/orgs/OpenLiberty/teams/externals-approvers))
  - Approver adds label `focalApproved:externals` 
- [x] **Demo** Demo is scheduled for an upcoming EOI or N/A. ([OpenLiberty/demo-approvers](https://github.com/orgs/OpenLiberty/teams/demo-approvers))
  - Add comment `@OpenLiberty/demo-approvers Demo scheduled for EOI [Iteration Number]` to this issue.
  - Approver adds label `focalApproved:demo`.
- [x] **FAT** All Tests complete and running successfully in SOE or N/A. ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers))
  - Approver adds label `focalApproved:fat`.
- [x] **Globalization** Translation and TVT are complete or N/A. ([OpenLiberty/globalization-approvers](https://github.com/orgs/OpenLiberty/teams/globalization-approvers))
  - Approver adds label `focalApproved:globalization`.

### **Design Approved Features**
- [x] **Accessibility** Accessibility testing completed or N/A. ([OpenLiberty/accessibility-approvers](https://github.com/orgs/OpenLiberty/teams/accessibility-approvers))
  - Approver adds label `focalApproved:accessibility`.
- [x] **ID** Documentation is complete or N/A. ([OpenLiberty/id-approvers](https://github.com/orgs/OpenLiberty/teams/id-approvers))
  - Approver adds label `focalApproved:id`.
  - > **_NOTE:_**  If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [x] **Performance** Performance testing is complete or N/A. ([OpenLiberty/performance-approvers](https://github.com/orgs/OpenLiberty/teams/performance-approvers))
  - Approver adds label `focalApproved:performance`.
- [x] **Serviceability** Serviceability has been addressed or N/A. ([OpenLiberty/serviceability-approvers](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
  - Approver adds label `focalApproved:sve`.
- [x] **STE** Skills Transfer Education chart deck is complete or N/A. ([OpenLiberty/ste-approvers](https://github.com/orgs/OpenLiberty/teams/ste-approvers))
  - Approver adds label `focalApproved:ste`.
- [x] **SVT** System Verification Test is complete or N/A. ([OpenLiberty/svt-approvers](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
  - Approver adds label `focalApproved:svt`.

### **Remove Beta Fencing** (Complete by Feature Complete Date)
- [x] Beta guards are removed, or N/A
  - Only after all necessary Focal Point Approvals have been granted.

### **GA Blog** (Complete by Feature Complete Date)
- [x] GA Blog issue created and populated using the [Open Liberty GA release blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the GA Blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [release blog post](https://openliberty.io/blog/?search=release&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

### **Post GA**
- [x] Replace `target:YY00X` label with the appropriate `release:YY00X`. ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager))

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Other Deliverables**

- [x] **Standalone Feature Blog Post** A blog post specifically about your feature or N/A.  ([OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect))
  - This should be strongly considered for larger or more prominent features.
  - Follow [instructions](https://github.com/OpenLiberty/blogs/tree/draft#writing-and-publishing-blog-posts-on-the-openlibertyio-blog) in the blogs repo.
- [x] **OL Guides** OL Guides assessment is complete or N/A. ([OpenLiberty/guide-assessment](https://github.com/orgs/OpenLiberty/teams/guide-assessment/members))
- [ ] **Dev Experience** Developer Experience & Tools work is complete or N/A. ([OpenLiberty/dev-experience-assessment](https://github.com/orgs/OpenLiberty/teams/dev-experience-assessment/members))
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by fmhwong** [comment]
ID issue: https://github.com/OpenLiberty/docs/issues/5258

**Comment by covener** [comment]
June 10 notes:

1. p3: opentelemetry operator in corner of RHOCP (Don) 
2. p3: jaeger/b3 is unclear to end users. (Eric)
3. p3: even agent is optional but simplifies config (Emily?)
4. p3: detail on frequency/timing of reading mpConfig settings (Tom Watson)
5. throughout: replace "jax-rs"? (Michal/Emily)
   - seems no consensus
6. update opentracing guide to refer to opentelemetry for later and addl details
7. p10: emphasize collector is always outside of the server (Eric)
8. Collectors are optional and not supplied by our team (Eric)
9. In tech background Clarify up-front "trace" and "span" since "trace" is not "verbose logging" (Eric)a
10.p27: pick up next time

**Comment by covener** [comment]
pt2 notes:

1. p27: server.xml change for MP property should be picked up on the fly (but maybe not for perf?) (Jared)
1. p27: checkpoint restore would need a hook (Thomas)
1. p27: agent may still trace even if the MP property is off (Don)
1. p28: mp.telemetry.tracing.name vs otel? Global one needed for agent? (Emily)
1. p32: agent is optional config (and why) (Eric)
1. p32: get otel to change/add Liberty/OpenLiberty (Emily)
1. p33: MP feature false, agent attached: spans still created by agent (or other API) and still sent to collectors (Emily, Eric)
1. p35: non-MP opentracing needs to be stabilized too. And use literal feature names in UFO (Jared)
1. p36: otel metrics collision, maybe need otel feedback (Don)
1. p41: FAT w/ agent? (Eric/Don)
    - does agent interfere with metrics or anything else related?
1. p42: zipkin in either FAT or SVT (Jared)
1. p43: impact w/ MP property off too (Jared)

**Comment by Yas-Franco** [comment]
Blog post in progress:
#21847

**Comment by tevans78** [comment]
Need to resolve J2S issues before GA - https://github.com/OpenLiberty/open-liberty/issues/22689

**Comment by Azquelt** [comment]
Corrected links, created FTS issue, updated epic description to match the latest template.

**Comment by fmhwong** [comment]
Updated the UFO (v42) based on the UFO review comments.

> June 10 notes:
> 
>     1. p3: opentelemetry operator in corner of RHOCP (Don)
Added a note "OpenTelemetry Operator can be used to setup the collectors in OpenShift."
> 
>     2. p3: jaeger/b3 is unclear to end users. (Eric)
In page 2, use "Spans (Jaeger/Zipkin)" instead of "jaeger/b3"
> 
>     3. p3: even agent is optional but simplifies config (Emily?)
Added the following to Collector (p.11) slide.
Use of collector is optional but it allows your service to offload data quickly and the collector can take care of additional handling like retries, batching, encryption or even sensitive data filtering.
> 
>     4. p3: detail on frequency/timing of reading mpConfig settings (Tom Watson)
It’s read at the first JAX-RS call and then only again if the config file is changed and the server updates
> 
>     5. throughout: replace "jax-rs"? (Michal/Emily)
>        * seems no consensus
No action is needed.
> 
>     6. update opentracing guide to refer to opentelemetry for later and addl details
Opened issues and added 
> 
>     7. p10: emphasize collector is always outside of the server (Eric)
Updated the Collector (p.11) slide saying the collector is not provided by OpenLiberty and it is running as a separate process.
> 
>     8. Collectors are optional and not supplied by our team (Eric)
Updated the Collector (p.11) slide.
> 
>     9. In tech background Clarify up-front "trace" and "span" since "trace" is not "verbose logging" (Eric)a
>        10.p27: pick up next time
Added p.7 Distributed Tracing to briefly talked about traces and spans.

> pt2 notes:
> 
>     1. p27: server.xml change for MP property should be picked up on the fly (but maybe not for perf?) (Jared)
Yes
> 
>     2. p27: checkpoint restore would need a hook (Thomas)
To follow up with Tom
> 
>     3. p27: agent may still trace even if the MP property is off (Don)
Agent can be disabled with otel.javaagent.enabled=false (p.37)
> 
>     4. p28: mp.telemetry.tracing.name vs otel? Global one needed for agent? (Emily)
The new config name to enable/disable is "otel.sdk.disabled" in p.31
> 
>     5. p32: agent is optional config (and why) (Eric)
Use of the OTel agent is optional.  Update p.36
> 
>     6. p32: get otel to change/add Liberty/OpenLiberty (Emily)
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7346
> 
>     7. p33: MP feature false, agent attached: spans still created by agent (or other API) and still sent to collectors (Emily, Eric)
No action is required.
> 
>     8. p35: non-MP opentracing needs to be stabilized too. And use literal feature names in UFO (Jared)
Updated Deprecation and Stabilization page
> 
>     9. p36: otel metrics collision, maybe need otel feedback (Don)
Will follow up with Don
> 
>     10. p41: FAT w/ agent? (Eric/Don)
>         * does agent interfere with metrics or anything else related?
Added to Automated Testing page
> 
>     11. p42: zipkin in either FAT or SVT (Jared)
Zipkin is added
> 
>     12. p43: impact w/ MP property off too (Jared)
Scenario is added

**Comment by fmhwong** [comment]
@NottyCode Could you take a look of the UFO again?  I'd like to get your design approval.

**Comment by fmhwong** [comment]
@samwatibm We have no new messages file in this feature.  May I get the G11N approval?

**Comment by samwatibm** [comment]
Sorry, not until you get design approvals!

**Comment by NottyCode** [comment]
@fmhwong I have the following questions:

1. Do spans get processed for any inbound http traffic, or is it just a subset? What about outbound http requests?
2. There was a discussion on the call about Otel being disabled OOTB and none of that was reflected in the deck. It seemed that things were more nuanced but that doesn't seem captured in the design.
3. The design should be explicit that if you use the Java API you lose zero migration. I still do not like this.
4. Slide 32 says that if there are multiple applications otel.service.name should be set in microprofile-config.properties but this doesn't make sense since that is application scoped and thus the multiple applications could have different names, wouldn't it be better to specify in bootstrap.properties, env vars or server.xml in that case?

**Comment by fmhwong** [comment]
@NottyCode 

1.  I created a new [epic](https://github.com/OpenLiberty/open-liberty/issues/24379) for inbound http requests.  For outbound requests, we will need to investigate if there is a hook point we can use.
2. Will update the UFO to make it clear on the disable property is used.
3. Will update the UFO.
4. `otel.service.name` should be unique for each app.

**Comment by fmhwong** [comment]
@NottyCode 

In v46 of the design document, I made the following updates.

- For (2), updated slide 31 on tracing enablement.
- For (3), updated Migration slide 52 to make this clear.
- For (4), updated slide 32 for the option of setting `otel.service.name` in `server.xml` using `<appProperties>`

**Comment by fmhwong** [comment]
@NottyCode 

In v47, I added "zero migration is not guaranteed" in the Third Party APIs slide 21.

**Comment by Yas-Franco** [comment]
@OpenLiberty/demo-approvers Demo scheduled for EOI  23.5

**Comment by Azquelt** [comment]
@OpenLiberty/ste-approvers The STE is now available on the internal L3 site

**Comment by gnadell** [comment]
WASWIN L2 Support is good with the STE slides, hence approving.

**Comment by Azquelt** [comment]
@OpenLiberty/serviceability-approvers Serviceability approval comment

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?
    - Yes (Slide 50)

3.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?
    - I demoed this to @benjamin-confino who works on L3
    - I demonstrated several problem scenarios
        - Not configuring the feature
        - Misconfiguring the exporter endpoint
        - Attempting to use the API without enabling `third-party` APIs
        - Starting a span without ending it
    - We thought the serviceability for these scenarios was fine

4.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature?
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  
    - @hanczaryk did the SVT for this feature

5.  Which L2 / L3 queues will handle PMRs for this feature?  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info.
    - WL3CDI will handle PMRs for this feature

7.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?
    - No

**Comment by Azquelt** [comment]
@OpenLiberty/accessibility-approvers There is no UI for this feature. Is anything else needed for accessibility approval?

**Comment by Azquelt** [comment]
@OpenLiberty/externals-approvers Is there any further information you need to approve this feature?

**Comment by chirp1** [comment]
Info to doc for telemetry is in the doc issue at https://github.com/OpenLiberty/docs/issues/5258 . Draft of documentation was written and is going through reviews. Approving this epic.

**Comment by samwatibm** [comment]
@fmhwong globalization approvals removed pending translations for:
https://github.com/OpenLiberty/open-liberty/pull/24397/files
https://github.com/OpenLiberty/open-liberty/pull/24247/files

**Comment by Yas-Franco** [comment]
GA blog issue: #24579

**Comment by anneqm** [comment]
@fmhwong @yasmin-aumeeruddy I'm working with Cass on OSS clearances, a few questions for you on the included open source:

Comparing OSS listed in UFO for OSS Clearance..  Can we please CONFIRM the license(s) for these three OSS packages?  Mend is coming up with "requires review";  @yasmin-aumeeruddy confirmed these are Apache 2.0 and provided Maven links. Anne will open Mend ticked to get these resolved properly for future use. 

1. opentelemetry-instrumentation-annotations | 1.19.0-alpha2. 
2. opentelemetry-instrumentation-annotations-support | 1.19.0-alpha4. 
3. opentelemetry-instrumentation-api-semconv | 1.19.0-alpha6. 

These 3 additional packages show up in Mend scan for Beta, but are not included in the UFO OSS listing. Please confirm if they are also part of the GA feature or not: (@yasmin-aumeeruddy confirms these ARE included in the GA package).

1. opentelemetry-exporter-logging	1.19.0
2. opentelemetry-extension-trace-propagators	1.19.0
3. opentelemetry-sdk-logs	1.19.0-alpha

Thanks in advance for your help!

**Comment by fmhwong** [comment]
Issue for guide: https://github.com/OpenLiberty/guides-common/issues/888

**Comment by yasmin-aumeeruddy** [comment]
The required issues for MicroProfile Telemetry 1.0 are complete. The remaining issues are not required for this feature and can be completed for MicroProfile Telemetry 1.1

**Comment by Yas-Franco** [comment]
The required issues for MicroProfile Telemetry 1.0 are complete. The remaining issues are not required for this feature and can be completed for MicroProfile Telemetry 1.1
