### ISSUE TITLE
Automate Liberty FAT bucket to run the JSON-P TCK

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#19404]
User story:
"As the development team, I want an automated test bucket that runs the JSON-P TCK so that we can ensure that we only permit changes to go in which comply with the TCK, to avoid causing regressions to users."

Location of TCK(s): 
Test: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/json/jakarta.json-tck-tests/2.1.0/
Pluggability: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/json/jakarta.json-tck-tests-pluggability/2.1.0/

This TCK does not provide Platform tests and therefore does not need to run against a running server. 
TCK that performs similar tests: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.jsonb.3.0_fat_tck

Key deliverables (can be separate commits/pulls): 
- [x] New functional test project io.openliberty.jakarta.jsonp.2.1_fat_tck
- [x] Determine the difference between TCK artifacts (test vs pluggability) and which of these tests need to run
    - The best place to find this information may be the TCK-DIST: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/json/jakarta.json-tck-dist-epl/2.1.0/ 
- [x] Fix JSONP TODOs in the JSONB TCK
    - https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/publish/tckRunner/tck/pom.xml#L91-L98
    - https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/publish/tckRunner/tck/pom.xml#L74-L81
    - Copy internal bundle instead of external artifact: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/publish/tckRunner/tck/pom.xml#L126-L164
