### ISSUE TITLE
SpringBoot 3.0: Support Spring Boot 3.0

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#19982]
Per review, this will continue to be worked unless told otherwise.

---

## Description of the high level feature, including any external spec links:  
Spring Boot 3.0 is slated for 4Q22.  It will require Java 17 and move to the jakarta package namespace.  Support for JPMS is likely to be optional.  We should provide a new Spring Boot 3.0 feature as we have done for Spring Boot 2.0 and older.
https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6

---

## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), blogs post issues(s), and [Aha](https://cloud-platform.ideas.aha.io/) (externally raised RFEs):
- UFO:
  -  UFO for V2.0: https://ibm.box.com/s/6g7rq3acac4ut4wt4bhnbx87a328v495
- FTS: https://github.com/OpenLiberty/open-liberty/issues/25753
- Beta Blog Post: https://github.com/OpenLiberty/open-liberty/issues/25679
- Blog Post: https://github.com/OpenLiberty/open-liberty/issues/25973
- Aha: 
   - Also, add a comment into the Aha idea linking to this issue.
- Working notes on box: https://ibm.box.com/s/vqgunkq6pf47i8oj4rsg4b37jl9x362i

---

## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [N/A] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [N/A] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [N/A] Complete any follow-ons from the POC Review.
- [N/A] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [X] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
  * Note: Design is required if any of the following apply: SVT or Performance testing, new UI, Servicibility considerations, significant documentation changes
- [X] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [X] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [X] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [X] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [X] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [X] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [X] Implementation complete. (Epic owner / Feature owner)
- [X] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [ ] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [N/A] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [X] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
  * Note: If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [X] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [N/A] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [N/A] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by berndgoetz** [comment]
Hi, is there any activity on this topic? I tried to run Open Liberty with Spring Boot 3.0.1 but failed.

It fails with

```
Launching spacer (Open Liberty 22.0.0.3/wlp-1.0.62.cl220320220302-1100) on OpenJDK 64-Bit Server VM, version 17.0.1+12 (en_US)
...
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application Gradle___pccc___sluwo_spacer_0_9_1_plain_war__exploded_. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: com.ibm.wsspi.adaptable.module.UnableToAdaptException: com.ibm.ws.javaee.ddmodel.DDParser$ParseException: CWWKC2261E: The sluwo-spacer-0.9.1-plain.war : WEB-INF/lib/tomcat-embed-el-10.1.4.jar : META-INF/web-fragment.xml deployment descriptor on line 23 specifies unsupported version 6.0.
```

I'm using the following features:

```
  <featureManager>
    <feature>webProfile-9.1</feature>
    <feature>localConnector-1.0</feature>
  </featureManager>

```

**Comment by NottyCode** [comment]
I haven't had a chance to try out a SpringBoot 3 application on Liberty yet, but looking at that error message it indicates that tomcat-embed-el-10.1.4.jar is using Servlet 6 and webProfile-9.1 is Servlet 5. I've checked the Tomcat release pages and it says that 10.0 implements Servlet 5 and Tomcat 10.1 implements Servlet 6.

You would thus have a choice, either download and use the Open Liberty beta and update to use webProfile-10, or configure Spring Boot 3 to use Tomcat 10.0 instead of 10.1.

I will admit I'm kind of confused because everything I've read has said that Spring Boot 3 is based on Jakarta EE 9, but it seems like Spring Boot is using Tomcat 10.1.4 which is Jakarta EE 10.

**Comment by NottyCode** [comment]
@berndgoetz I have managed to get Petclinic to start on 23.0.0.13 of Open Liberty. The most recent version of Petclinic is based on Spring Boot 3. In order to get it running I had to make the following changes:

1. Change the pet clinic pom.xml packaging type from jar to war
2. Add a ServletContainerInitializer
3. Add the following to the dependencies section: 
```
 <dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-tomcat</artifactId>
   <scope>provided</scope>
</dependency>
<dependency>
  <groupId>org.apache.tomcat.embed</groupId>
  <artifactId>tomcat-embed-websocket</artifactId>
  <version>10.1.4</version>
  <scope>provided</scope>
</dependency>
<dependency>
  <groupId>org.apache.tomcat.embed</groupId>
  <artifactId>tomcat-embed-el</artifactId>
  <version>10.1.4</version>
  <scope>provided</scope>
</dependency>
```
4. Configured Liberty with the following features:
```
    <featureManager>
        <feature>servlet-5.0</feature>
        <feature>websocket-2.0</feature>
        <feature>expressionLanguage-4.0</feature>
        <feature>jdbc-4.2</feature>
    </featureManager>
```

That allowed me to get these things working. There might be a better way to stop it packaging the tomcat el and web socket dependencies, but this got it to start and be accessible. 

I also reached out to some Spring Boot contributors and they told me that Tomcat 10.0 (which is the Jakarta EE 9 compatible Tomcat) was end of life, so they had to build on Tomcat 10.1. While they believe you could downgrade to 10.0 the Mock Servlet support they have would not work, so I thought excluding these dependencies from the produced war was a better direction.

**Comment by hlhoots** [comment]
A requirement that must be completed for this feature is the update to gradle capable of Java 17.  This is being tracked via this issue:  https://github.ibm.com/WAS-CD-Area/WAS-CD-Area/issues/867

Target locations of links might be accessible only to IBM employees.

**Comment by faandg** [comment]
Spring boot support (non-commercial) for 2.7 and 3.0 [seems to be expiring towards Q4 2023](https://spring.io/projects/spring-boot#support). 
Spring boot 3.1 will be supported longer until May 2024.
Since 2.7 -> 3.0 will be most migration effort, our clients are trying to get ahead by starting migrations to 3.0.

However, starting our containers with a Spring boot 3.0 application and Liberty's springboot-2.0 feature results in failure to start because the application is trying to start the embedded Tomcat within Liberty. 
Normally the springboot feature should stop this from happening if I am not mistaken, hence we would need the springboot-3.0 feature.

Alternatively we could [exclude the dependency](https://stackoverflow.com/questions/47827560/how-to-exclude-embeded-tomcat-in-spring-boot-application/47828590#47828590) but the Liberty feature may contain additional optimizations we don't want to lose.

**Comment by NottyCode** [comment]
@faandg you are right that the Spring Boot 2.x feature won't work with Spring Boot 3, but I think the code trying to start embedded Tomcat is likely more a symptom of the underlying issue which is the `springboot-2.0` feature requires Jakarta EE 8/Java EE 7 and Spring Boot 3 requires Jakarta EE 10 and these are not source or binary compatible.

**Comment by faandg** [comment]
@NottyCode I understand, due to the class namespace changes and such.
Seeing how the Spring support 2.x and 3.0 is dropped in November though, there isn't much time to release a new `springboot-3.0` feature (which I assumed this ticket is for) which would be compatible with the new specification. 
This feature is needed to allow Liberty developers to migrate to 3.x and test, ideally before support expires.

**Comment by cbridgha** [comment]
Initial PR for features: https://github.com/OpenLiberty/open-liberty/pull/25329

**Comment by jimblye** [comment]
PR for SpringBootThinUtility updates #25406

**Comment by hlhoots** [comment]
Based on the following, **No Design Approval** is requested for this feature:

The implementation of the SB 3 feature is straightforward given the existing design of the SB 1.5 and SB 2.0 features.  The prerequisite of Java 17 for SB 3 has been resolved by the recent update of the Liberty build infrastructure to use Java 17 (see PRs https://github.com/OpenLiberty/open-liberty/pull/25119 and https://github.com/OpenLiberty/open-liberty/pull/25242 for details).  We added a new  prerequisite for servlet-6.0 to the SB 3 feature.  A new SB 3 web feature was created based on the SB 2.0 feature with minor updates.  The Liberty support to remove the internal server packaged with the application at run time is common code and is being reused.  Configuration is the same as SB 2.0, with the exception of 1) features must be updated to their JakartaEE10 equivalents, and 2) a new SpringBoot3 server template, which provisions the JakartaEE10 feature, must be used.  No metatype updates are required.  Additionally, only minimal updates are required to the springbootUtility to ensure that the correct SB 3 jars are supported for thinning.

A minimal server configuration to run a SB 3 application will be almost the same as for prior Springboot versions:

server.xml
```
<features>
  <feature>springboot-3.0</feature>
  <feature>servlet-6.0</feature>
</features>

<springBootApplication id="petclinic" location="spring-petclinic.jar" name="petclinic" /> 
```
NOTE: The SB 3 application can be of type .jar or .war.

The creation of the new Springboot-3.0 feature consists of the following tasks:
1.	Defining the new Springboot-3.0 feature with the correct level of dependencies to run with Java 17 and servlet-6.0 https://github.com/OpenLiberty/open-liberty/pull/25329

- This includes the feature definitions, but also now switching to “jakarta transformed bundles for the EE10 required api’s.

- We made SB changes when needed for SB configuration from SB 2 to SB 3. 

2.	When we GA we’ll have updated the SB 3.x jar’s to the latest released version - currently 3.1.
3.	Updating the springbootUtility to support and thin the correct version of SB 3 jars https://github.com/OpenLiberty/open-liberty/pull/25406. 
4.	Ensure we support all the previously supported SB 2.0 starters referred to on this page for SB 3: https://www.ibm.com/docs/en/was-liberty/base?topic=architecture-spring-boot-programming-model-support
5.	Creating test cases similar to those that exist for SB 1.5 and 2.0. 
6.	Creating a blog around this new feature with hints and tips on migrating a Springboot app to the 3.x level. 
7.	We need to engage with the SVT and Performance testing teams prior to release.
8.	We need to engage with the Tools team to ensure Liberty Plugin works as expected with SB 3.
9.	Documentation should include, minimally, a guide for migrating liberty server configurations to SB 3.0 from earlier SB releases. This migration guide is expected to be no more than a few paragraphs, as the migration changes are small. Note: The guide should reference guides to migrating SB applications, but should not itself include application migration details. This is significant as SB 3.0 removed deprecated function. In particular, application security configuration must be updated. The result is that application migration requires more significant documentation. See the following links for security configuration changes:

- https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
- https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html
- https://stackoverflow.com/questions/72381114/spring-security-upgrading-the-deprecated-websecurityconfigureradapter-in-spring

**Comment by hlhoots** [comment]
Beta blog issue: https://github.com/OpenLiberty/open-liberty/issues/25679

**Comment by hlhoots** [comment]
Feature Test Summary: https://github.com/OpenLiberty/open-liberty/issues/25753

**Comment by hlhoots** [comment]
ID change request is here: https://github.ibm.com/websphere/liberty-docs/issues/3568

Target locations of links might be accessible only to IBM employees.

**Comment by hlhoots** [comment]
@LifeIsGood524 We are seeking Globalization approval for this feature given that we added new messages.  These should have been sent out in the last batch. CC @cbridgha

**Comment by LifeIsGood524** [comment]
@hlhoots Have you verified that everything you’ve delivered that requires translation has been translated, returned and merged into the release branch?

**Comment by hlhoots** [comment]
@LifeIsGood524 Yes, they look to be correct here with the latest commit being 'NLS Returns for 23008': https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.app.manager.springboot/resources/com/ibm/ws/app/manager/springboot/internal/resources

**Comment by LifeIsGood524** [comment]
You had me at "Yes".....approved

**Comment by hlhoots** [comment]
GA BLOG https://github.com/OpenLiberty/open-liberty/issues/25973
