### ISSUE TITLE
CRIU : EJBContainer settings for deferred EJB initialization and bean pool preloading

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#20368]
There are 3 EJBContainer settings that should improve restore performance by enabling additional application initialization prior to checkpoint that occurs after application start:

**1 - startEJBsAtAppStart in server.xml (or com.ibm.websphere.ejbcontainer.initializeEJBsAtStartup ) as a JVM property.**
```
    <ejbContainer startEJBsAtAppStart="true"/>
```
or, in `ibm-ejb-jar-ext.xml`
```
<session name="AccountServiceBean">
 <start-at-app-startvalue="TRUE"/>
</session>
```
The default is "false", but switching the default to "true" should be considered for the checkpoint scenario.  A customer could specifically set it to "false" in `ibm-ejb-jar-ext.xml` to disable for a bean.  Should decide what effect setting this in server.xml would have for checkpoint (would checkpoint override?)

For testing, I'd recommend the setting in server.xml (or as a JVM property) for now, but be aware the setting in ibm-ejb-jar-ext.xml would override it.

Recommendation:
- EJBContainer can check for "checkpoint" and change the default setting for this config option if not explicitly disabled

**2 - com.ibm.websphere.ejbcontainer.poolSize as a JVM property.**
```
com.ibm.websphere.ejbcontainer.poolSize=*=H50,500
```
This will preload the bean pools with 50 instances per stateless bean type.  The pool may grow to a max of 500.

The default is 50,500, adding the H makes it a "hard limit", so is a request to preload to the minimum value.  Default is to start the pool at 0 and let it grow as used. Adding an H to the second value (500) would set a hard max limit, so the EJB Container would never create more than that; generally not recommended.

The * is the bean type (all), so you may specify this for individual beans with a comma separate list.

Note: the bean pools are "preloaded" using a background thread, so the application may report that it has started before the pools have been preloaded. 

- For the CRIU scenario, perhaps the default should change to `H50,500`.  This would be overridden by the JVM setting.
- EJBContainer should check if the server is for "checkpoint", and then preload the pools synchronously, rather than asynchronously.

**3 - `@Startup` or ` <init-on-startup>` for Singleton beans to force preCreate of bean.**

An instance of a Singleton bean is normally created on first use, but an app developer may add `@Startup` to force the bean to be created during application start.  Similar behavior could be added automatically when creating a checkpoint.

- EJB Container could check for "checkpoint" and switch singleton beans to be `@Startup`.

---
#### Recommended Implementations:
**1 - startEJBsAtAppStart in server.xml (or com.ibm.websphere.ejbcontainer.initializeEJBsAtStartup ) as a JVM property.**
- [x] Implemented by: [20595: Default EJBInitAtStartup for CRIU](https://github.com/OpenLiberty/open-liberty/pull/20595)
- [x] Implemented by [21305: Default EJBInitAtStartup for CRIU DEPLOYMENT](https://github.com/OpenLiberty/open-liberty/pull/21305)

**2 - com.ibm.websphere.ejbcontainer.poolSize as a JVM property.**
- [x] Implemented by: [20863: Preload EJB pools for CRIU](https://github.com/OpenLiberty/open-liberty/pull/20863)

**3 - `@Startup` or ` <init-on-startup>` for Singleton beans to force preCreate of bean.**
- [x] Implemented by: [20910: Preload Singleton EJBs for CRIU](https://github.com/OpenLiberty/open-liberty/pull/20910)

**Comment by dettmoney** [comment]
I ran some experiments with the three checkpoint options (features, deployment, applications) to see if these two particular suggestions would help first response time. I used daytrader7, specifically measuring the startup and first response to the ejb3/PingServlet2SessionRemote servlet (format <startup>/<first response).
baseline:
features - 2915ms/3235ms
deployment - 2421ms/2698ms
applications - 236ms/587ms
add startEJBsAtAppStart=true to server.xml:
features - 3019ms/3279ms
deployment - 2408ms/2682ms
applications - 222ms/532ms
add poolSize to applicable beans:
features - 3103ms/3240ms
deployment - 2548ms/2692ms
applications - 231ms/394ms

I see a 33% drop in first response time when adding these two options with the applications checkpoint. No effect on the other two checkpoint options.

Normal JVM startup/first response time:
baseline: 5494ms/5749ms
add startEJBs=true: 5663ms/5967ms
add poolSize settings: 5863ms/6000ms

**Comment by tkburroughs** [comment]
#build

**Comment by tjwatson** [comment]
@tkburroughs is all planned work here done?  Can we close this?

**Comment by tkburroughs** [comment]
@tjwatson I had left this issue open pending the outcome of design issue https://github.com/OpenLiberty/open-liberty/issues/20490.

Based on recent changes for limiting transactional work during checkpoint, that limits the options for EJB, and therefore this work is complete.  Closing.
