### ISSUE TITLE
Faces 4.0: add new layout attribute value to h:selectManyCheckbox and h:selectOneRadio so it renders <ul> instead of <table>

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20835]
User Story: 
As a user of Open Liberty and the Faces 4.0 feature, I want to be able to use the h:selectManyCheckBox and h:selectOneRadio elements to render lists instead of tables using the new layout attribute.  

Spec issue: `https://github.com/jakartaee/faces/issues/1574`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html

Testing:
- [x] h:selectManyCheckBox without a layout attribute should output a table in `lineDirection`
- [x] h:selectManyCheckBox with `layout=list` should output a list
- [x] h:selectManyCheckBox with `layout=list` and `border=5` the boarder attribute should be ignored
- [x] h:selectManyCheckBox with `layout=pageDirection` should output a table
- [x] h:selectManyCheckBox with an invalid `layout=city` should default to `lineDirection`
- [x] h:selectOneRadio without a layout attribute should output a table in `lineDirection`
- [x] h:selectOneRadio with `layout=list` should output a list
- [x] h:selectOneRadio with `layout=list` and `border=5` the boarder attribute should be ignored
- [x] h:selectOneRadio with `layout=pageDirection` should output a table
- [x] h:selectOneRadio with an invalid `layout=city` should default to `lineDirection`

Test coverage from TCK: 
https://github.com/jakartaee/faces/tree/4.0.1/tck/faces40/selectManyCheckbox
