### ISSUE TITLE
Faces 4.0: h:inputFile accept="..." 

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20842]
User Story:
As a user of Open Liberty and the faces-4.0 feature, I want to create forms that restrict the type of file uploaded to a certain extension, format, or explicit name. 

Spec issue: `https://github.com/jakartaee/faces/issues/1556`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html

Test cases:
- [x]  A valid case-insensitive filename extension, starting with a period (".") character. For example: .jpg, .pdf, or .doc.
- [x]  A valid MIME type string, with no extensions.
  - [x]  The string audio/* meaning "any audio file".
  - [x]  The string video/* meaning "any video file".
  - [x]  The string image/* meaning "any image file".
- [x]  All of the above cases, but also with multiple input files.
