### ISSUE TITLE
Jakarta Connectors 2.1 deployment descriptor for EE 10

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#20996]
User story:
"As a user of Liberty, I want to deploy resource adapters that have a version 2.1 deployment descriptor so that my applications can connect to the backend systems that they support."

- [x] transform a FAT Suite to use connectors-2.1 and use the 2.1 deployment descriptor 
- [x] search our implementation for any static references to version 2.0 or earlier
- [ ] modify the transformer tool to transform existing deployment descriptors to version 2.1 when repeating tests
- [x] Update some JCA suites to repeat using connectors-2.1 in lite mode and repeat using earlier features in full mode.
