### ISSUE TITLE
Create microProfile-6.0 feature based on EE9 and add toleration for EE10 where possible

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#21968]
Create `microProfile-6.0` convenience feature containing...
- cdi-3.0
- jsonb-2.0
- jsonp-2.0
- restfulWS-3.0
- servlet-5.0
- mpCompatible-6.0
- mpConfig-3.0
- mpFaultTolerance-4.0
- mpHealth-4.0
- mpJwt-2.1
- mpOpenAPI-3.1
- mpMetrics-5.0
- mpRestClient-3.0
- mpTelemetry-1.0
(note that the EE9 features above will later be swapped to their EE10 versions)

mpCompatible-6.0 should depend on eeCompatible-10.0 but tolerate 9.0

mpConfig-3.0, mpFaultTolerance-4.0, mpHealth-4.0 and mpRestClient-3.0 should have toleration for EE10 added  (may not be possible yet).

mpJwt-2.1, mpOpenAPI-3.1, mpMetrics-5.0 and mpTelemetry-1.0 should be based on EE10 but tolerate EE9

mpMetrics-5.0 and mpJwt-2.1 do not actually exist yet but can be stubbed out using the old impls

Tasks
- [x] Create mpCompatible-6.0 feature #22024
- [x] Update test framework to allow repeats to be added for MP60 #22024
- [x] Make mpConfig-3.0 tolerate EE10 #22024
- [x] Make mpHealth-4.0 tolerate EE10 #22089
- [x] Make mpOpenAPI-3.1 be based on EE10 and tolerate EE9 #22088 
- [x] Make mpRestClient-3.0 tolerate EE10 #22141 
  - [x] Make mpTelemetry-1.0 be based on EE10 and tolerate EE9 #22190
- [x] Make mpFaultTolerance-4.0 tolerate EE10 #22063
  - [x] Enable mpRestClient-FT integration FATs
  - [x] Create mpMetrics-5.0 stub feature to avoid waiting for the real feature to be done
- [x] Make mpContextPropagation-1.3 tolerate EE10 #22109 
  - [x] Make GraphQL-2.0 tolerate EE10 https://github.com/OpenLiberty/open-liberty/pull/23053
- [x] Create microProfile-6.0 feature https://github.com/OpenLiberty/open-liberty/pull/22144
- [x] Run high level MP tests against microProfile-6.0 https://github.com/OpenLiberty/open-liberty/issues/22201
- [x] Ensure repeatAll in the test framework is correct

**Comment by Azquelt** [comment]
I ran into some problems when trying to update mpGraphQL-2.0 so I've opened a new issue for that instead: https://github.com/OpenLiberty/open-liberty/issues/22380

**Comment by Azquelt** [comment]
Thanks @jhanders34
