### ISSUE TITLE
Remove weaker ciphers from the HIGH cipher list in Liberty

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/open-liberty#24601]
## Description

Removing of the use of cipher suites with the RSA key exchange from the HIGH/default cipher list. No longer consider the securityLevels for ciphers as the medium and low categories no longer have any ciphers in them.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Documents

When available, add links to required feature documents. Use "N/A" to mark particular documents which are not required by the feature.

- Aha: Externally raised RFE ([Aha](https://cloud-platform.ideas.ibm.com/ideas/LIBERTY-I-101))
  - Link the RFE with this issue
- UFO: https://ibm.box.com/s/czj3x2p2ejoebk788ip9fa58islppjos
- FTS: https://github.com/OpenLiberty/open-liberty/issues/34200
- Beta Blog: https://github.com/OpenLiberty/open-liberty/issues/34374
- GA Blog: Link to GA Blog Post GH Issue

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Process Overview

- [Prioritization](#prioritization)
- [Design](#design)
- [Implementation](#implementation)
- [Legal and Translation](#legal-and-translation)
- [Beta](#beta)
- [GA](#ga)
  - [Focal Point Approvals](#focal-point-approvals-complete-by-feature-complete-date)
- [Other Deliverables](#other-deliverables)

### General Instructions

The process steps occur roughly in the order as presented. Process steps occasionally overlap.

Each process step has a number of tasks which must be completed or must be marked as not applicable ("N/A").

Unless otherwise indicated, the tasks are the responsibility of the Feature Owner or a Delegate of the Feature Owner.

If you need assistance, reach out to the [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect).

**Important: Labels are used to trigger particular steps and must be added as indicated.** 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Prioritization** (Complete Before Development Starts)

The ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) and area leads are responsible for prioritizing the features and determining which features are being actively worked on.

### **Prioritization**
- [ ] Feature added to the "New" column of the [Open Liberty project board](https://github.com/orgs/OpenLiberty/projects/2)
  - Epics can be added to the board in one of two ways:
    - From this issue, use the "Projects" section to select the appropriate project board.
    - From the appropriate project board click "Add card" and select your Feature Epic issue
- [ ] Priority assigned
  - Attend the Liberty Backlog Prioritization meeting

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Design** (Complete Before Development Starts)

Design preliminaries determine whether a formal design, which will be provided by an [Upcoming Feature Overview (UFO)](https://ibm.box.com/v/UFO-Template) document, must be created and reviewed.  A formal design is required if the feature requires any of the following: UI, Serviceability, SVT, Performance testing, or non-trivial documentation/ID.

### **Design Preliminaries**
- [x] UI requirements identified. (Owner and [UI focal point](https://github.com/orgs/OpenLiberty/teams/ui-approvers))
- [x] ID requirements identified. (Owner and [ID focal point](https://github.com/orgs/OpenLiberty/teams/id-approvers))
   - Refer to [Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty).
   - Feature Owner adds label `ID Required`, if non-trivial documentation needs to be created by the ID team.
   - ID adds label `ID Required - Trivial`, if no design will be performed and only trivial ID updates are needed.
- [x] Serviceability Requirements Identified. (Owner and [Serviceability focal point](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
- [x] SVT Requirements Identified. (Owner and [SVT focal point](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
- [x] Performance testing requirements identified. (Owner and [Performance focal point](https://github.com/orgs/OpenLiberty/teams/performance-approvers))

### **Design**
- [x] POC Design / UFO review scheduled.
  - Follow the instructions in the POC-Forum repo
- [x] POC Design / UFO review completed.
- [x] POC / UFO Review follow-ons completed.
- [x] POC Design / UFO approval requested.
  - Owner adds label `Design Approval Request`
- [x] Design / UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) adds label `Design Approved`
  - Add the public link to the UFO in Box to the [Documents](#documents) section.
  - The UFO must always accurately reflect the final implementation of the feature. Any changes must be first approved. Afterwards, update the UFO by creating a copy of the original approved slide(s) at the end of the deck and prepend "OLD" to the title(s). A single updated copy of the slide(s) should take the original's place, and have its title(s) prepended with "UPDATED".

### **No Design**
- [ ] No Design requested.
  - Owner adds label `No Design Approval Request`
- [ ] No Design / No UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - Approver adds label `No Design Approved`
- [ ] Feature / Capability stabilization or discontinuation or N/A
  - Owner adds label `Product Management Approval Request` and notifies [OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management)
  - Approver adds label `Product Management Approved` ([OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management))
  - Note: For stabilized, superseded, and discontinued feature/capability, skip the [Beta](#beta) section of the template (you may delete it).  Otherwise, proceed as normal.

### **FAT Documentation**
- [x] "Feature Test Summary" child task created
  - Use the [Feature Test Summary Template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=)
  - Add FTS issue link to the [Documents](#documents) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Implementation**

A feature must be [prioritized](https://github.com/orgs/OpenLiberty/projects/2) before any implementation work may begin to be delivered (inaccessible/no-ship).  However, a design focused approach should still be applied to features, and developers should think about the feature design prior to writing and delivering any code.  
Besides being prioritized, a feature must also be socialized (or No Design Approved) before any beta code may be delivered.  All new Liberty content must be inaccessible in our GA releases until it is [Feature Complete](#feature-complete) by either marking it `kind=noship` or [beta fencing](#beta-code) it.  
Code may not GA until this feature has obtained the "Design Approved" or "No Design Approved" label, along with all other tasks outlined in the [GA](#ga) section.

### **Feature Development Begins**
- [x] Add the `In Progress` label

## **Legal and Translation**

In order to avoid last minute blockers and significant disruptions to the feature, the **legal items need to be done as early in the feature process as possible**, either in design or as early into the development as possible.  Similarly, translation is to be done concurrently with development.  Both **MUST** be completed before Beta or GA is requested.

### **Legal** (Complete before Feature Complete Date)
- [x] Changed or new open source libraries are cleared and approved, or N/A. (Legal Release Services/Cass Tucker/Release PM).
- [x] Licenses and Certificates of Originality (COOs) are updated, or N/A

### **Translation** (Complete 1 week before Feature Complete Date)
- [x] PII updates are merged, or N/A. Note timing with translation shipments.

### **Innovation** (Complete 1 week before Feature Complete Date)
- [x] Consider whether any aspects of the feature may be patentable. If any identified, disclosures have been submitted.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Beta**

In order to facilitate early feedback from users, all new features and functionality should first be released as part of a beta release.

### **Beta Code**
- [x] Beta fence the functionality
  - `kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`
- [x] Beta development complete and feature ready for inclusion in a beta release
  - Add label `target:beta` and the appropriate `target:YY00X-beta` (where YY00X is the targeted beta version).
- [ ] Feature delivered into beta
  - ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager)) adds label `release:YY00X-beta` (where YY00X is the first beta version that included the functionality).

### **Beta Blog** (Complete 1.5 weeks before beta eGA)
- [x] Beta blog issue created and populated using the [Open Liberty BETA blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the beta blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [beta release blog post](https://openliberty.io/blog/?search=beta&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **GA**

A feature is ready to GA after it is Feature Complete and has obtained all necessary Focal Point Approvals. 

### **Feature Complete**
- [ ] Feature implementation and tests completed.
  - [ ] All PRs are merged.
  - [ ] All epic and child issues are closed.
  - [ ] All stop ship issues are completed.
- [x] Legal: all necessary approvals granted.
- [ ] Translation: All messages translated or sent for translation for upcoming release 
- [ ] GA development complete and feature ready for inclusion in a GA release
  - Add label `target:ga` and the appropriate `target:YY00X` (where YY00X is the targeted GA version).
  - Inclusion in a release requires the completion of all Focal Point Approvals.

### **Focal Point Approvals** (Complete by Feature Complete Date)

These occur only after GA of this feature is requested (by adding a `target:ga` label).  GA of this feature may not occur until all approvals are obtained.

### **All Features**
- [x] **APIs/Externals** Externals have been reviewed or N/A.  ([OpenLiberty/externals-approvers](https://github.com/orgs/OpenLiberty/teams/externals-approvers))
  - Approver adds label `focalApproved:externals` 
- [x] **Demo** Demo is scheduled for an upcoming EOI or N/A. ([OpenLiberty/demo-approvers](https://github.com/orgs/OpenLiberty/teams/demo-approvers))
  - Add comment `@OpenLiberty/demo-approvers Demo scheduled for EOI [Iteration Number]` to this issue.
  - Approver adds label `focalApproved:demo`.
- [ ] **FAT** All Tests complete and running successfully in SOE or N/A. ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers))
  - Approver adds label `focalApproved:fat`.
- [x] **Globalization** Translation and TVT are complete or N/A. ([OpenLiberty/globalization-approvers](https://github.com/orgs/OpenLiberty/teams/globalization-approvers))
  - Approver adds label `focalApproved:globalization`.

### **Design Approved Features**
- [x] **Accessibility** Accessibility testing completed or N/A. ([OpenLiberty/accessibility-approvers](https://github.com/orgs/OpenLiberty/teams/accessibility-approvers))
  - Approver adds label `focalApproved:accessibility`.
- [ ] **ID** Documentation is complete or N/A. ([OpenLiberty/id-approvers](https://github.com/orgs/OpenLiberty/teams/id-approvers))
  - Approver adds label `focalApproved:id`.
  - > **_NOTE:_**  If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **Performance** Performance testing is complete or N/A. ([OpenLiberty/performance-approvers](https://github.com/orgs/OpenLiberty/teams/performance-approvers))
  - Approver adds label `focalApproved:performance`.
- [x] **Serviceability** Serviceability has been addressed or N/A. ([OpenLiberty/serviceability-approvers](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
  - Approver adds label `focalApproved:sve`.
- [x] **STE** Skills Transfer Education chart deck is complete or N/A. ([OpenLiberty/ste-approvers](https://github.com/orgs/OpenLiberty/teams/ste-approvers))
  - Approver adds label `focalApproved:ste`.
- [ ] **SVT** System Verification Test is complete or N/A. ([OpenLiberty/svt-approvers](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
  - Approver adds label `focalApproved:svt`.

### **Remove Beta Fencing** (Complete by Feature Complete Date)
- [ ] Beta guards are removed, or N/A
  - Only after all necessary Focal Point Approvals have been granted.

### **GA Blog** (Complete by Feature Complete Date)
- [ ] GA Blog issue created and populated using the [Open Liberty GA release blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the GA Blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [release blog post](https://openliberty.io/blog/?search=release&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

### **Post GA**
- [ ] Replace `target:YY00X` label with the appropriate `release:YY00X`. ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager))

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Other Deliverables**

- [ ] **Standalone Feature Blog Post** A blog post specifically about your feature or N/A.  ([OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect))
  - This should be strongly considered for larger or more prominent features.
  - Follow [instructions](https://github.com/OpenLiberty/blogs/tree/draft#writing-and-publishing-blog-posts-on-the-openlibertyio-blog) in the blogs repo.
- [ ] **OL Guides** OL Guides assessment is complete or N/A. ([OpenLiberty/guide-assessment](https://github.com/orgs/OpenLiberty/teams/guide-assessment/members))
- [ ] **Dev Experience** Developer Experience & Tools work is complete or N/A. ([OpenLiberty/dev-experience-assessment](https://github.com/orgs/OpenLiberty/teams/dev-experience-assessment/members))
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by acdemyers** [comment]
The tWAS Epic is https://github.ibm.com/websphere/WS-CD-Open/issues/28213.  The POC approvals can be found there.

**Comment by acdemyers** [comment]
UFO link: https://ibm.box.com/s/8yb875q2mrhlr78qt0pm9qn0n92n789i

**Comment by ayoho** [comment]
POC review notes:

Action: Take out references to "STRONG" since that's only used on the tWAS console; Liberty doesn't use that term.

Slide 15

How do people define a custom list?
- If enabledCiphers has anything in it, we use that over securityLevel.
- Typically we'll set securityLevel="CUSTOM", but that's not actually required. Ideally the Liberty documentation should make that clear.

Should securityLevel remain? Be removed?
Action: Remove it. There will be work to do to tell builds that it's ok that it's being removed, but it'll be better to remove it rather than mark it internal.

Slide 27

Consider whether relevant NLS message explanations/user actions could be improved to suggest what customers might be able to do about "no cipher suites in common" error

**Comment by acdemyers** [comment]
UFO updated and uploaded to https://ibm.box.com/s/8yb875q2mrhlr78qt0pm9qn0n92n789i

**Comment by ayoho** [comment]
I've added the `pause_review` label to this feature since Alaine is no longer working on it. As of right now I know of no one who has picked up this work or has bandwidth for it.

**Comment by ayoho** [comment]
@ljforet FYI

**Comment by malincoln** [comment]
removing in progress label since this one has been paused.

**Comment by jacobwdv** [comment]
notes for FTS: be sure to test with FIPS enabled. Compare handshake ciphers before and after our change to be certain that FIPS compliant algorithms continue to be the only ones considered.

**Comment by follis** [comment]
Comments from the UFO review (February 25, 2026):
- Beta - Consider beta guards for the configuration changes to keep the metadata from showing up early
- Tests - Consider providing some more detail here (concerns raised about 'negative' tests)
- Chart 11 - Consider updating to be clearer about how it all works.

**Comment by jacobwdv** [comment]
UFO has been updated: https://ibm.box.com/s/czj3x2p2ejoebk788ip9fa58islppjos

**Comment by ayoho** [comment]
## Meeting Summary - POC Forum, February 25, 2026

Presenter: Jake de Vos | Facilitator: David Follis (POC meeting host)

---

### Liberty — `+`/`-` Filter Syntax for `enabledCiphers`

**Beta scope debate (Jared Anderson, Jake de Vos)**
Jared raised the question of whether the new `+`/`-` filter syntax should be beta-gated. Jake's initial instinct was that it wasn't necessary since it's purely additive, but Jared pushed back: the `securityLevel` metatype removal *can't* be beta-gated (metatype changes don't support that), so Jared suggested beta-gating the new filter syntax instead, leaving the security level attribute in place during the beta period. Jake agreed this was a reasonable compromise.

**Mixing static and dynamic syntax (Jared Anderson)**
Jared asked what happens if a customer mixes static cipher names with `+`/`-` prefixed entries in the same `enabledCiphers` attribute. Jake confirmed this is an error condition — the server logs an error and falls back to JDK defaults. Jared noted this is a meaningful behavior change customers need to be aware of.

**Wildcard on `+` (add) side (Jared Anderson)**
Jared asked whether wildcards are supported for adding ciphers (e.g., `+TLS_RSA*`), not just for removing them. Jake said wildcards are only supported on the minus (remove) side, not the plus (add) side, because adding an unknown cipher that the JDK doesn't support would silently do nothing and be confusing. Jared accepted this but noted it should be clearly documented.

**Modeling after classloader syntax (Jared Anderson)**
Jared pointed out that the `+`/`-` syntax is modeled after the existing classloader attribute pattern in Liberty, which the team agreed was a good precedent to follow for consistency.

---

### Migration Impact (tWAS → Liberty)

**Alex Butcher — version mismatch risk**
Alex raised a concern about the tWAS-to-Liberty migration path: since the new `+`/`-` syntax is being added to the *existing* `enabledCiphers` attribute (not a new attribute), the migration tooling would blindly copy the value over to Liberty's `server.xml`. If the target Liberty version doesn't yet support the new syntax, Liberty would fail to start. Jake acknowledged this was a real risk and said he hadn't tested it.

**Chuck Bridgham — minimum Liberty version guard**
Chuck noted that the migration tooling does have a concept of a minimum Liberty version. When support for the new syntax is released, the minimum Liberty version in the migration driver should be bumped accordingly, so customers can't accidentally migrate to an older Liberty that doesn't understand the syntax. Alex agreed this would mitigate the risk, though noted there's still a window where a customer updates tWAS but hasn't updated their migration driver.

**Jake de Vos — action item**
Jake committed to updating the migration impact slide to explicitly call out the `enabledCiphers` version mismatch scenario and the need to bump the minimum Liberty version in the migration tooling.

**Jared Anderson — closing note**
Jared noted that the migration impact slide was clearly going to be important and the discussion was worth having.

**Comment by NottyCode** [comment]
Slide 11 flow chart is confusing because the first decision point is whether `enabledCiphers` is set, but if you answer no I think the next question is whether `enabledCiphers` is set using the new +/- syntax. This is confusing and I think the diagram needs to be updated to remove any confusion.

Wildcarding is described in the ToBe section, but is then never mentioned again. I would expect it to be described on slide 16 where the configuration is described as a part of externals design section, rather than the ToBe section.

**Comment by jacobwdv** [comment]
@NottyCode suggested updates are complete: https://ibm.box.com/s/czj3x2p2ejoebk788ip9fa58islppjos

**Comment by jacobwdv** [comment]
Docs issue updated with 26.0.0.5 target: https://github.com/OpenLiberty/docs/issues/8186

**Comment by jacobwdv** [comment]
@OpenLiberty/demo-approvers Demo scheduled for EOI  26.06 - 31st March

**Comment by tngiang73** [comment]
WASSEC is good with the STE slides. Hence, approving the STE.

**Comment by pgunapal** [comment]
@rangaran @jacobwdv 
**Serviceability Approval Comment** - Please answer the following questions for Serviceability approval:

1.  Have the most likely customer‑facing problem scenarios identified in the Serviceability section of the UFO been addressed in the implementation?

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. IBM Support, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid Support Cases for any problems customers are likely to encounter, or that IBM Support should be able to quickly address those problems without need to engage SMEs?

3.  Which IBM Support / SME queues will handle Support Cases for this feature?  Ensure they are present in the contact reference file and in the Queue Contact Summary, and that the respective IBM Support/SME teams know they are supporting it.  Ask Prashanth Gunapalasingam if you need links or more info.

4.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?

**Comment by rangaran** [comment]
@pgunapal 
1. Yes, slide [28](https://ibm.ent.box.com/file/2122990598073?s=czj3x2p2ejoebk788ip9fa58islppjos) of the UFO goes over this
2.
   a. Please see the positive and negative tests outlined in the FTS: https://github.com/OpenLiberty/open-liberty/issues/34200
   b. @Morgan-Li 
   c. Yes. Morgan brought up the following points and this is the related reasoning I gave:
     - Why do we have two messages for security level being used in the server.xml: One is for securityLevel, HIGH and the other is for securityLevel, LOW and MEDIUM. We want to additionally warn people for weak ciphers to discourage them from using them.
     - Why do we not support +TLS_AES* as in wildcards with '+': This is because that would involve an implicit removal of algorithms from the effective JDK list which would in turn mean different from our intended use. Adding another operation does not make sense at this time because that would mean we would be supporting regex which goes against the precedent we are following from ClassLoaders. 
    - Why can we not use just '*' for enabledCiphers: It is because without a prefix the operation/filtering criteria is unknown.
 3. WAS L3: Core Security
 4. No

**Comment by CassTucker** [comment]
@jacobwdv I see your comment removed "26.0.0.5-beta" tag but I see it's still there. need to know if this is still an aha issue for 26.0.0.5-beta OR 26.0.0.5.  Let me know asap, thanks!

**Comment by jacobwdv** [comment]
@CassTucker  - This will go into 26.0.0.5 beta and then release in 26.0.0.5

**Comment by jacobwdv** [comment]
I removed the tag assuming that was the right move but maybe it wasn't, adding it back in so it will be tracked for the beta.

**Comment by chirp1** [comment]
No doc updates for writers to do in the following issue: https://github.com/OpenLiberty/docs/issues/8186
Links to update are for generated doc only and are done by development.
Removed ID required and focalapproved:id.
