### ISSUE TITLE
The ddlgen utility should show DDL for Jakarta Data tables

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#24916]
User Story:
"As a database administrator, I want to run the ddlgen tool to generate DDL for Jakarta Data entities so that I can ensure the correct tables and constraints are set up in the database."

https://www.ibm.com/docs/el/was-liberty/base?topic=line-running-ddlgen-utility

see example of DDLGenerationParticipant in com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.generate(Writer)

**Comment by tkburroughs** [comment]
The initial implementation has been delivered under PR #29266.  The following concerns need to be investigated further before closing out this story:

- [x] I had just picked _repository as a first guess that was consistent with PersistentExecutor and Batch; before I realized there may be more than one per file; do we want to change that?
- [x] name of the files in general; I tried to be consistent with PersistentExecutor and Batch, but we may want to consider if there are better options, though I think the names of most files currently are nicely tied to identifying the DatabaseStore, which I think is good.
- [x] name of file for default databasestore; it does not include the `databaseStore[xxx]` wording like the others, but that is consistent with documentation I found for PersistentExecutor.  It would be trivial to change so it is consistent with the other files names.
- [x] Are we concerned about the order of the statements in each file.  Because everything is so asynchronous, I have found the order can switch when multiple EMBuilders are mapped to the same file name.  I don't think the order should matter.... and I did ensure the test verification is not order dependent.
- [x] It might be possible that one DDL file ends up with CREATE TABLE statements for the same table.  I didn't consider this when developing... until I was finalizing testing.  All my new repositories added a new Entity/new table.... but then I found that other parts of the test declare separate repositories that use the same Entity. Currently those all end up in different files because they specify the DatabaseStore differently.... so we need to consider additional testing to see if there is a way to get duplicates in a single file.  If so, we may need to add a filter in the DDLGenerationWriter that detects that and throws away the duplicate. Or if very unlikely, we document when this might occur so the rare customer is not surprised when they get a table already exists error.
- [x] Also... more testing around "java:global" and using direct JNDI names.  Currently, for global names, all applications using the same global name will map to the same file... which is one of the reasons why I updated persistence service to support multiple components mapping to the same file, so that Jakarta Data doesn't have to keep track of this and perform additional cleanup during app uninstall.   However, we may want to consider splitting each application to a different file?  If a customer has all of their applications using the same DatabaseStore, would they want all create tables in the same file... or would they want a separate file per application?
- [x] Translate exception text and error, and add a test that demonstrates an error provides meaningful help.

But having the initial implementation delivered will make it easier for everyone begin trying out and seeing how it works with other test scenarios, including database rotations... and come up with answers to my above concerns.  It really shouldn't fail to handle any scenarios... it is now about how end user friendly it is.

**Comment by tkburroughs** [comment]
All work for ddlgen complete; closing.
