### ISSUE TITLE
Jakarta EE 11:  Support Jakarta Faces 4.1 and Faces Container 4.1

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#25089]
## Description

Implement the Jakarta Faces 4.1 specification

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Documents

When available, add links to required feature documents. Use "N/A" to mark particular documents which are not required by the feature.

- Externally raised requests for enhancements: 
  - [Aha](https://cloud-platform.ideas.aha.io/): Link to the Aha idea (also add a link to this issue in the Aha idea)
    - Feature owner adds label `Aha idea`
  - [Open Liberty Feature Request](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=): Link to the OL GH issue (also add a link to this issue in the Feature Request GH issue)
    - Feature owner adds label `Requested feature`
- UFO: Link to [Upcoming Feature Overview](https://ibm.box.com/v/UFO-Template) document: [Faces 4.1 UFO](https://ibm.ent.box.com/file/1625509266116?s=g9wyqsalt4diudl3389wde3h639u1d1z)
  - [Upload the feature UFO to Box](https://ibm.ent.box.com/folder/52716090328) and set the link to be publicly accessible, with a long expiration (10 years)
    - Click "Share" > select "People with link" > click "Link Settings" > under "Link Expiration" select "Disable Shared Link on" > set an expiration date ~10 years into the future
    - If you lack permissions, contact [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect)
    - The initial Part one UFO was for Faces 5.0, since then EE11 was changed to Faces 4.1. The original UFO was: https://ibm.box.com/s/5qsecwfw52h4f7avlvg38ktmbu4fr1ax
- FTS: [Faces 4.1 Feature Test Summary](https://github.com/OpenLiberty/open-liberty/issues/27130)
- Beta Blog: `faces-4.1` -> https://github.com/OpenLiberty/open-liberty/issues/28603 `facesContainer-4.1` -> https://github.com/OpenLiberty/open-liberty/issues/28770
- GA Blog: Link to GA Blog Post GH Issue

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Process Overview

- [Prioritization](#prioritization)
- [Design](#design)
- [Implementation](#implementation)
- [Legal and Translation](#legal-and-translation)
- [Beta](#beta)
- [GA](#ga)
  - [Focal Point Approvals](#focal-point-approvals-complete-by-feature-complete-date)
- [Other Deliverables](#other-deliverables)

### General Instructions

The process steps occur roughly in the order as presented. Process steps occasionally overlap.

Each process step has a number of tasks which must be completed or must be marked as not applicable ("N/A").

Unless otherwise indicated, the tasks are the responsibility of the Feature Owner or a Delegate of the Feature Owner.

If you need assistance, reach out to the [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect).

**Important: Labels are used to trigger particular steps and must be added as indicated.** 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Prioritization** (Complete Before Development Starts)

The ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) and area leads are responsible for prioritizing the features and determining which features are being actively worked on.

### **Prioritization**
- [x] Feature added to the "New" column of the [Open Liberty project board](https://github.com/orgs/OpenLiberty/projects/2)
  - Epics can be added to the board in one of two ways:
    - From this issue, use the "Projects" section to select the appropriate project board.
    - From the appropriate project board click "Add card" and select your Feature Epic issue
- [x] Priority assigned
  - Attend the Liberty Backlog Prioritization meeting

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Design** (Complete Before Development Starts)

Design preliminaries determine whether a formal design, which will be provided by an [Upcoming Feature Overview (UFO)](https://ibm.box.com/v/UFO-Template) document, must be created and reviewed.  A formal design is required if the feature requires any of the following: UI, Serviceability, SVT, Performance testing, or non-trivial documentation/ID.  Furthermore, each identified item places a blocking requirement on another team so it must be identified early in the process.  The feature owner may check-off the item if they know it doesn't apply, but otherwise they should work with the focal point to determine what work, if any, will be necessary and make them aware of it.

### **Design Preliminaries**
- [x] UI requirements identified, or N/A. (Feature owner and [UI focal point](https://github.com/orgs/OpenLiberty/teams/ui-approvers))
- [x] Accessibility requirements identified, or N/A. (Feature owner and [Accessibility focal point](https://github.com/orgs/OpenLiberty/teams/accessibility-approvers))
- [x] ID requirements identified, or N/A. (Feature owner and [ID focal point](https://github.com/orgs/OpenLiberty/teams/id-approvers))
   - Refer to [Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty).
   - Feature Owner adds label `ID Required`, if non-trivial documentation needs to be created by the ID team.
   - ID adds label `ID Required - Trivial`, if no design will be performed and only trivial ID updates are needed.
- [x] Serviceability requirements identified, or N/A. (Feature owner and [Serviceability focal point](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
- [x] SVT requirements identified, or N/A. (Feature owner and [SVT focal point](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
- [x] Performance testing requirements identified, or N/A. (Feature owner and [Performance focal point](https://github.com/orgs/OpenLiberty/teams/performance-approvers))

### **Design**
- [x] POC Design / UFO review requested.
  - Feature owner adds label `Design Review Request`
- [x] POC Design / UFO review scheduled.
  - Follow the instructions in POC-Forum repo
- [x] POC Design / UFO review completed.
- [x] POC / UFO Review follow-ons completed.
- [x] POC Design / UFO approval requested.
  - Feature owner adds label `Design Approval Request`
- [x] Design / UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) adds label `Design Approved`
  - Add the public link to the UFO in Box to the [Documents](#documents) section.
  - The UFO must always accurately reflect the final implementation of the feature. Any changes must be first approved. Afterwards, update the UFO by creating a copy of the original approved slide(s) at the end of the deck and prepend "OLD" to the title(s). A single updated copy of the slide(s) should take the original's place, and have its title(s) prepended with "UPDATED".

### **No Design**
- [ ] No Design requested.
  - Feature owner adds label `No Design Approval Request`
- [ ] No Design / No UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - Approver adds label `No Design Approved`
- [ ] Feature / Capability stabilization or discontinuation or N/A
  - Feature owner adds label `Product Management Approval Request` and notifies [OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management)
  - Approver adds label `Product Management Approved` ([OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management))
  - Note: For stabilized, superseded, and discontinued feature/capability, skip the [Beta](#beta) section of the template (you may delete it).  Otherwise, proceed as normal.

### **FAT Documentation**
- [x] "Feature Test Summary" child task created
  - Use the [Feature Test Summary Template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=)
  - Add FTS issue link to the [Documents](#documents) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Implementation**

A feature must be [prioritized](https://github.com/orgs/OpenLiberty/projects/2) before any implementation work may begin to be delivered (inaccessible/no-ship).  However, a design focused approach should still be applied to features, and developers should think about the feature design prior to writing and delivering any code.  
Besides being prioritized, a feature must also be socialized (or No Design Approved) before any beta code may be delivered.  All new Liberty content must be inaccessible in our GA releases until it is [Feature Complete](#feature-complete) by either marking it `kind=noship` or [beta fencing](#beta-code) it.  
Code may not GA until this feature has obtained the `Design Approved` or `No Design Approved` label, along with all other tasks outlined in the [GA](#ga) section.

### **Feature Development Begins**
- [x] Add the `In Progress` label

## **Legal and Translation**

In order to avoid last minute blockers and significant disruptions to the feature, the **legal items need to be done as early in the feature process as possible**, either in design or as early into the development as possible.  Similarly, translation is to be done concurrently with development.  Both **MUST** be completed before Beta or GA is requested.

### **Legal** (Complete before Feature Complete Date)
- [x] Changed or new open source libraries are cleared and approved, or N/A. (Legal Release Services/Cass Tucker/Release PM).

### **Innovation** (Complete 1 week before Feature Complete Date)
- [x] Consider whether any aspects of the feature may be patentable. If any identified, disclosures have been submitted.

### **Translation** (Complete by Feature Complete Date)
- [x] PII (Program Integrated Information) updates are merged (i.e. all English strings due for translation have been delivered), or N/A.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Beta**

In order to facilitate early feedback from users, all new features and functionality should first be released as part of a beta release.

### **Beta Code**
- [x] [Beta fence](https://github.com/OpenLiberty/open-liberty/wiki/Beta-Fencing) the functionality
  - E.g. `kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`
- [x] Beta development complete and feature ready for inclusion in a beta release
  - Add label `target:beta` and the appropriate `target:YY00X-beta` (where YY00X is the targeted beta version).
- [x] Feature delivered into beta
  - ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager)) adds label `release:YY00X-beta` (where YY00X is the first beta version that included the functionality).

### **Beta Blog** (Complete by beta eGA)
- [x] Beta blog issue created and populated using the [Open Liberty BETA blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the beta blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [beta release blog post](https://openliberty.io/blog/?search=beta&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **GA**

A feature is ready to GA after it is Feature Complete and has obtained all necessary Focal Point Approvals. 

### **Feature Complete**
- [x] Feature implementation and tests completed.
  - [x] All PRs are merged.
  - [x] All related/child issues are closed.
  - [x] All stop ship issues are completed.
- [x] Legal: all necessary approvals granted.
- [x] Translation: Feature may only proceed to GA if it has either `Translation - Complete` or `Translation - Missing` label
  - If all translation has been delivered to `release` branch, feature owner adds label `Translation - Complete`.
  - If missing translation does not cause a break in functionality, nor a security or production outage risk, feature owner adds label `Translation - Missing`.
    - Once all missing translations are delivered, the `Translation - Missing` label is replaced with `Translation - Complete`.
  - If missing translation could cause a break in functionality or a security or production outage risk, feature owner adds the `Translation - Blocked` label.
    - Featues with `Translation - Blocked` may **NOT** proceed to GA until the label has been replaced with either `Translation - Missing` or `Translation - Complete`.
  - For further guidance, contact [Globalization focal point](https://github.com/orgs/OpenLiberty/teams/globalization-approvers) or the [Release Architect](https://github.com/orgs/OpenLiberty/teams/release-architect).
- [x] GA development complete and feature ready for inclusion in a GA release
  - Add label `target:ga` and the appropriate `target:YY00X` (where YY00X is the targeted GA version).
  - Inclusion in a release requires the completion of all Focal Point Approvals.

### **Focal Point Approvals** (Complete by Feature Complete Date)

These occur only after GA of this feature is requested (by adding a `target:ga` label).  GA of this feature may not occur until all approvals are obtained.

### **All Features**
- [x] **APIs/Externals** - Externals have been reviewed or N/A.  ([OpenLiberty/externals-approvers](https://github.com/orgs/OpenLiberty/teams/externals-approvers))
  - Approver adds label `focalApproved:externals` 
- [x] **Demo** - Demo is scheduled for an upcoming EOI or N/A. ([OpenLiberty/demo-approvers](https://github.com/orgs/OpenLiberty/teams/demo-approvers))
  - Add comment `@OpenLiberty/demo-approvers Demo scheduled for EOI [Iteration Number]` to this issue.
  - Approver adds label `focalApproved:demo`.
- [x] **FAT** - All Tests complete and running successfully in SOE or N/A. ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers))
  - Approver adds label `focalApproved:fat`.

### **Design Approved Features**
- [x] **ID** - Documentation is complete or N/A. ([OpenLiberty/id-approvers](https://github.com/orgs/OpenLiberty/teams/id-approvers))
  - Approver adds label `focalApproved:id`.
  - > **_NOTE:_**  If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [x] **InstantOn** - InstantOn capable or N/A. ([OpenLiberty/instantOn-approvers](https://github.com/orgs/OpenLiberty/teams/instantOn-approvers))
  - Approver adds label `focalApproved:instantOn`.
- [x] **Performance** - Performance testing is complete or N/A. ([OpenLiberty/performance-approvers](https://github.com/orgs/OpenLiberty/teams/performance-approvers))
  - Approver adds label `focalApproved:performance`.
- [x] **Serviceability** - Serviceability has been addressed or N/A. ([OpenLiberty/serviceability-approvers](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
  - Approver adds label `focalApproved:sve`.
- [x] **STE** - Skills Transfer Education chart deck is complete or N/A. ([OpenLiberty/ste-approvers](https://github.com/orgs/OpenLiberty/teams/ste-approvers))
  - Approver adds label `focalApproved:ste`.
- [x] **SVT** - System Verification Test is complete or N/A. ([OpenLiberty/svt-approvers](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
  - Approver adds label `focalApproved:svt`.

### **Remove Beta Fencing** (Complete by Feature Complete Date)
- [ ] Beta guards are removed, or N/A
  - Only after all necessary Focal Point Approvals have been granted.

### **GA Blog** (Complete by Friday after GM)
- [ ] GA Blog issue created and populated using the [Open Liberty GA release blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the GA Blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [release blog post](https://openliberty.io/blog/?search=release&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

### **Post GM** (Complete before GA)
- [ ] After confirming this feature has been included in the GM driver, feature owner closes this issue.

### **Post GA**
- [ ] Remove the `target:ga` and `target:YY00X` labels, and add the appropriate `release:YY00X`. ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager))

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Other Deliverables**

- [ ] **Standalone Feature Blog Post** - A blog post specifically about your feature or N/A.  (Feature owner and [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect))
  - This should be strongly considered for larger or more prominent features.
  - Follow [instructions](https://github.com/OpenLiberty/blogs/tree/draft#writing-and-publishing-blog-posts-on-the-openlibertyio-blog) in the blogs repo.
- [ ] **OL Guides** - OL Guides assessment is complete or N/A. ([OpenLiberty/guide-assessment](https://github.com/orgs/OpenLiberty/teams/guide-assessment/members))
- [ ] **Dev Experience** - Developer Experience & Tools work is complete or N/A. ([OpenLiberty/dev-experience-assessment](https://github.com/orgs/OpenLiberty/teams/dev-experience-assessment/members))
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by tjwatson** [comment]
UFO review call part 1

Slide 3
 - [ ] How does this relates to Jakarta MVC?
  - **Volodymyr** (9/6/23): 
    -  Per the [Jakarta MVC spec](https://jakarta.ee/specifications/mvc/2.1/jakarta-mvc-spec-2.1#introduction): 
    _The API defined by this specification falls into the action-based category and is, therefore, not intended to be a replacement for component-based frameworks such as Jakarta Server Faces [1], but simply a different approach to building Web applications on the Jakarta EE platform._
    -  Jakarta MVC looks to mostly requests are mapped to actions while Faces is more advanced / different approach via components. 
    -  Arjan also wrote an article here with examples that I found useful: `https://arjan-tijms.omnifaces.org/2014/11/jsf-and-mvc-10-comparison-in-code.html` 
     - Also worth noting that Jakarta MVC applications can support Facelets if the FacesServlet mappings are defined, but Jakarta Server Pages are supported by default. 
 
Slide 8
 - [ ] 5032 issue is Mojarra is that a spec issue?  Yes a TCK update that we expect to fail with MyFaces.
 - **Volodymyr** ( 9/06/23):
   - The issue can be found here: `https://github.com/eclipse-ee4j/mojarra/issues/5032`. I will need to test via MyFaces. 
   
Slide 10
- [ ] UUIDConverter - is this a general purpose utility or only useful in the faces context?  It seems specific to Faces
- [ ] Does our MyFaces implementation get the body of this utility class from the specification project or does it have its own implementation?
 - **Volodymyr** ( 9/06/23):
   -   Correct. The UUIDConverter would implement  the [jakarta.faces.convert.Converter](https://jakarta.ee/specifications/platform/10/apidocs/jakarta/faces/convert/package-summary). MyFaces provides it's own implementation and can be found [here](https://github.com/apache/myfaces/blob/f003bb4794c88ec91b27a28b8a4e34b6fd53edbd/api/src/main/java/jakarta/faces/convert/UUIDConverter.java).

Slide 12
- [ ] Split implementation from source for 5.0 release.  Is this prioritized and going to make it?
 - **Volodymyr** ( 9/06/23)
   - I hope so, but we'll see. Issue can be found here: `https://github.com/jakartaee/faces/issues/1839`.  Arjan looks to prioritize it. 

Slide 13
- [ ] Specify if this applies to MyFaces specific stuff or both 
 - **Volodymyr** ( 9/06/23)
   - Should mention it's specific for MyFaces. Link JIRAs, too? 

Slide 20
- [ ] Some other items have been deprecated and need listed here
- [ ] Add details to faces spec issue with arguments for removal exception to spec committee.

Slide 23
- [ ] Can third-party impl of faces be configured as a library, or must be packaged in application?
  - **Volodymyr** ( 9/06/23)
    - Must be packaged within the application. 
    - The liberty documentation for jsfContainer-2.2 specifies that `The program does not support packaging the JSF API and implementation in a shared library.` 
      - https://www.ibm.com/docs/en/was-liberty/base?topic=22-configuring-third-party-javaserver-faces-implementations

Slide 28
- [ ] Other runtimes use MyFaces?  Good to list here also.
  - **Volodymyr** ( 9/06/23)
   - By default? I think only TomEE and Open Liberty.  However, other application servers can still use MyFaces 
     - if it's packaged within the application. For example, I have no trouble running MyFaces-based applications on Tomcat (no default implementation provided). 
     - or if the default implementation is changed. For example, in WildFly: `https://docs.jboss.org/author/display/WFLY/JSF%20Configuration.html`

**Comment by pnicolucci** [comment]
We are targeting `24008-beta` for the `facesContainer-4.1` feature.

**Comment by pnicolucci** [comment]
The `faces-4.1` feature was delivered in the `24007-beta`

**Comment by tevans78** [comment]
UFO Review comments:

- Slide 12 - Is the github right for both API and TCK? Verify if this is correct repo/branch.
- Slide 14 - Not completely clear which packages are in which bundle
- Slide 15 - Change Optional to Additional for “facesContainer-4.1” feature
- Slide 18 - Clarify which packages are API vs ThirdParty and why … list all out rather than just additions
- Slide 21 - Clarify how libraries may be packaged in apps & defined in server.xml. Check if shared libraries can be used via application classloader element? Can EAR/lib directory be used?
  - Consider if a separate feature should be opened to support shared libs?
- Slide 23 - Clarify that default value of PARTIAL_STATE_SAVING is true and is no longer required as an option

**Comment by pnicolucci** [comment]
@LifeIsGood524 I added the `release:24008-beta` for the `facesContainer-4.1` feature and `release:24007-beta` for the `faces-4.1` feature.

**Comment by volosied** [comment]
Updated the UFO, but I still need to look into Slide 21 comments regarding shared libraries.  Documentation said it won't work, but I can try to investigate it a bit more on why / what errors we encounter.  I can also test EAR/lib.

**Comment by volosied** [comment]
I created a shared library, but the FacesServlet would not initialized.   The app has access to the the JSF packages (tested via simple imports), but, for some reason, it cannot use it. No customers are requesting this feature (shared library support for jsf container features), so I don't think it's worth pursing as of now.

Looking into ears next. 

I placed the jsf libraries (and dependencies) under `<app>.ear/lib` and Faces initialized fine. App ran without problems.


It looks like just the shared libraries approach doesn't work.  I'm assuming something with the app / server class loading separation is causing a disconnect?

**Comment by pnicolucci** [comment]
Translations for Faces 4.1 / Faces Container 4.1:

1) Faces 4.1 feature translations: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.1/resources/l10n
2) Faces Container 4.1 feature translations: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.1/resources/l10n

No other new translations for Faces 4.1 / Faces Container 4.1

**Comment by pgunapal** [comment]
@pnicolucci 
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?

> We are using an opensource  API and implementation, and it's forked off the 4.0 implementation. Existing error handling and messages have not changed. The existing 4.1 error-handling via the implementation ought to be enough for clients. Any other issues will nee a SF or PMR.

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. IBM Support, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that IBM Support should be able to quickly address those problems without need to engage SMEs?

>  I demonstrated to Varun and Thanh from L2, as well as Phu from my team. The main problem path demonstrated were
>  - UUID Converter
>  - Composite Extension
>  - Refresh periods for the development project stage. 
> The current serviceability is enough, and I've updated the STE slide to call our errors with Faces converters.

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature?
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that IBM Support should be able to quickly address those problems without need to engage SMEs?

> Reached out to Jag from SVT. Regression testing with tolerance scenarios (i.e existing tests against faces-4.1) have been completed. New feature development will begin in 4Q2025. 

4.  Which IBM Support / SME queues will handle PMRs for this feature?  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective IBM Support/SME teams know they are supporting it.  Ask Prashanth Gunapalasingam if you need links or more info.

> The contacts would be WAS L3: JSF team. I've updated the QueueContactPage.

5.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?

> No new metrics.

**Comment by pnicolucci** [comment]
ID issue : https://github.com/OpenLiberty/docs/issues/7969

**Comment by chirp1** [comment]
From Ram, he completed the updates for the 4.1 vs 4.0 Faces differences page at https://github.com/OpenLiberty/docs/issues/7969. Approving.

**Comment by chirp1** [comment]
Ram completed work for doc issue https://github.com/OpenLiberty/docs/issues/7969

Approving
