### ISSUE TITLE
Jakarta EE 11:  Support Jakarta Security 4.0

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#25090]
## Description

Implement the Jakarta Security 4.0 specification

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Documents

When available, add links to required feature documents. Use "N/A" to mark particular documents which are not required by the feature.

- Externally raised requests for enhancements: 
  - [Aha](https://cloud-platform.ideas.aha.io/): Link to the Aha idea (also add a link to this issue in the Aha idea)
    - Feature owner adds label `Aha idea`
  - [Open Liberty Feature Request](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=): Link to the OL GH issue (also add a link to this issue in the Feature Request GH issue)
    - Feature owner adds label `Requested feature`
- UFO: [Jakarta EE11: Security 4.0 UFO](https://ibm.box.com/s/4bf6yvddaw1uf9xr13in0cjy4xx1k0r3)
  - [Upload the feature UFO to Box](https://ibm.ent.box.com/folder/52716090328) and set the link to be publicly accessible, with a long expiration (10 years)
    - Click "Share" > select "People with link" > click "Link Settings" > under "Link Expiration" select "Disable Shared Link on" > set an expiration date ~10 years into the future
    - If you lack permissions, contact [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect)
- FTS: Link to Feature Test Summary GH Issue: https://github.com/OpenLiberty/open-liberty/issues/32649
- Beta Blog: Link to Beta Blog Post GH Issue: https://github.com/OpenLiberty/open-liberty/issues/34086
- GA Blog: Link to GA Blog Post GH Issue

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Process Overview

- [Prioritization](#prioritization)
- [Design](#design)
- [Implementation](#implementation)
- [Legal and Translation](#legal-and-translation)
- [Beta](#beta)
- [GA](#ga)
  - [Focal Point Approvals](#focal-point-approvals-complete-by-feature-complete-date)
- [Other Deliverables](#other-deliverables)

### General Instructions

The process steps occur roughly in the order as presented. Process steps occasionally overlap.

Each process step has a number of tasks which must be completed or must be marked as not applicable ("N/A").

Unless otherwise indicated, the tasks are the responsibility of the Feature Owner or a Delegate of the Feature Owner.

If you need assistance, reach out to the [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect).

**Important: Labels are used to trigger particular steps and must be added as indicated.** 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Prioritization** (Complete Before Development Starts)

The ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) and area leads are responsible for prioritizing the features and determining which features are being actively worked on.

### **Prioritization**
- [x] Feature added to the "New" column of the [Open Liberty project board](https://github.com/orgs/OpenLiberty/projects/2)
  - Epics can be added to the board in one of two ways:
    - From this issue, use the "Projects" section to select the appropriate project board.
    - From the appropriate project board click "Add card" and select your Feature Epic issue
- [x] Priority assigned
  - Attend the Liberty Backlog Prioritization meeting

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Design** (Complete Before Development Starts)

Design preliminaries determine whether a formal design, which will be provided by an [Upcoming Feature Overview (UFO)](https://ibm.box.com/v/UFO-Template) document, must be created and reviewed.  A formal design is required if the feature requires any of the following: UI, Serviceability, SVT, Performance testing, or non-trivial documentation/ID.  Furthermore, each identified item places a blocking requirement on another team so it must be identified early in the process.  The feature owner may check-off the item if they know it doesn't apply, but otherwise they should work with the focal point to determine what work, if any, will be necessary and make them aware of it.

### **Design Preliminaries**
- [x] UI requirements identified, or N/A. (Feature owner and [UI focal point](https://github.com/orgs/OpenLiberty/teams/ui-approvers))
- [x] Accessibility requirements identified, or N/A. (Feature owner and [Accessibility focal point](https://github.com/orgs/OpenLiberty/teams/accessibility-approvers))
- [x] ID requirements identified, or N/A. (Feature owner and [ID focal point](https://github.com/orgs/OpenLiberty/teams/id-approvers))
   - Refer to [Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty).
   - Feature Owner adds label `ID Required`, if non-trivial documentation needs to be created by the ID team.
   - ID adds label `ID Required - Trivial`, if no design will be performed and only trivial ID updates are needed.
- [x] Serviceability requirements identified, or N/A. (Feature owner and [Serviceability focal point](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
- [ ] SVT requirements identified, or N/A. (Feature owner and [SVT focal point](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
- [x] Performance testing requirements identified, or N/A. (Feature owner and [Performance focal point](https://github.com/orgs/OpenLiberty/teams/performance-approvers))

### **Design**
- [x] POC Design / UFO review requested.
  - Feature owner adds label `Design Review Request`
- [x] POC Design / UFO review scheduled.
  - Follow the instructions in POC-Forum repo
- [x] POC Design / UFO review completed.
- [x] POC / UFO Review follow-ons completed.
- [x] POC Design / UFO approval requested.
  - Feature owner adds label `Design Approval Request`
- [x] Design / UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) adds label `Design Approved`
  - Add the public link to the UFO in Box to the [Documents](#documents) section.
  - The UFO must always accurately reflect the final implementation of the feature. Any changes must be first approved. Afterwards, update the UFO by creating a copy of the original approved slide(s) at the end of the deck and prepend "OLD" to the title(s). A single updated copy of the slide(s) should take the original's place, and have its title(s) prepended with "UPDATED".

### **No Design**
- [ ] No Design requested.
  - Feature owner adds label `No Design Approval Request`
- [ ] No Design / No UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - Approver adds label `No Design Approved`
- [ ] Feature / Capability stabilization or discontinuation or N/A
  - Feature owner adds label `Product Management Approval Request` and notifies [OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management)
  - Approver adds label `Product Management Approved` ([OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management))
  - Note: For stabilized, superseded, and discontinued feature/capability, skip the [Beta](#beta) section of the template (you may delete it).  Otherwise, proceed as normal.

### **FAT Documentation**
- [x] "Feature Test Summary" child task created
  - Use the [Feature Test Summary Template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=)
  - Add FTS issue link to the [Documents](#documents) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Implementation**

A feature must be [prioritized](https://github.com/orgs/OpenLiberty/projects/2) before any implementation work may begin to be delivered (inaccessible/no-ship).  However, a design focused approach should still be applied to features, and developers should think about the feature design prior to writing and delivering any code.  
Besides being prioritized, a feature must also be socialized (or No Design Approved) before any beta code may be delivered.  All new Liberty content must be inaccessible in our GA releases until it is [Feature Complete](#feature-complete) by either marking it `kind=noship` or [beta fencing](#beta-code) it.  
Code may not GA until this feature has obtained the `Design Approved` or `No Design Approved` label, along with all other tasks outlined in the [GA](#ga) section.

### **Feature Development Begins**
- [x] Add the `In Progress` label

## **Legal and Translation**

In order to avoid last minute blockers and significant disruptions to the feature, the **legal items need to be done as early in the feature process as possible**, either in design or as early into the development as possible.  Similarly, translation is to be done concurrently with development.  Both **MUST** be completed before Beta or GA is requested.

### **Legal** (Complete before Feature Complete Date)
- [x] Changed or new open source libraries are cleared and approved, or N/A. (Legal Release Services/Cass Tucker/Release PM).

### **Innovation** (Complete 1 week before Feature Complete Date)
- [x] Consider whether any aspects of the feature may be patentable. If any identified, disclosures have been submitted.

### **Translation** (Complete by Feature Complete Date)
- [x] PII (Program Integrated Information) updates are merged (i.e. all English strings due for translation have been delivered), or N/A.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Beta**

In order to facilitate early feedback from users, all new features and functionality should first be released as part of a beta release.

### **Beta Code**
- [x] [Beta fence](https://github.com/OpenLiberty/open-liberty/wiki/Beta-Fencing) the functionality
  - E.g. `kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`
- [x] Beta development complete and feature ready for inclusion in a beta release
  - Add label `target:beta` and the appropriate `target:YY00X-beta` (where YY00X is the targeted beta version).
- [ ] Feature delivered into beta
  - ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager)) adds label `release:YY00X-beta` (where YY00X is the first beta version that included the functionality).

### **Beta Blog** (Complete by beta eGA)
- [x] Beta blog issue created and populated using the [Open Liberty BETA blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the beta blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [beta release blog post](https://openliberty.io/blog/?search=beta&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **GA**

A feature is ready to GA after it is Feature Complete and has obtained all necessary Focal Point Approvals. 

### **Feature Complete**
- [ ] Feature implementation and tests completed.
  - [ ] All PRs are merged.
  - [ ] All related/child issues are closed.
  - [ ] All stop ship issues are completed.
- [x] Legal: all necessary approvals granted.
- [x] Translation: Feature may only proceed to GA if it has either `Translation - Complete` or `Translation - Missing` label
  - If all translation has been delivered to `release` branch, feature owner adds label `Translation - Complete`.
  - If missing translation does not cause a break in functionality, nor a security or production outage risk, feature owner adds label `Translation - Missing`.
    - Once all missing translations are delivered, the `Translation - Missing` label is replaced with `Translation - Complete`.
  - If missing translation could cause a break in functionality or a security or production outage risk, feature owner adds the `Translation - Blocked` label.
    - Featues with `Translation - Blocked` may **NOT** proceed to GA until the label has been replaced with either `Translation - Missing` or `Translation - Complete`.
  - For further guidance, contact [Globalization focal point](https://github.com/orgs/OpenLiberty/teams/globalization-approvers) or the [Release Architect](https://github.com/orgs/OpenLiberty/teams/release-architect).
- [ ] GA development complete and feature ready for inclusion in a GA release
  - Add label `target:ga` and the appropriate `target:YY00X` (where YY00X is the targeted GA version).
  - Inclusion in a release requires the completion of all Focal Point Approvals.

### **Focal Point Approvals** (Complete by Feature Complete Date)

These occur only after GA of this feature is requested (by adding a `target:ga` label).  GA of this feature may not occur until all approvals are obtained.

### **All Features**
- [ ] **APIs/Externals** - Externals have been reviewed or N/A.  ([OpenLiberty/externals-approvers](https://github.com/orgs/OpenLiberty/teams/externals-approvers))
  - Approver adds label `focalApproved:externals` 
- [x] **Demo** - Demo is scheduled for an upcoming EOI or N/A. ([OpenLiberty/demo-approvers](https://github.com/orgs/OpenLiberty/teams/demo-approvers))
  - Add comment `@OpenLiberty/demo-approvers Demo scheduled for EOI [Iteration Number]` to this issue.
  - Approver adds label `focalApproved:demo`.
- [ ] **FAT** - All Tests complete and running successfully in SOE or N/A. ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers))
  - Approver adds label `focalApproved:fat`.

### **Design Approved Features**
- [ ] **ID** - Documentation is complete or N/A. ([OpenLiberty/id-approvers](https://github.com/orgs/OpenLiberty/teams/id-approvers))
  - Approver adds label `focalApproved:id`.
  - > **_NOTE:_**  If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **InstantOn** - InstantOn capable or N/A. ([OpenLiberty/instantOn-approvers](https://github.com/orgs/OpenLiberty/teams/instantOn-approvers))
  - Approver adds label `focalApproved:instantOn`.
- [ ] **Performance** - Performance testing is complete or N/A. ([OpenLiberty/performance-approvers](https://github.com/orgs/OpenLiberty/teams/performance-approvers))
  - Approver adds label `focalApproved:performance`.
- [ ] **Serviceability** - Serviceability has been addressed or N/A. ([OpenLiberty/serviceability-approvers](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
  - Approver adds label `focalApproved:sve`.
- [ ] **STE** - Skills Transfer Education chart deck is complete or N/A. ([OpenLiberty/ste-approvers](https://github.com/orgs/OpenLiberty/teams/ste-approvers))
  - Approver adds label `focalApproved:ste`.
- [ ] **SVT** - System Verification Test is complete or N/A. ([OpenLiberty/svt-approvers](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
  - Approver adds label `focalApproved:svt`.

### **Remove Beta Fencing** (Complete by Feature Complete Date)
- [ ] Beta guards are removed, or N/A
  - Only after all necessary Focal Point Approvals have been granted.

### **GA Blog** (Complete by Friday after GM)
- [ ] GA Blog issue created and populated using the [Open Liberty GA release blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the GA Blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [release blog post](https://openliberty.io/blog/?search=release&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

### **Post GM** (Complete before GA)
- [ ] After confirming this feature has been included in the GM driver, feature owner closes this issue.

### **Post GA**
- [ ] Remove the `target:ga` and `target:YY00X` labels, and add the appropriate `release:YY00X`. ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager))

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Other Deliverables**

- [ ] **Standalone Feature Blog Post** - A blog post specifically about your feature or N/A.  (Feature owner and [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect))
  - This should be strongly considered for larger or more prominent features.
  - Follow [instructions](https://github.com/OpenLiberty/blogs/tree/draft#writing-and-publishing-blog-posts-on-the-openlibertyio-blog) in the blogs repo.
- [ ] **OL Guides** - OL Guides assessment is complete or N/A. ([OpenLiberty/guide-assessment](https://github.com/orgs/OpenLiberty/teams/guide-assessment/members))
- [ ] **Dev Experience** - Developer Experience & Tools work is complete or N/A. ([OpenLiberty/dev-experience-assessment](https://github.com/orgs/OpenLiberty/teams/dev-experience-assessment/members))
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by tevans78** [comment]
UFO Socialization comments...
- Ensure UFO doc is uploaded to correct location before call
- Slide 9: Application fails to start ... not the whole server
- Slide 9: Can you please add the name of the exception previously thrown?
- Slide 10: If a user provided HAM implementation is used, is there a log message? (serviceability slide). 
- Slide 12: Be specific about when the AmbigousResolutionException is thrown ... server start, application start, first request??
- Slide 13: Update InMemoryIdentityStoreDefinition example syntax
- Slide 13: change example to use encrypted password
- Slide 13: look at allowing password to be passed in via a variable
- Slide 14: Are handlers called per request?
- Slide 14: Also show the developer HAM & Identity stores
- Slide 20: Security Manager is not supported.
- Slide 22: Should BasicRegistry be integrated into the new InMemoryIdentityStore mechanism ... or not?? Should the InMemoryIdenityStore be configurable via server.xml? Provide side by side usage examples & best practice.
- Slide 26: If variables are used in the InMemoryIdentityStore then is there an InstantOn implication? Or maybe just don't allow InMemory in containers (edited) 
- Slide 31: Consider automated TCKs
- Slide 31: Test HAM `@Priority`
- Slide 36: If AmbiguousResolutionException is thrown by CDI, is it clear what the problem is? Example exception message?

**Comment by daveywebster** [comment]
UFO Socialization comments...
- Ensure UFO doc is uploaded to correct location before call - **Done, thanks Alex.**
- Slide 9: Application fails to start ... not the whole server - **Done**
- Slide 9: Can you please add the name of the exception previously thrown?  - **Done, gave error ID and text.**
- Slide 10: If a user provided HAM implementation is used, is there a log message? (serviceability slide).  - **Done, added a clear log message will output the HAM handler being used.**
- Slide 12: Be specific about when the AmbigousResolutionException is thrown ... server start, application start, first request?? - **Done, provided specific statement about exception thrown on application start.**
- Slide 13: Update InMemoryIdentityStoreDefinition example syntax - **Done**
- Slide 13: change example to use encrypted password - **Done**
- Slide 13: look at allowing password to be passed in via a variable - **Done, showed specific syntax, but this could be changed and I will update the UFO if required.**
- Slide 14: Are handlers called per request? - **Done, updated slide 12 (Feature Design)**
- Slide 14: Also show the developer HAM & Identity stores - **Done**
- Slide 20: Security Manager is not supported. - **Done, explicitly stated its removal in EE11.**
- Slide 22: Should BasicRegistry be integrated into the new InMemoryIdentityStore mechanism ... or not?? Should the InMemoryIdenityStore be configurable via server.xml? Provide side by side usage examples & best practice. - **Done, added new slide to reduce clutter.**
- Slide 26 (**now Slide 27**): If variables are used in the InMemoryIdentityStore then is there an InstantOn implication? Or maybe just don't allow InMemory in containers (edited)  - **Done, added note and updated testing points on Slide 32.**
- Slide 31 (**now Slide 32)**: Consider automated TCKs - **Done, added note.**
- Slide 31 (**now Slide 33)**: Test HAM `@Priority` - **Done, expanded on handler testing on new slide to reduce clutter.**
- Slide 36: If AmbiguousResolutionException is thrown by CDI, is it clear what the problem is? Example exception message? - **Done, provided example of erroneous situation sample error message.**

**Comment by NottyCode** [comment]
Slide 13: Maybe exclude xor from being supported in favour of aes.
Can the in memory identity store be disabled in config?

**Comment by daveywebster** [comment]
> Slide 13: Maybe exclude xor from being supported in favour of aes. Can the in memory identity store be disabled in config?

Hi, sorry for the late reply!  I left XOR in as a supported encoding technique because the existing Open Liberty UserRegistry supports XOR, and I modelled the In Memory Identity Store encoding/encryption support based on UserRegistry.  Now, if XOR is out of favour and not recommended, I can remove the example in the slide so that it's mentioned (as the code still supports it), but isn't explicitly shown in the examples.  **Would this be okay?**

Secondly, the In Memory Identity Store is conceptually equivalent to the existing Database and LDAP Identity Stores.  Any of the three - if specified via Jakarta Security X.0 annotations in an application - cannot be then disabled in operator configuration, such as server.xml.  There is no explicit mention in the Jakarta Security 4.0 specification about disabling the In Memory Identity Store, so I didn't consider it, as what is explicit in the documentation, log files and (soon to be completed) code examples/tutorials is that the In Memory Identity Store is for debugging, testing and development purposes only and is strongly recommended to not be used in a production environment.  **Is this okay?**  

Much thanks.

**Comment by NottyCode** [comment]
I'm ok with the answer to the first, but I'm not going to approve the design without a way for an administrator to disable the In Memory Identity Store. To be honest I'd probably prefer it to be disabled OOTB because I think it is going to be an avenue for security vulnerabilities.

**Comment by pgunapal** [comment]
@daveywebster 
**Serviceability Approval Comment** - Please answer the following questions for Serviceability approval:

1.  Have the most likely customer‑facing problem scenarios identified in the Serviceability section of the UFO been addressed in the implementation?

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. IBM Support, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid Support Cases for any problems customers are likely to encounter, or that IBM Support should be able to quickly address those problems without need to engage SMEs?

3.  Which IBM Support / SME queues will handle Support Cases for this feature?  Ensure they are present in the contact reference file and in the Queue Contact Summary, and that the respective IBM Support/SME teams know they are supporting it.  Ask Prashanth Gunapalasingam if you need links or more info.

4. Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?

**Comment by daveywebster** [comment]
**Serviceability Approval Responses**

1 .  **Yes.**  Details from slides 39 and 40 from the [Jakarta Security 4.0 UFO ](https://ibm.ent.box.com/file/1883922167037?s=4bf6yvddaw1uf9xr13in0cjy4xx1k0r3) have been addressed:

- When multiple HAM beans are detected with the same priority (and the HAM handler cannot choose which one), then then an explicit error is thrown as per design and specification:

    - `CWWKS2605E: Unable to determine which HttpAuthenticationMechanism to handle request. The following HttpAuthenticationMechanisms have the same priority or Http Authentiation Mechanism Type CustomHAMThree Priority = 100001, CustomHAMOne Priority = 100001.`

- Common error scenarios are already handled by the existing implemention prior to any specific Jakarta EE11 changes, such as:

    - no HAM nor registry: `CWWKS3005E: A configuration exception has occurred. No UserRegistry implementation service is available.`
    - no datastore: <same error as above - as per existing specification and code>
    - missing mandatory annotation values: compilation error, application cannot start

- Furthermore, explicit trace logging will,

    1/ warn if an in memory identity store was configured:
    - `CWWKS2600W: An identity store that is configured by using an @InMemoryIdentityStoreDefinition annotation was detected within this application. Do not use this definition in a production environment.`

    2/ output which HAM Handler is being used:
    - `The HttpAuthenticationMechanismHandler being used is: CustomHAMHandler.`

    3/ output all HAMs found, their ordering/priority and explicitly states which one resullting bean that was choosen:
    - `Order of HttpAuthenticationMechanisms found (the first one will be used if its prioritization is unique - @Priority for application HAMs and HAM type - Oidc/CustomForm/Form/Basic - for in-built HAMs): CustomHAMThree Priority = 100001, CustomHAMTwo Priority = 100, CustomHAMOne Priority = 1, OidcHttpAuthenticationMechanism, FormAuthenticationMechanism, BasicHttpAuthenticationMechanism.`
AND
    - `The (highest priority) HttpAuthenticationMechanism being used is: CustomHAMThree.`

- Lastly, the in-memory identity store needs to be explicitly enabled for use.  If one exists but is not explicitly enabled, a message is output:

    - `An identity store that is configured by using an @InMemoryIdentityStoreDefinition annotation was detected within this application, but it will not be used because it was not explicitly enabled.`

- Note: All non-debug messages have been approved by translation.


2a) All the problem paths listed above in Q1 (and re-listed below) - and new errors - were internally tested, and also demoed.  These were:
- 1/ cannot resolve HAM priority - **as above**
    - `CWWKS2605E:` ...
- 2/ in-memory identity store should not be used - **as above**
    - `CWWKS2600W:` ...
- 3/ no HAM nor registry - **as above**
    - `CWWKS3005E:` ...
- 4/ bad EL values in annotations:
    - `CWWKS2603W: The Expression Language (EL) expression for the 'priority/priorityExpression' attribute of the identity store annotation cannot be resolved to a valid value. Ensure that the EL expression and the result are valid and ensure that any referenced beans that are used in the expression are resolvable. The default attribute value of '90' is used instead.`
- 5/ invalid credential passed for authorization:
    - `CWWKS2602E: The credential provided to the IdentityStore object is not a UsernamePasswordCredential and cannot be validated.`
- 6/ failed to create a HAM
    - `CWWKS2604E: The HttpAuthenticationMechanism object for the multipleHAMs.E11.war module in the multipleHAMs.E11 application could not be created.`
 - 7/ missing a custom HAM Handler if HAMs with qualifiers were configured
   - `CWWKS2610E: Missing a custom handler that uses qualified HttpAuthenticationMechanisms.`
  
2b) To an independent team not involved with development, nor Jakarta Security.  They then went on to write the FAT Suite tests ([from a FAT suite document](https://github.com/OpenLiberty/open-liberty/issues/32649) which explicitly called out all the error scenarios).  Therefore automated regression testing currently covers all defined errors. 

Communication was through Slack, and their progress was tracked [here](https://github.com/orgs/OpenLiberty/projects/51/views/1). 

2c) Yes, literally all code paths which lead to an error have been both manually tested, and automated test cases created also.



3 . `WAS L3: Core Security` (with whom I liaise with daily).

 
4 . No, no new metrics nor JSON events have been added.

**Comment by gnadell** [comment]
@daveywebster ,WAS support requested for a live session which is scheduled for 4/21, so approving the STE.

**Comment by chirp1** [comment]
Ram's issue at https://github.com/OpenLiberty/docs/issues/8062 Completing examples.

Approving
