### ISSUE TITLE
Add support for ignoring unknown elements in SOAP response

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#25265]
## Description

We run an application on Liberty that performs SOAP-based API calls to a third party API. The API changes frequently and adds new elements to the response, which breaks our application until we update our client code as well.
When previously deploying applications on Websphere Traditional, we were able to configure the custom property "com.ibm.ws.webservices.ignoreUnknownElements=true" to prevent API updates from breaking our application. We are now looking for the same configuration which can be applied on Websphere Liberty. I tried adding the same to jvm.options (-Dcom.ibm.ws.webservices.ignoreUnknownElements=true) but it is not working. 
Reference: https://www.ibm.com/docs/en/was/8.5.5?topic=SSEQTP_8.5.5/com.ibm.websphere.zseries.doc/ae/xrun_jvm.htm#com.ibm.ws.webservices.ignoreUnknownElements
Adding this feature to Liberty would provide value because otherwise development changes need to be done to support non-breaking changes done by a third party. Additionally it would bring Liberty into closer alignment with the same feature on Websphere Traditional.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Documents

When available, add links to required feature documents. Use "N/A" to mark particular documents which are not required by the feature.

- Aha: Externally raised RFE ([Aha](https://cloud-platform.ideas.ibm.com/ideas/LIBERTY-I-79))
  - Link the RFE with this issue
- UFO:  [Upcoming Feature Overview 25265](https://ibm.box.com/s/v8h8r2pvgc4r80rhcnbn80p7u5xu5fvh)
- FTS: Link to Feature Test Summary GH Issue
- Beta Blog: [Link to Beta Blog Post GH Issue](https://github.com/OpenLiberty/open-liberty/issues/29770#issue-2562191696)
- GA Blog: Link to GA Blog Post GH Issue

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Process Overview

- [Prioritization](#prioritization)
- [Design](#design)
- [Implementation](#implementation)
- [Legal and Translation](#legal-and-translation)
- [Beta](#beta)
- [GA](#ga)
  - [Focal Point Approvals](#focal-point-approvals-complete-by-feature-complete-date)
- [Other Deliverables](#other-deliverables)

### General Instructions

The process steps occur roughly in the order as presented. Process steps occasionally overlap.

Each process step has a number of tasks which must be completed or must be marked as not applicable ("N/A").

Unless otherwise indicated, the tasks are the responsibility of the Feature Owner or a Delegate of the Feature Owner.

If you need assistance, reach out to the [OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect).

**Important: Labels are used to trigger particular steps and must be added as indicated.** 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Prioritization** (Complete Before Development Starts)

The ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) and area leads are responsible for prioritizing the features and determining which features are being actively worked on.

### **Prioritization**
- [x] Feature added to the "New" column of the [Open Liberty project board](https://github.com/orgs/OpenLiberty/projects/2)
  - Epics can be added to the board in one of two ways:
    - From this issue, use the "Projects" section to select the appropriate project board.
    - From the appropriate project board click "Add card" and select your Feature Epic issue
- [x] Priority assigned
  - Attend the Liberty Backlog Prioritization meeting

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Design** (Complete Before Development Starts)

Design preliminaries determine whether a formal design, which will be provided by an [Upcoming Feature Overview (UFO)](https://ibm.box.com/v/UFO-Template) document, must be created and reviewed.  A formal design is required if the feature requires any of the following: UI, Serviceability, SVT, Performance testing, or non-trivial documentation/ID.

### **Design Preliminaries**
- [x] UI requirements identified. (Owner and [UI focal point](https://github.com/orgs/OpenLiberty/teams/ui-approvers))
- [x] ID requirements identified. (Owner and [ID focal point](https://github.com/orgs/OpenLiberty/teams/id-approvers))
   - Refer to [Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty).
   - Feature Owner adds label `ID Required`, if non-trivial documentation needs to be created by the ID team.
   - ID adds label `ID Required - Trivial`, if no design will be performed and only trivial ID updates are needed.
- [ ] Serviceability Requirements Identified. (Owner and [Serviceability focal point](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
- [x] SVT Requirements Identified. (Owner and [SVT focal point](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
- [x] Performance testing requirements identified. (Owner and [Performance focal point](https://github.com/orgs/OpenLiberty/teams/performance-approvers))

### **Design**
- [x] POC Design / UFO review requested.
  - Owner adds label `Design Review Request`
- [x] POC Design / UFO review scheduled.
  - Follow the instructions in POC-Forum repo
- [x] POC Design / UFO review completed.
- [x] POC / UFO Review follow-ons completed.
- [x] POC Design / UFO approval requested.
  - Owner adds label `Design Approval Request`
- [x] Design / UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) adds label `Design Approved`
  - Add the public link to the UFO in Box to the [Documents](#documents) section.
  - The UFO must always accurately reflect the final implementation of the feature. Any changes must be first approved. Afterwards, update the UFO by creating a copy of the original approved slide(s) at the end of the deck and prepend "OLD" to the title(s). A single updated copy of the slide(s) should take the original's place, and have its title(s) prepended with "UPDATED".

### **No Design**
- [ ] No Design requested.
  - Owner adds label `No Design Approval Request`
- [ ] No Design / No UFO approved. ([OpenLiberty/chief-architect](https://github.com/orgs/OpenLiberty/teams/chief-architect)) or N/A
  - Approver adds label `No Design Approved`
- [ ] Feature / Capability stabilization or discontinuation or N/A
  - Owner adds label `Product Management Approval Request` and notifies [OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management)
  - Approver adds label `Product Management Approved` ([OpenLiberty/product-management](https://github.com/orgs/OpenLiberty/teams/product-management))
  - Note: For stabilized, superseded, and discontinued feature/capability, skip the [Beta](#beta) section of the template (you may delete it).  Otherwise, proceed as normal.

### **FAT Documentation**
- [ ] "Feature Test Summary" child task created
  - Use the [Feature Test Summary Template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=)
  - Add FTS issue link to the [Documents](#documents) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Implementation**

A feature must be [prioritized](https://github.com/orgs/OpenLiberty/projects/2) before any implementation work may begin to be delivered (inaccessible/no-ship).  However, a design focused approach should still be applied to features, and developers should think about the feature design prior to writing and delivering any code.  
Besides being prioritized, a feature must also be socialized (or No Design Approved) before any beta code may be delivered.  All new Liberty content must be inaccessible in our GA releases until it is [Feature Complete](#feature-complete) by either marking it `kind=noship` or [beta fencing](#beta-code) it.  
Code may not GA until this feature has obtained the "Design Approved" or "No Design Approved" label, along with all other tasks outlined in the [GA](#ga) section.

### **Feature Development Begins**
- [x] Add the `In Progress` label

## **Legal and Translation**

In order to avoid last minute blockers and significant disruptions to the feature, the **legal items need to be done as early in the feature process as possible**, either in design or as early into the development as possible.  Similarly, translation is to be done concurrently with development.  Both **MUST** be completed before Beta or GA is requested.

### **Legal** (Complete before Feature Complete Date)
- [x] Changed or new open source libraries are cleared and approved, or N/A. (Legal Release Services/Cass Tucker/Release PM).
- [x] Licenses and Certificates of Originality (COOs) are updated, or N/A

### **Translation** (Complete 1 week before Feature Complete Date)
- [x] PII updates are merged, or N/A. Note timing with translation shipments.

### **Innovation** (Complete 1 week before Feature Complete Date)
- [x] Consider whether any aspects of the feature may be patentable. If any identified, disclosures have been submitted.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Beta**

In order to facilitate early feedback from users, all new features and functionality should first be released as part of a beta release.

### **Beta Code**
- [x] Beta fence the functionality
  - `kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`
- [x] Beta development complete and feature ready for inclusion in a beta release
  - Add label `target:beta` and the appropriate `target:YY00X-beta` (where YY00X is the targeted beta version).
- [ ] Feature delivered into beta
  - ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager)) adds label `release:YY00X-beta` (where YY00X is the first beta version that included the functionality).

### **Beta Blog** (Complete 1.5 weeks before beta eGA)
- [ ] Beta blog issue created and populated using the [Open Liberty BETA blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the beta blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [beta release blog post](https://openliberty.io/blog/?search=beta&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **GA**

A feature is ready to GA after it is Feature Complete and has obtained all necessary Focal Point Approvals. 

### **Feature Complete**
- [ ] Feature implementation and tests completed.
  - [ ] All PRs are merged.
  - [ ] All epic and child issues are closed.
  - [ ] All stop ship issues are completed.
- [ ] Legal: all necessary approvals granted.
- [ ] Translation: All messages translated or sent for translation for upcoming release 
- [ ] GA development complete and feature ready for inclusion in a GA release
  - Add label `target:ga` and the appropriate `target:YY00X` (where YY00X is the targeted GA version).
  - Inclusion in a release requires the completion of all Focal Point Approvals.

### **Focal Point Approvals** (Complete by Feature Complete Date)

These occur only after GA of this feature is requested (by adding a `target:ga` label).  GA of this feature may not occur until all approvals are obtained.

### **All Features**
- [ ] **APIs/Externals** Externals have been reviewed or N/A.  ([OpenLiberty/externals-approvers](https://github.com/orgs/OpenLiberty/teams/externals-approvers))
  - Approver adds label `focalApproved:externals` 
- [ ] **Demo** Demo is scheduled for an upcoming EOI or N/A. ([OpenLiberty/demo-approvers](https://github.com/orgs/OpenLiberty/teams/demo-approvers))
  - Add comment `@OpenLiberty/demo-approvers Demo scheduled for EOI [Iteration Number]` to this issue.
  - Approver adds label `focalApproved:demo`.
- [ ] **FAT** All Tests complete and running successfully in SOE or N/A. ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers))
  - Approver adds label `focalApproved:fat`.
- [ ] **Globalization** Translation and TVT are complete or N/A. ([OpenLiberty/globalization-approvers](https://github.com/orgs/OpenLiberty/teams/globalization-approvers))
  - Approver adds label `focalApproved:globalization`.

### **Design Approved Features**
- [ ] **Accessibility** Accessibility testing completed or N/A. ([OpenLiberty/accessibility-approvers](https://github.com/orgs/OpenLiberty/teams/accessibility-approvers))
  - Approver adds label `focalApproved:accessibility`.
- [ ] **ID** Documentation is complete or N/A. ([OpenLiberty/id-approvers](https://github.com/orgs/OpenLiberty/teams/id-approvers))
  - Approver adds label `focalApproved:id`.
  - > **_NOTE:_**  If only trivial documentation changes are required, you may reach out to the ID Feature Focal to request a `ID Required - Trivial` label.  Unlike features with regular ID requirement, those with `ID Required - Trivial` label do not have a hard requirement for a Design/UFO.
- [ ] **Performance** Performance testing is complete or N/A. ([OpenLiberty/performance-approvers](https://github.com/orgs/OpenLiberty/teams/performance-approvers))
  - Approver adds label `focalApproved:performance`.
- [ ] **Serviceability** Serviceability has been addressed or N/A. ([OpenLiberty/serviceability-approvers](https://github.com/orgs/OpenLiberty/teams/serviceability-approvers))
  - Approver adds label `focalApproved:sve`.
- [ ] **STE** Skills Transfer Education chart deck is complete or N/A. ([OpenLiberty/ste-approvers](https://github.com/orgs/OpenLiberty/teams/ste-approvers))
  - Approver adds label `focalApproved:ste`.
- [ ] **SVT** System Verification Test is complete or N/A. ([OpenLiberty/svt-approvers](https://github.com/orgs/OpenLiberty/teams/svt-approvers))
  - Approver adds label `focalApproved:svt`.

### **Remove Beta Fencing** (Complete by Feature Complete Date)
- [ ] Beta guards are removed, or N/A
  - Only after all necessary Focal Point Approvals have been granted.

### **GA Blog** (Complete by Feature Complete Date)
- [ ] GA Blog issue created and populated using the [Open Liberty GA release blog post](https://github.com/OpenLiberty/open-liberty/issues/new/choose) template.
  - Add a link to the GA Blog issue in the [Documents](#documents) section.
  - Note: This is for inclusion into the overall [release blog post](https://openliberty.io/blog/?search=release&key=tag).  If, in addition, you'd also like to create a dedicated blog post about your feature, then follow the "Standalone Feature Blog Post" instructions under the [Other Deliverables](#other-deliverables) section.

### **Post GA**
- [ ] Replace `target:YY00X` label with the appropriate `release:YY00X`. ([OpenLiberty/release-manager](https://github.com/orgs/OpenLiberty/teams/release-manager))

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## **Other Deliverables**

- [ ] **Standalone Feature Blog Post** A blog post specifically about your feature or N/A.  ([OpenLiberty/release-architect](https://github.com/orgs/OpenLiberty/teams/release-architect))
  - This should be strongly considered for larger or more prominent features.
  - Follow [instructions](https://github.com/OpenLiberty/blogs/tree/draft#writing-and-publishing-blog-posts-on-the-openlibertyio-blog) in the blogs repo.
- [ ] **OL Guides** OL Guides assessment is complete or N/A. ([OpenLiberty/guide-assessment](https://github.com/orgs/OpenLiberty/teams/guide-assessment/members))
- [ ] **Dev Experience** Developer Experience & Tools work is complete or N/A. ([OpenLiberty/dev-experience-assessment](https://github.com/orgs/OpenLiberty/teams/dev-experience-assessment/members))
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by NottyCode** [comment]
@neuwerk as discussed outside of this issue we shouldn't be using System properties for configuration like this. Either it should be configured in server.xml on an element for the web service runtime (and we don't have this today), or we should update the web service bnd dd. I think there have been a few other cases where having an element for the web service engine would have made sense so I'm wondering if we should bite that bullet even if it would currently only have 1 attribute.

**Comment by cbridgha** [comment]
UFO review notes:

Slide 10 - Is the property "com.ibm.ws.webservices.ignoreUnknownElements" global?  

Slide 11 - Page 11
both request and response?
	only affecting the client side
	Liberty - validation not on server side (its off for providers)
         T-WAS its on for both
Confusing twas and liberty existing behavior.  (provider doesn't change)
Maybe add some detail here.

Slide 18
(webServiceClient)
binding name if webservice needs to match the serverClient config
- Tom asked about ability for application restart....
The webService element - (for the provider) is a future possible config.

Slide Feature Design
Michael - need to update name to "ignoreUnexpected" - more than just validating Unknown...
Is the t-was config name the same proposed here?
naming of element - could use "ws" as prefix....    
naming of attribute could be "validate"
cxf currently uses schema-validation-enabled

page feature design continued...
Why port name - its in WSDL file - optional on annotation
need warning on (Port name is not specified)
fix the JAXB unmarshalling to JAXB validation

Dev Experience - Discuss the language server support with Scott

FVT - add dynamic test for inst on in inst on bucket.

Security - 	Maybe reach out to security team for concern on skipping validation.

Migration - needs more details

**Comment by neuwerk** [comment]
Adding a comment to track the development work for this. Configuration names subject to change based on final design approval. 

***** Work for client side config - `webServiceClient` *****

- [x] Deliver changes introducing beta `webServiceClient` metatype and properties files - #27959 
- [x] Deliver related configuration messages 
- [x] Deliver extendable configuration processing APIs that can be used by both configuration implementations. - #27998
- [x] Deliver `WebServiceClientConfigImpl` Declarative Service, `bnd.bnd` updates to `include-resources` for metatype definitions, and related configuration processing extensions with [JVM Beta Fence System Property](https://github.ibm.com/websphere/WS-CD-Open/wiki/Beta-Fencing#beta-fencing-using-jvm-system-property) to `com.ibm.ws.jaxws.2.3.common`   - #27998
- [x] Deliver Configuration Processing Unit Tests to `com.ibm.ws.jaxws.2.3.common`   - #27998
- [x] Deliver Inbound and outbound client interceptors for mapping processed configuration to Apache CXF supported properties and applying them to the `MessageContext`  - #27998
- [ ] Deliver new `io.openliberty.jaxws.config_fat` with to test both valid and invalid configurations of `webServiceClient`- (1/2) #28862

***** Work for provider side config - `webService` *****

- [ ] Deliver changes introducing beta `webService` metatype and properties files
- [ ] Deliver related configuration messages
- [ ] Deliver `WebServiceConfigImpl` Declarative Service  and related configuration processing extensions with [JVM Beta Fence System Property](https://github.ibm.com/websphere/WS-CD-Open/wiki/Beta-Fencing#beta-fencing-using-jvm-system-property) to `com.ibm.ws.jaxws.2.3.common` 
- [ ] Deliver Configuration Processing Unit Tests to `com.ibm.ws.jaxws.2.3.common` 
- [ ] Deliver Inbound and outbound provider interceptors for mapping processed configuration to Apache CXF supported properties and applying them to the `MessageContext`
- [ ] Deliver new `io.openliberty.jaxws.config_fat` with to test both valid and invalid configurations of `webService`

**Comment by cbridgha** [comment]
Adding the part 2 comments(Sorry so late, and I see the UFO is already updated too) - very few comments in any case.... @neuwerk 

Slide 26(Design) - Question around existing T-WAS behavior for allowing / disallowing schema Validation.....
Slide 50 (Instant On) Question around adding tests for Instant-On?
Slide 54 (Automated Test) - Adding tests for new attributes
Slide 56 (Performance) Add a note for when schema validation enabled.

**Comment by malincoln** [comment]
@tjwatson, as we work through priorities on the Core Runtime backlog, Alasdair would like the latest status on this one.  Is it still in progress or paused; is it in a beta yet as the label says target, not release, what is sizing, and any other helpful status to determine priority.  Thanks!

**Comment by tjwatson** [comment]
> @tjwatson, as we work through priorities on the Core Runtime backlog,

This is a question for @neuwerk (the other Thomas) :)

**Comment by malincoln** [comment]
> > [@tjwatson](https://github.com/tjwatson), as we work through priorities on the Core Runtime backlog,
> 
> This is a question for [@neuwerk](https://github.com/neuwerk) (the other Thomas) :)

Sorry, about that.  Yes, @neuwerk if you can help answer my questions above.  Thanks

**Comment by neuwerk** [comment]
Sure can @malincoln , it has been paused with the London work, but I've actually meant to pick it back up as I've had two requests for it in the last month. It was released in 24.0.0.12-beta and I've contacted Barry to get the proper label added. As far as sizing goes, its a Large, but the work that's actually remaining is a Small, since the only thing outstanding is getting the approvals (and putting the code into GA). If I'm good to pick it back up, I can have it ready to go out in 25.0.0.9.

**Comment by neuwerk** [comment]
Also, @malincoln is it OK to add the new `migration gap` label to this one?

**Comment by malincoln** [comment]
Okay, I've fixed the labels.  Use target for what release you will be targeting to complete.  Once it GA's that label will be replaced with the "release:..." label.  Size for remaiining work set to Small.

**Comment by malincoln** [comment]
> Also, [@malincoln](https://github.com/malincoln) is it OK to add the new `migration gap` label to this one?

Yes, added
