### ISSUE TITLE
Expand MP OpenAPI Fat tests to cover endpoint customization

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#25437]
The current OpenAPI MP Fat tests all hardcode the paths to `/openapi` and `/openapi/ui`.

To ensure that we are seeing expected behavior when the endpoints are customized these need to added to 

This will be a mixture of Selenium based tests where we need to do a step by step check of the UI or making requests to get the pages/contents at given endpoints

- [x] oauth2 #25726
- [x] UI endpoint customization #25436
- [x] Doc endpoint customization #25436
  -  [x] included placement of UI endpoint #25436
- [x] UI and Doc customization #25436
