### ISSUE TITLE
Jakarta Persistence 3.2 - Deliver feature updates to support API M1 build

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#27273]
Add support for Jakarta Persistence API 3.2 M1 build in Open Liberty for persistence-3.2 and persistenceContainer-3.2.

- EclipseLink implementation will still only support 3.1 level of APIs.

- Include JPA FAT updates to repeat for Jakarta EE 11 (no new FAT specific to 3.2).

for #25091 

----

Deliver JPA 3.2 API M1 & Feature updates : #27044 

Existing FAT that should repeat for JPA 3.2:
- [x] com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat : #27044
- [x] com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat : #27296
- [x] com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat : #27296

**Comment by tkburroughs** [comment]
All test repeats delivered
