### ISSUE TITLE
Update Eclipselink from 4.0.1 to 4.0.2

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#27500]
EclipseLink 4.0.2 has been released, update io.openliberty.persistence.3.1.thirdparty and deliver the new release.

Note: there are no overlays to remove.

The included fixes may be found here: [EclipseLink 4.0.2 Release Notes](https://github.com/eclipse-ee4j/eclipselink/releases/tag/4.0.2)

Overlays to remove:
- [x] ~~Remove the TODOs in `build.gradle`~~ Not done; message improvement not yet in eclipselink; moved to [4.0.3](https://github.com/OpenLiberty/open-liberty/issues/27543)
   - /io.openliberty.persistence.3.1.thirdparty/build.gradle

Included fixes to document in Liberty
- [x] [[JPA 3.1] EclipseLink: Deliver Issue #1821](https://github.com/OpenLiberty/open-liberty/issues/24603)
- [x] [[JPA 3.1] EclipseLink: Deliver Issue #1827](https://github.com/OpenLiberty/open-liberty/issues/24647)

**Comment by tkburroughs** [comment]
It appears all work to update to EclipseLink 4.0.2 has been completed; closing.
