### ISSUE TITLE
Update Eclipselink from 4.0.0 to 4.0.1

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#27501]
EclipseLink 4.0.1 has been released, update io.openliberty.persistence.3.1.thirdparty and deliver the new release.

Note: there are no overlays to remove.

Need to remove TODOs (enable tests) in:
- /com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java
- /com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java

The included fixes may be found here: [EclipseLink 4.0.1 Release Notes](https://github.com/eclipse-ee4j/eclipselink/releases/tag/4.0.1)

In addition, the following changes are needed:
- [x] Remove the TODOs for #23952
- [x] Remove the TODOs for #23944
- [x] Remove the TODOs for #23680
- [x] Remove the TODOs for #23566

**Comment by tkburroughs** [comment]
Looks like all test updates related to 4.0.0 to 4.0.1 upgrade have been accounted for; closing.
