### ISSUE TITLE
Update to EclipseLink 4.0.3 for JPA 3.1

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#27543]
When EclipseLink 4.0.3 is released, update `io.openliberty.persistence.3.1.thirdparty` to deliver new release.

- [All EclipseLink Binaries](https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink)
- [EclipseLink 4.0.3 Binaries](https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink/4.0.3)
- [EclipseLink 4.0.3 Release Notes](https://github.com/eclipse-ee4j/eclipselink/releases/tag/4.0.3)

Overlays to remove:
- [x] [Added doPrivileged for setAccessible](https://github.com/OpenLiberty/open-liberty/pull/26608)
- [x] [ASM Performance Improvement](https://github.com/OpenLiberty/open-liberty/issues/27725)
- [x] [UUID not working as GeneratedValue Id in some cases](https://github.com/eclipse-ee4j/eclipselink/issues/2086) -- [(See PR 27872)](https://github.com/OpenLiberty/open-liberty/pull/27872)
- [x] Remove the TODOs in `build.gradle`  (i.e. listed as for 4.0.2)
   - /io.openliberty.persistence.3.1.thirdparty/build.gradle

Included fixes to document in Liberty
- [x] [[JPA 3.1] EclipseLink: Deliver Issue #1981](https://github.com/OpenLiberty/open-liberty/issues/27291)
- [x] [[JPA 3.1] EclipseLink: Deliver Issue #2048](https://github.com/OpenLiberty/open-liberty/issues/27725)
- [x] [[JPA 3.1] EclipseLink: Deliver Issue #2086](https://github.com/OpenLiberty/open-liberty/issues/27852)

**Comment by tkburroughs** [comment]
All overlays removed; all fix issues closed.
- there were no release bugs with this update since all known bugs had been fixed in overlays
- removal of excluded message files was deferred to 4.0.4 update since new messages were added.
