### ISSUE TITLE
EclipseLink: Deliver Bug #579409

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#27544]
It appears the fix for this EclipseLink issue was delivered some time ago, and is likely included in all levels of JPA.

Remove the TODOs that indicate testing should be enabled in these parts:
- /com.ibm.ws.jpa.tests.spec10.entity_jpa_2.2_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java
- /com.ibm.ws.jpa.tests.spec10.entity_jpa_3.0_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java
- /com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java
- /com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java

And close out these issues when the testing works:
- [x] [[JPA 2.2] EclipseLink: Deliver Bug #579409](https://github.com/OpenLiberty/open-liberty/issues/21205)
- [x] [[JPA 3.0] EclipseLink: Deliver Bug #579409](https://github.com/OpenLiberty/open-liberty/issues/21206)
- [x] [[JPA 3.1] EclipseLink: Deliver Bug #579409](https://github.com/OpenLiberty/open-liberty/issues/21207)

**Comment by tkburroughs** [comment]
Fix has been included in all JPA levels and testing has now been enabled; closing.
