### ISSUE TITLE
EclipseLink issues that need to be fixed for Jakarta Data

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#28366]
This issue will keep a list of EclipseLink issues that need to be fixed/implemented for Jakarta Data. More issues will be added as they are found. This list is in order of priority (top of list is highest priority).
- [x] https://github.com/OpenLiberty/open-liberty/issues/32688
- [x] https://github.com/OpenLiberty/open-liberty/issues/32246
- [x] https://github.com/OpenLiberty/open-liberty/issues/30789
- [x] https://github.com/OpenLiberty/open-liberty/issues/30351 The workaround for this in Jakarta Data code is blocking the implementation of other required function
- [x] https://github.com/OpenLiberty/open-liberty/issues/28912
- [x] https://github.com/OpenLiberty/open-liberty/issues/28913
- [x] https://github.com/OpenLiberty/open-liberty/issues/29457
- [x] https://github.com/OpenLiberty/open-liberty/issues/33189 (high - Persistence 3.2 methods not working. Also a potential data consistency bug in EclipseLink. The actual function does work when using 3.1 API to set the same thing, so hopefully the new 3.2 way of setting it can be easily fixed by copying from that)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/29073 (medium - broken in prior releases as well, but requires disabling 10 places in Data tests even with a temporary work around in the Data provider code in place that we would like to get rid of. Should probably fix it, but the IdClass is a less prominent usage pattern, so we could possible get a way with letting it remain broken)
- [x] https://github.com/OpenLiberty/open-liberty/issues/28908
- [x] https://github.com/OpenLiberty/open-liberty/issues/28874
- [x] https://github.com/OpenLiberty/open-liberty/issues/28920
- [x] https://github.com/OpenLiberty/open-liberty/issues/28909
- [x] https://github.com/OpenLiberty/open-liberty/issues/29460 (medium - Persistence 3.2 bug with embeddable records, requires disabling a dozen places in Data tests, so should probably fix it)
- [x] https://github.com/OpenLiberty/open-liberty/issues/28931
- [x] https://github.com/OpenLiberty/open-liberty/issues/30093
- [x] https://github.com/OpenLiberty/open-liberty/issues/28925
- [x] https://github.com/OpenLiberty/open-liberty/issues/29893
- [x] https://github.com/OpenLiberty/open-liberty/issues/29117
- [x] https://github.com/OpenLiberty/open-liberty/issues/29781
- [ ] https://github.com/OpenLiberty/open-liberty/issues/32909 (medium - includes a Persistence 3.2 bug as well as some questions/optional parts that are not needed for 3.2 compliance and can be omitted. Could release without this if need be)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/33662 (medium - Persistence 3.2 bug with somewhat obscure scenario with a heirarchy of record embeddables under another record embeddable. Could release without this if need be)
- [x] https://github.com/OpenLiberty/open-liberty/issues/30534
- [x] https://github.com/OpenLiberty/open-liberty/issues/30444
- [x] https://github.com/OpenLiberty/open-liberty/issues/28545
- [x] https://github.com/OpenLiberty/open-liberty/issues/29475
- [x] https://github.com/OpenLiberty/open-liberty/issues/30501
- [x] https://github.com/OpenLiberty/open-liberty/issues/29443
- [x] https://github.com/OpenLiberty/open-liberty/issues/28368
- [ ] https://github.com/OpenLiberty/open-liberty/issues/33294 (low impact - this would have also been broken in prior releases and we should be able to make the Data provider not require it)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/33293 (low impact - this would have also been broken in prior releases and we should be able to make the Data provider not require it)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/30400 (low impact - this is due to an unfortunate behavior from PostgreSQL that EclipseLink ought to be able to handle better, but it's a wouldn't have worked in prior EclipseLink releases either and only impact some unusual escaping scenarios)
- [x] https://github.com/OpenLiberty/open-liberty/issues/28813
- [x] https://github.com/OpenLiberty/open-liberty/issues/28928
- [x] https://github.com/OpenLiberty/open-liberty/issues/24926
- [x] https://github.com/OpenLiberty/open-liberty/issues/28289
- [x] https://github.com/OpenLiberty/open-liberty/issues/30146
- [ ] https://github.com/OpenLiberty/open-liberty/issues/28078 (low impact - would be nice if this were fixed, but previous EclipseLink releases would have shipped with this bug, and we are able to work around it be forcing a test to run in a particular order)
- [x] https://github.com/OpenLiberty/open-liberty/issues/28905
- [x] https://github.com/OpenLiberty/open-liberty/issues/28898
- [x] https://github.com/OpenLiberty/open-liberty/issues/28895
- [x] https://github.com/OpenLiberty/open-liberty/issues/31559
- [x] https://github.com/OpenLiberty/open-liberty/issues/31558
- [x] https://github.com/OpenLiberty/open-liberty/issues/32185 (low impact - would be nice if this were fixed, but previous EclipseLink releases would have shipped with this bug, and it only impacts a single assertion in 1 test)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/32204 (minor impact, only impacts a single assertion in 1 test)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/33842 (minor impact, easily worked around by including entity identifier variable, more likely to impact direct Jakarta Persistence 3.2 users than Data)
- [x] https://github.com/OpenLiberty/open-liberty/issues/29440
- [x] https://github.com/OpenLiberty/open-liberty/issues/32263
- [x] https://github.com/OpenLiberty/open-liberty/issues/31802
- [x] https://github.com/OpenLiberty/open-liberty/issues/29459
- [x] https://github.com/OpenLiberty/open-liberty/issues/31884
- [x] https://github.com/OpenLiberty/open-liberty/issues/31979
- [x] https://github.com/OpenLiberty/open-liberty/issues/32848
- [x] https://github.com/OpenLiberty/open-liberty/issues/32867
- [x] https://github.com/OpenLiberty/open-liberty/issues/32957
- [ ] https://github.com/OpenLiberty/open-liberty/issues/28589 (minor impact, needs better error message for usability)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/33246 (minor impact and user can easily choose different column name)
- [ ] https://github.com/OpenLiberty/open-liberty/issues/27696 (minor - EclipseLink has chosen this will be unsupported, but needs an appropriate error message)

for #19508
for #25091

**Comment by Riva-Tholoor-Philip** [comment]
JPA team will work on these items as per the priority. Currently we are giving higher priority for Jakarta 11 (Persistence 3.2) issues and Salesforce L3 cases. That is, Issue# 25091.

**Comment by njr-11** [comment]
> JPA team will work on these items as per the priority. Currently we are giving higher priority for Jakarta 11 (Persistence 3.2) issues and Salesforce L3 cases. That is, Issue# 25091.

To clarify, these issues are also for Jakarta EE 11, and it is fine if they are only fixed in Persistence 3.2 and not 3.1 or earlier.

**Comment by Riva-Tholoor-Philip** [comment]
Created EclipseLink issues for the above mentioned issues
