### ISSUE TITLE
Create functional test for `advanced-aws-jdbc-wrapper`

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#28587]
User Story: 
As a user of Open Liberty, JDBC and AWS I want to ensure that I am able to use the `advanced-aws-jdbc-wrapper` to create connections to a PostgreSQL database using an IAM token or a password stored in AWS Secrets Manager.

Current Status:
We currently test configuring the `advanced-aws-jdbc-wrapper` for PostgreSQL, but we do not functionally test this by having a mock S3 service. 
https://github.com/OpenLiberty/open-liberty/blob/bbd918527c6146983a4ff260b9b9091be112c478/dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLAWSTest/server.xml#L39-L57

Work Items:

- [ ] Import testcontainer's localstack module
- [ ] Configure localstack with IAM and Secret Manager
- [ ] Create a PostgreSQL container that has a user that requires a IAM token for authentication
- [ ] Test using an IAM token and a password obtained from Secret Manager
- [ ] Ensure that the `advanced-aws-jdbc-wrapper` does not interfere with connection matching when the cached IAM token expires (every 15 minutes)
