### ISSUE TITLE
Jakarta Data - experimental features to be removed prior to GA

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#28636]
User Story:
As a user of Open Liberty and Jakarta Data, there are features unique to Open Liberty I want to utilize and other experimental features I would prefer to wait to use until they are integrated into the specification.

This user story can maintain a list experimental features that are currently in Open Liberty that are not part of the spec that might be removed prior to GA.

## Review
> List of items to review as team

## More investigation
> Needs more investigation

## Keep and document
> Features we want to keep in Open Liberty but need to document

- [x] Query by Method Name `deleteBy` currently allows users to return an Entity (E), Collection<E>, E[], and the ID type.
  - Specification: Deletes every record which satisfy the restriction, or all records if there is no restriction, and returns either no result (void) or the number of records deleted.
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/1b6aae291e221152224f2ee6fcb3ea7f2e3541ec/dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java#L44-L46
  - Undocumented: `int deleteById(int id)` does Open Liberty return a count (1) or id?
  - Notes from meeting: We should disallow return type of ID, but keep return type of Entity/Entity collection as a value add for Open Liberty
  - More notes: It could be when we return an ID that is a Number it could be distiguished by using Optional<long> or Collection<long> for singular or multiple ids.
  - This is being removed under #33854

- [x] `@Asynchronous` queries are not in the spec yet.
  - Specification: N/A
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/014750b68c9ecff265ff279a8608cc4c3bc550ac/dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java#L56-L60
  - Notes from meeting: Spec currently does allow `@Asynchronous` with a void return time via the interoperability with Jakarta Interceptors.  We should allow for CompletableFuture and CompletableState return types and push for these to be added to the spec in the next release.

- [x] The unique identifier field of an entity `ending with Id` is not in the spec
  - Specification: an entity programming model must define an annotation which identifies the field or property holding the unique identifier of an entity. For Jakarta Persistence, it is jakarta.persistence.Id. Alternatively, an entity programming model might allow the identifier field or property to be identified via some convention.
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/1a66450e1d891bc2501208a2acec8dfaa6cccd8c/dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/House.java#L31
  - Notes from meeting: This is necessary for Java Record support which Jakarta Persistence is never going to support. Open Liberty must have some model for determining `Id` `Version` and `Embedded` fields of a Record based on field name.

- [x] Query by Method name 'OrderBy' are only valid on 'find' queries, but we allow them on `delete` queries.
  - Specification: A `find` query may have an order. The order specifies how records must be sorted.
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/1b6aae291e221152224f2ee6fcb3ea7f2e3541ec/dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Vehicles.java#L39
  -  Expected: Open Liberty should fail to parse this query by method name, and throw an UnsupportedOperationException instead. 
  - Notes from meeting: Does a delete query by method name allow a `Limit` parameter?  If so then we should be able to order the output.  If not, then ordering the output doesn't make sense.
  - Notes: this is more useful then forcing users to use dynamic sorts, and Spring supports it.

- [x] Query by Method name we support the `remove` action
  - Specification: A method name is formed by concatenating, in the following order: an action, which must be `find`, `delete`, `count`, or `exists`
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/517bd25c4305ed9b833a93d0ca8f65297179a8bd/dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java#L74
  -  Notes: synonym for `delete`

- [x] Query by Method name we support the `update` action
  - Specification: A method name is formed by concatenating, in the following order: an action, which must be `find`, `delete`, `count`, or `exists`
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/872e6e22d9d0f3a2d740f4592a84c71987ddade7/dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Vehicles.java#L66

- [x] Query by Method name we support return type of boolean for `delete` queries
  - Specification: Deletes every record which satisfy the restriction, or all records if there is no restriction, and returns either no result (void) or the number of records deleted.
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/517bd25c4305ed9b833a93d0ca8f65297179a8bd/dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java#L39
  - Expected: Open Liberty should fail to parse this query by method name, and throw an UnsupportedOperationException instead. 

## Move to data-1.1 (experimental)
> Features we want remove from data-1.0 and put in data-1.1

## Remove
> Features we want to remove

- [x] #29112
  - Specification: A `find` query may have a limit, for example, First or First10. Other actions must not be combined with a limit.
  - Open Liberty:
https://github.com/OpenLiberty/open-liberty/blob/ec21e2fbdb4641a44c77ab706b5d907065dcd5ab/dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java#L59
  - Expected: Open Liberty should fail to parse this query by method name, and throw an UnsupportedOperationException instead. 
  - Notes from meeting: This must be removed because the grammar for Query by Method Name says we should ignore `FirstX`.

**Comment by njr-11** [comment]
`updateBy` has been removed from the implementation. It was not part of 1.0 and will likely never be added. There are better ways to offer updates that we will look into in a future spec version.

`@Asynchronous` has been added to Data 1.1, so we are keeping that.

**Comment by njr-11** [comment]
Allowing `boolean` return type for delete queries:  The spec does not forbid it and it seems very useful when the delete query removes by primary key or other unique criteria.  It is working, tested, and we will keep this as useful added value.

**Comment by njr-11** [comment]
`remove` as synonym for `delete`: not forbidden by spec. Useful because many times writing tests I have accidentally used "remove" rather than "delete".  Customers will do that, too.  It has almost no cost and is already tested, so might as well keep it.
