### ISSUE TITLE
Untested parts of the Jakarta Data 1.0 Specification

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#29104]
# Missing from Open Liberty + Jakarta Data

- [x] 2.9. Persistent Field Names in Query by Method Name
  - write and implement test that for the following scenario
  - https://github.com/OpenLiberty/open-liberty/pull/29562

```java
class Person {
  private Long id;
  private MailingAddress address;
}

class MailingAddress {
  private int zipcode;
}
```

```java
List<Person> findByAddressZipCode(int zipCode);
List<Person> findByAddress_zipcode(int zipCode);
```

- [x] 3.2.2. Persistent Field Names
  - SPEC: Within a given entity class or embeddable class, names assigned to persistent fields must be unique ignoring case.
A Jakarta Data provider is permitted to reject an entity class if two persistent fields would be assigned the same name.
  - Verify this case seems impossible since we will attempt to create a table with two fields named addressZipCode
  - https://github.com/OpenLiberty/open-liberty/pull/29637

```java
class Customer {
  private Long id;
  private String addressZipCode;
  private MailingAddress address;
}

class MailingAddress {
  private int zipcode;
}
```

```java
List<Customer> findByAddress_zipcode(int zipCode);
```

- [x] 3.1.1. Entity Inheritance
  - SPEC: An entity programming model might support inheritance between entities.
Two entities are related by inheritance if:
    1. The entity classes are related by Java language inheritance, and
    2. The Jakarta Data provider supports retrieving and querying the entities in a polymorphic fashion.
Support for entity inheritance is not required by this specification.
  - We need to do some more testing: 
    - via Persistence using `@Inheritance`
    - via JDBC, need to determine if extends means Inheritance or Mapped Superclass

- [x] 4.5 Conflicting method annotations
  - If a method of a repository interface has more than one such annotation, the annotated repository method must raise UnsupportedOperationException every time it is called.
  - No specific tests for these (that I could find)

- [x] 4.6 Special Parameters for Limits, Sorting, and Pagination
  - SPEC: A repository method must throw UnsupportedOperationException if it has:
    - more than one parameter of type PageRequest or Limit,
    - a parameter of type PageRequest and a parameter of type Limit,
    - a parameter of type PageRequest or Limit, in combination with the keyword First, or
    - more than one parameter of type Order.
  - No specific tests for these (that I could find)

- [x] 4.7.2. Static Mechanisms for Sort Criteria
  - SPEC: The OrderBy keyword cannot be intermixed with the `@OrderBy` annotation or the `@Query` annotation.
  - The specification says we cannot mix this, but does not specify what the outcome should be if a user does intermix these orderings.
  - My guess would be UnsupportedOperationException, but we might need to update the specification to make this clear.
  - We need a test for this

- [x] 4.8.1.1 Requirements when using Offset Pagination
  - SPEC: If PageRequest.requestTotal() returns true, the Page should contain accurate information about the total number of pages and total number of elements across all pages.
  - Otherwise, if PageRequest.requestTotal() returns false, the operations Page.totalElements() and Page.totalPages() throw IllegalStateException.
  - No specific test for this (that I could find)

- [x] 4.8.2.3. Restrictions on use of Cursor-based Pagination
  - SPEC: A repository method that is annotated with `@Query` and performs cursor-based pagination must omit the ORDER BY clause from the provided query and instead must supply the sort criteria via `@OrderBy` annotations or Sort criteria of PageRequest.
  - The provided query must end with a WHERE clause to which additional conditions can be appended by the Jakarta Data provider.
  - The Jakarta Data provider is not expected to parse query text that is provided by the application.
  - What happens if the `@Query` annotation does have a where clause?  Is it ignored? Or do we throw an Exception?
  -  My guess would be UnsupportedOperationException, but we might need to update the specification to make this clear.
  - We need a test for this

- [x] 5.2.4 String Literals
  - SPEC: A single literal ' character may be included within a string literal by self-escaping it, that is, by writing ''.
For example, the string literal 'Furry''s theorem has nothing to do with furries.' evaluates to the string Furry's theorem has nothing to do with furries.
  -  No specific test for this (that I could find)

- [x] 5.3.1 Literal Expressions
  - SPEC: A string, integer, or decimal literal is assigned the type it would be assigned in Java.
So, for example, 'Hello' is assigned the type java.lang.String, 123 is assigned the type int, 1e4 is assigned the type double, and 1.23f is assigned the type float.
  -  No specific test for double or floating point literals using java notation.

- [x] 5.3.2 Special Values
  - SPEC: The special values true and false are assigned the type boolean, and evaluate to their literal values.
The special values local date, local time, and local datetime are assigned the types java.time.LocalDate, java.time.LocalTime, and java.time.LocalDateTime, and evaluate to the current date and current datetime of the database server, respectively.
  - No specific test for this (that I could find)

- [x]  5.3.4 Enum Literals
  - SPEC: The type must be a Java enum type, and the identifier must be the name of an enumerated value of the enum type including the fully qualified Java enum class name. For example, day <> java.time.DayOfWeek.MONDAY is a legal comparison expression.
  - No specific test for this (that I could find)

- [x] 5.3.7 Operator Expressions
  - SPEC: The concatenation operator || is assigned the type java.lang.String.
Its operand expressions must also be of type java.lang.String.
When executed, a concatenation operator expression evaluates to a new string concatenating the strings to which its arguments evaluate.
  - No specific test for this (that I could find)

- [x] 5.4.3 Between Expressions
  - SPEC: A between expression, with syntax given by between_expression is satisfied when its operands all evaluate to non-null values, and, if the not keyword is missing, its left operand evaluates to a value which is:
    - larger than or equal to the value taken by its middle operand, and
    - smaller than or equal to the value taken by its right operand.
  - Or, if the not keyword occurs, the left operand must evaluate to a value which is:
    - strictly smaller than to the value taken by its middle operand, or
    - strictly larger than the value taken by its right operand.
  - All three operands must have the same type.
  - No specific test for this (that I could find)

**Comment by njr-11** [comment]
> 4.7.2. Static Mechanisms for Sort Criteria
> - SPEC: The OrderBy keyword cannot be intermixed with the ... `@Query` annotation.

In this case, OrderBy would be ignored because `@Query` methods can have any method name and do not recognize Query by Method Name keywords.  This applies equally to `OrderBy`, `findBy`, `deleteBy`, ...  We aren't going to scan the method name at all when `@Query` or several of the other annotations like `@Find`, `@Delete`, and so forth are used.
The spec wording could probably use an update here to clarify.

**Comment by njr-11** [comment]
> * What happens if the `@Query` annotation does have a where clause?  Is it ignored? Or do we throw an Exception?

I think this question meant to ask about an ORDER BY clause, not WHERE.  WHERE is expected and works fine.  We do have a test for ORDER BY clause within the user-provided cursor-based pagination `@Query` and it raises UnsupportedOperationException, with a translatable message,
```
CWWKD1033.ql.orderby.disallowed=CWWKD1033E: The {0} method of the {1} repository \
 interface cannot specify a query that includes an ORDER BY clause because \
 the method returns {2}. Remove the ORDER BY clause and instead use the {3} \
 annotation to specify static sort criteria. The query is: {4}.
```

**Comment by njr-11** [comment]
> * SPEC: A single literal ' character may be included within a string literal by self-escaping it, that is, by writing ''

We don't have it in our Liberty specific tests, but I found it covered in the TCK.
