### ISSUE TITLE
Customizable OpenAPI UI

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty#378]
Implement native support for an OpenAPI UI, to enhance the MicroProfile OpenAPI implementation.

- [x] #1823 - Change the UI endpoint from /api/explorer to /openapi/ui

- [x] #531 - Customizing OpenAPI UI

- [x] #530 - Support MP Config value customizationPolling (for performance)

- [ ] Run-at : Investigate if possible to reuse UI artifacts between endpoints (public/private/mp-openapi-ui)

**Comment by mrglavas** [comment]
All UI related tasks are complete.
