### ISSUE TITLE
Feature Ship Release Readiness Checklist for API-10 GH: Support JDBC 4.3 on Liberty

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#5431]
This work item collects the actions for feature readiness to onboard a feature to a release.

This checklist applies to:

AHA link: [https://bigblue.aha.io/features/API-10]
Github link: [https://github.com/OpenLiberty/open-liberty/issues/4728]

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (Clone date)
 
Instructions:
 - do the action and mark it complete in the checklist.
 - make sure the approver puts the appropriate tag on the github epic for the feature.
 - link the github epic for the feature to this work item as a dependency
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **OCT 5** 
- [x] POC Design / WAD Review Scheduled (David Chang) or N/A. AHA Feature marked.
- [x] POC Design / WAD Reviewed (Feature Owner) or N/A. AHA Feature marked.
- [x] Complete any To-Do's from the POC Review, and create a new TO-DO in the AHA Feature for the "Design Approval Request" and assign it to Ian Robinson. Leave the date blank. (Feature Owner)
- [x] Design / WAD Approval (Ian Robinson / Alasdair Nottingham) or N/A. AHA Feature marked.
- [x] No Design / No WAD Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A. AHA Feature marked.
- [x] AHA Feature has link to Github epic or issue. Github epic has link back to AHA Feature. (Feature Owner or PM).
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **OCT 29** 
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **OCT 26** 
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **NOV 2** 
- [x] Implementation complete. (Epic owner / Feature owner) 
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## APPROVALS with TARGET COMPLETION DATE **Nov 2 to Nov 9** 
Prereq: You must have the Design Approval or No Design Approval on the AHA Feature.
- [x] **Accessibility** - (G Scott Johnston). Accessibility testing is complete or N/A. Add label focalApproved:accessibility to the Epic in Github.
- [x] **FAT Liberty SOE** - (Kevin Smith). SOE FATS are running successfully or N/A . Add label focalApproved:fat to the Epic in Github.
- [x] **Globalization** (Marika Joannidis - Liberty / Sam Wong - tWAS). Translation is complete or N/A. TVT - complete or N/A. Add label focalApproved:globalization to the Epic in Github.
- [x] **ID** - (Carolyn Carpenter or Brandy Byrd Gantt). Documentation work is complete or N/A . Add label focalApproved:id to the Epic in Github.
- [x] **Performance** - (Tim Pickett or Jared Anderson). Performance testing is complete with no high severity defects or N/A . Add label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - (Don Bourne). Serviceability has been addressed. 
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Add label focalApproved:ste to the Epic in Github.
- [x] **SVT** - (Lena Klimovich - Cloud). SVT is complete or N/A . Add label focalApproved:svt to the Epic in Github.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## TARGET COMPLETION DATE **NOV 9** 
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / PM)
- [x] Github Epic and Epic's issues is closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## NOT REQUIRED FOR A FEATURE
- [ ] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A. 
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Related Deliverables TARGET COMPLETION DATE **DEC 14** 
- [x] Blog article writeup
