### ISSUE TITLE
APSFOUND-1 Liberty Annotation Caching

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#6329]
WAD Links:

https://ibm.ent.box.com/folder/52057437511
Final WAD; includes updates from 06-Sep-2019: "APSFOUND-1-Final-10-Sep-2019.pptx" 
Most recent WAD review notes: "APSFOUND-1-Update-06-Sep-2019.pptx"
Most recent WAD supporting data: "APSFOUND-1-Update-03-Sep-2019.xlsx"

Details per: https://bigblue.aha.io/features/APSFOUND-1

*) Refactoring of annotation tables to generate tables per class path component.
-- Necessary to support invalidation on class path component boundaries.

*) Adding annotation table persistence (write and read) on component boundaries.
-- Core function: When possible, annotation tables are read from cache.  By default,
   annotation tables are generated by iterative scan.  New results are automatically
   written to cache.

*) Adding logic to incrementally invalidate final result tables.
-- Efficient invalidation is per class path component.  Invalidation of a single
   component should not require regeneration of tables for still valid components.
   Invalidation means re-composing per component tables, reusing already cached
   results for still valid components, and generating new results for invalid
   components.

*) Adding class path component signature generation (JAR size and time stamp) to be
   used for cache invalidation.
-- A new API which works with the artifact file system and which provides size and
   time stamp information for artifact containers which are mapped to a JAR file.
-- Signature information for artifact containers which are mapped to directories is
   not generated.

*) Adding multi-threading to per class path component processing.
-- Having results generated per component enables a multi-threaded implementation
   of processing (either iterative scan or cache read) across components.  A pool
   of threads is provided for per component processing, with each component being
   assigned its own thread up to the capacity of the thread pool.

*) Adding multi-threading to cache writes per class path component.
-- Process has no immediate dependency on writes of per component results.  Writes
   are performed asynchronously.  A pool of threads is provided for per component
   writes, with each component write assigned its own thread up to the capacity of
   the thread pool.

*) Persistence uses either Jandex or uses a custom persistence format.
-- Existing Jandex indexes continue to be used in preference to iterative
   scans.
-- When a Jandex index is available for a component, that index is used in preference
   to a custom format.
-- Writes may use either Jandex or may use a custom format, with preference to
   be determined based on performance tuning.

*) A custom Jandex reader is used.
-- Jandex indexes have much more data than is stored in the annotation target
   tables.  To minimize read overhead, a custom reader is used which skips unused
   data.  This reduces transient memory use during jandex reads, which otherwise
   would read then immediately discard class information which is unused by the
   annotation targets tables.

**Comment by tbitonti** [comment]
==================================================================================
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (Clone date)
 
Instructions:
 - Do the actions below and mark them complete in the checklist when they are done.
 - Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **Before Development Starts or 8 weeks before Onboarding** 
- [ ] POC Design / WAD Review Scheduled (David Chang) or N/A. AHA Feature marked.
- [ ] POC Design / WAD Reviewed (Feature Owner) or N/A. AHA Feature marked.
- [ ] Complete any To-Do's from the POC Review, and create a new TO-DO in the AHA Feature for the "Design Approval Request" and assign it to Ian Robinson. Leave the date blank. (Feature Owner)
- [ ] Design / WAD Approval (Ian Robinson) or N/A. AHA Feature marked.
- [ ] No Design / No WAD Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A. AHA Feature marked.
- [ ] AHA Feature has link to Github epic or issue. Github epic has link back to AHA Feature. (Feature Owner or PM).
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [ ] Create a child task of the epic entitled "FAT Approval Test Summary"
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **6 weeks before Onboarding** 
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **6 to 3 weeks before Onboarding** 
- [N/A] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **2 weeks before Onboarding** 
- [ ] Implementation complete. (Epic owner / Feature owner) 
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## APPROVALS with TARGET COMPLETION DATE **2 to 1 week before Onboarding** 
Prereq: You must have the Design Approval or No Design Approval on the AHA Feature.
- [ ] **Accessibility** - (G Scott Johnston). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **FAT Liberty SOE** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Globalization** (Marika Joannidis - Liberty / Sam Wong - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.
- [ ] **ID** - (Carolyn Carpenter or Brandy Byrd Gantt). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - (Tim Pickett or Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - (Don Bourne). Serviceability has been addressed. 
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - (Greg Ecock - Cloud). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## TARGET COMPLETION DATE **1 week before Onboarding** 
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / PM)
- [ ] Github Epic and Epic's issues is closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## NOT REQUIRED FOR A FEATURE
- [ ] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A. 
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Related Deliverables TARGET COMPLETION DATE **General Availability** 
- [ ] Blog article writeup

**Comment by tbitonti** [comment]
WAD Uploaded: https://ibm.ent.box.com/folder/52057437511
"APSFOUND-1_AnnoCache_WAD.pptx".

**Comment by tbitonti** [comment]
[APSFOUND-1_AnnoCache_WAD.pptx](https://github.com/OpenLiberty/open-liberty/files/2862519/APSFOUND-1_AnnoCache_WAD.pptx)

**Comment by tbitonti** [comment]
[AnnoScan_13-Feb-2019.pptx](https://github.com/OpenLiberty/open-liberty/files/2862522/AnnoScan_13-Feb-2019.pptx)

**Comment by tbitonti** [comment]
[AnnoValidContainer_13-Feb-2019.txt](https://github.com/OpenLiberty/open-liberty/files/2862523/AnnoValidContainer_13-Feb-2019.txt)

**Comment by tbitonti** [comment]
[AnnoFats_13-Feb-2019.txt](https://github.com/OpenLiberty/open-liberty/files/2862554/AnnoFats_13-Feb-2019.txt)

**Comment by tbitonti** [comment]
Uploads are the annotation caching WAD plus supporting documentation.

**Comment by marikaj123** [comment]
@tbitonti - Did the beta feature code make it into Liberty release 19005 GM?

**Comment by tbitonti** [comment]
Sorry, not yet.

**Comment by tbitonti** [comment]
[APSFOUND-1_AnnoCache_WAD.pptx](https://github.com/OpenLiberty/open-liberty/files/3234320/APSFOUND-1_AnnoCache_WAD.pptx)
[APSFOUND-1_AnnoCacheMapping.pptx](https://github.com/OpenLiberty/open-liberty/files/3234321/APSFOUND-1_AnnoCacheMapping.pptx)
[APSFOUND-1_AnnoFAT.txt](https://github.com/OpenLiberty/open-liberty/files/3234322/APSFOUND-1_AnnoFAT.txt)
[APSFOUND-1_AnnoOptions.txt](https://github.com/OpenLiberty/open-liberty/files/3234323/APSFOUND-1_AnnoOptions.txt)
[APSFOUND-1_AnnoPerf.txt](https://github.com/OpenLiberty/open-liberty/files/3234324/APSFOUND-1_AnnoPerf.txt)
[APSFOUND-1_AnnoScan.pptx](https://github.com/OpenLiberty/open-liberty/files/3234325/APSFOUND-1_AnnoScan.pptx)
[APSFOUND-1_AnnoSVT.txt](https://github.com/OpenLiberty/open-liberty/files/3234326/APSFOUND-1_AnnoSVT.txt)

**Comment by tbitonti** [comment]
"AnnoCache_WAD" is the current WAD, which includes updates from the initial WAD review.
"AnnoScan" is an animated diagram which shows the basic scan process and demonstrates multi-threaded scans.
"AnnoCacheMapping" shows the basic scan rocess and the mapping of data structures to cache files.
"AnnoFAT" has the FAT test list.
"AnnoSVT" has the SVT test plan.
"AnnoPerf" has the Performance test plan.
"AnnoOptions" documents options, including enablement options, which will be required for SVT and Performance testing.

**Comment by tbitonti** [comment]
[APSFOUND-1_AnnoScan.pptx](https://github.com/OpenLiberty/open-liberty/files/3238257/APSFOUND-1_AnnoScan.pptx)

**Comment by tbitonti** [comment]
"Pre-beta NLS drop", pull request #7629, has been delivered to open-liberty.  This update includes message updates and additions which are required for the new cache code.  (The cache code is not yet delivered.)

**Comment by tbitonti** [comment]
STE Template Location: Box: https://ibm.box.com/s/1an42g7zdgmaj84w7dft0indqfgi8ffm

**Comment by tbitonti** [comment]
[APSFOUND-1_AnnoCache_WAD.pptx](https://github.com/OpenLiberty/open-liberty/files/3297213/APSFOUND-1_AnnoCache_WAD.pptx)
[APSFOUND-1_AnnoCacheMapping_2.pptx](https://github.com/OpenLiberty/open-liberty/files/3297214/APSFOUND-1_AnnoCacheMapping_2.pptx)
Updated WAD plus Cache mapping diagrams

**Comment by tbitonti** [comment]
[AnnoCache_19-Aug-2019.pptx](https://github.com/OpenLiberty/open-liberty/files/3569946/AnnoCache_19-Aug-2019.pptx)

**Comment by tbitonti** [comment]
[tomb-190810-2154-patch-measurements-cold-2.xlsx](https://github.com/OpenLiberty/open-liberty/files/3569951/tomb-190810-2154-patch-measurements-cold-2.xlsx)

**Comment by gscottj** [comment]
This feature does not have any user interfaces that are exposed to end users. No accessibility verification testing required.

**Comment by donbourne** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  WAD -- does the WAD identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature?
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  

4.  Which L2 / L3 queues will handle PMRs for this feature?  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info.

**Comment by lauracowen** [comment]
@tbitonti Should there be a release blog post issue for this? (appearing here: https://github.com/OpenLiberty/open-liberty/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3ABlog+label%3A%22release%3A190010%22+-label%3AEpic+-label%3Astory+-label%3AtWAS)

**Comment by marikaj123** [comment]
The translation messages are included into the stream.

**Comment by skasund** [comment]
L2 has requested STE slides for this feature.  The STE template can be found at the link below: 

https://ibm.box.com/s/1an42g7zdgmaj84w7dft0indqfgi8ffm

Please upload the completed slides to the same BOX folder.  Thanks!

**Comment by marikaj123** [comment]
@tbitonti - Are we planning to release this feature as a beta in 190011?

**Comment by marikaj123** [comment]
@jhanders34 - Please add the tag target:ga when the feature is ready to go into 190012.

**Comment by tbitonti** [comment]
Added BETA BLOG issue: 
BETA BLOG 191100 : APSFOUND-1 Liberty Annotation Caching
https://github.com/OpenLiberty/open-liberty/issues/9647

**Comment by chirp1** [comment]
Tom will add the information that needs to be documented to his blog post. An update to the --clean option will also be made based on the priority of the  #787 doc issue on the docs backlog. Approving the epic.

**Comment by sabolo** [comment]
This feature is going to struggle to get in for this release.  Due to the nature of the change, a standard SOE will not test this and we need to do a mini-SOE against a personal (or other) build containing the required code changes.  This would normally not be an issue as we can do these mid week however in this case we have 2 cloud outages (this weekend and next) and the infrastructure is flat out running the full SOE around these outages.  The only option on the horizon is Tuesday however that will not give enough time to get the GA flags enabled for the GM build on Wednesday.  If the outage over this weekend has less impact than currently expected there may be a chance on Monday however this is not something we can guarantee at this time.

**Comment by skasund** [comment]
L2 has requested STE slides for this feature.  The STE template can be found at the link below: 

https://ibm.box.com/s/1an42g7zdgmaj84w7dft0indqfgi8ffm

Please upload the completed slides to the same STE Archive BOX folder.  Thanks!

**Comment by tbitonti** [comment]
The PR which changes enablement to "enabled by default" has been merged into open-liberty/integration:
https://github.com/OpenLiberty/open-liberty/pull/9780
If this delivery sticks, it means the caching will be enabled appropriately for post-beta.
