### ISSUE TITLE
SEC-28: Add hash encoding support to QuickStartSecurity

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#6479]
https://bigblue.aha.io/features/SEC-28

Today we support plaintext, XOR, and AES for QuickStartSecurity. This feature is to add support for HASH encoded strings.

### In addition to any issues included in this epic, the following commercial Liberty issues were opened:
CL PR: [https://github.ibm.com/was-liberty/WS-CD-Open/pull/15304](https://github.ibm.com/was-liberty/WS-CD-Open/pull/15304)
- Updated 19001 schema so that we can modify the password attribute to support hashed passwords without breaking the build.

CL PR: [https://github.ibm.com/was-liberty/WS-CD-Open/pull/14108](https://github.ibm.com/was-liberty/WS-CD-Open/pull/14108)
- Add FAT to test quickstartsecurity hashing functionality.

**Comment by jvanhill** [comment]
==================================================================================
Feature Ship Release Readiness Checklist 
 
Instructions:
- Paste everything below the next line into the GitHub epic for a feature as the first comment.

==================================================================================
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (Clone date)
 
Instructions:
 - Do the actions below and mark them complete in the checklist when they are done.
 - Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **Before Development Starts or 8 weeks before Onboarding** 
- [ ] POC Design / WAD Review Scheduled (David Chang) or N/A. AHA Feature marked.
- [ ] POC Design / WAD Reviewed (Feature Owner) or N/A. AHA Feature marked.
- [ ] Complete any To-Do's from the POC Review, and create a new TO-DO in the AHA Feature for the "Design Approval Request" and assign it to Ian Robinson. Leave the date blank. (Feature Owner)
- [ ] Design / WAD Approval (Ian Robinson) or N/A. AHA Feature marked.
- [ ] No Design / No WAD Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A. AHA Feature marked.
- [ ] AHA Feature has link to Github epic or issue. Github epic has link back to AHA Feature. (Feature Owner or PM).
- [ ] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [ ] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [ ] Create a child task of the epic entitled "FAT Approval Test Summary"
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **6 weeks before Onboarding** 
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **6 to 3 weeks before Onboarding** 
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **2 weeks before Onboarding** 
- [ ] Implementation complete. (Epic owner / Feature owner) 
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## APPROVALS with TARGET COMPLETION DATE **2 to 1 week before Onboarding** 
Prereq: You must have the Design Approval or No Design Approval on the AHA Feature.
- [ ] **Accessibility** - (G Scott Johnston). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [ ] **FAT Liberty SOE** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [ ] **Globalization** (Marika Joannidis - Liberty / Sam Wong - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.
- [ ] **ID** - (Carolyn Carpenter or Brandy Byrd Gantt). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [ ] **Performance** - (Tim Pickett or Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [ ] **Serviceability** - (Don Bourne). Serviceability has been addressed. 
- [ ] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [ ] **SVT** - (Greg Ecock - Cloud). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## TARGET COMPLETION DATE **1 week before Onboarding** 
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / PM)
- [ ] Github Epic and Epic's issues is closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## NOT REQUIRED FOR A FEATURE
- [ ] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A. 
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Related Deliverables TARGET COMPLETION DATE **General Availability** 
- [ ] Blog article writeup

**Comment by marikaj123** [comment]
According to Jesse, there is no translation as it is a simple change to a configuration attribute's type.

**Comment by sabolo** [comment]
Please can you complete the feature test summary for this features?  To save you time I have created the issue and populated it with the template for you.  Many thanks

**Comment by jvanhill** [comment]
@sabolo - Hi Kevin. I have filled in the test feature summary. Thanks for generating it for me. The FAT test in GHE is waiting for the implementation in OLGH to make it to master. If you want to review it before it makes integration or master, I have included the GHE issue in this issue's description.

**Comment by skasund** [comment]
L2 won't need an STE for this feature.  Please make sure the documentation is updated to reflect this change.  Thanks!

**Comment by marikaj123** [comment]
@jvanhill - Please follow the Liberty process to ensure your feature will be included in the GM driver: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wde4b45b770c2_47cd_9d6d_7061f359add9/page/GitHub%20process%20for%20a%20Feature%20to%20board%20the%20release%20train

**Comment by jvanhill** [comment]
@marikaj123 - I have completed the steps from the link above. Closing this epic to complete the process.
