### ISSUE TITLE
Feature Ship Release Readiness Checklist for API-23

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#6674]
This work item collects the actions for feature readiness to onboard a feature to a release.

This checklist applies to: 

AHA feature : https://bigblue.aha.io/features/API-23

Github epic : https://github.com/OpenLiberty/open-liberty/issues/4089
Feature Ship Release Readiness Checklist 
 
===================================================================
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (Clone date)
 
Instructions:
 - Do the actions below and mark them complete in the checklist when they are done.
 - Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **Before Development Starts or 8 weeks before Onboarding** 
- [x] POC Design / WAD Review Scheduled (David Chang) or N/A. AHA Feature marked.
- [x] POC Design / WAD Reviewed (Feature Owner) or N/A. AHA Feature marked.
- [x] Complete any To-Do's from the POC Review, and create a new TO-DO in the AHA Feature for the "Design Approval Request" and assign it to Ian Robinson. Leave the date blank. (Feature Owner)
- [x] Design / WAD Approval (Ian Robinson) or N/A. AHA Feature marked.
- [x] No Design / No WAD Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A. AHA Feature marked.
- [x] AHA Feature has link to Github epic or issue. Github epic has link back to AHA Feature. (Feature Owner or PM).
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of the epic entitled "FAT Approval Test Summary"
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **6 weeks before Onboarding** 
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **6 to 3 weeks before Onboarding** 
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **2 weeks before Onboarding** 
- [x] Implementation complete. (Epic owner / Feature owner) 
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## APPROVALS with TARGET COMPLETION DATE **2 to 1 week before Onboarding** 
Prereq: You must have the Design Approval or No Design Approval on the AHA Feature.
- [x] **Accessibility** - (G Scott Johnston). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **FAT Liberty SOE** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Globalization** (Marika Joannidis - Liberty / Sam Wong - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.
- [x] **ID** - (Carolyn Carpenter or Brandy Byrd Gantt). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - (Tim Pickett or Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - (Don Bourne). Serviceability has been addressed. 
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - (Brian Hanczaryk - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## TARGET COMPLETION DATE **1 week before Onboarding** 
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / PM)
- [x] Github Epic and Epic's issues is closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## NOT REQUIRED FOR A FEATURE
- [x] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A. 
- [x] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Related Deliverables TARGET COMPLETION DATE **General Availability** 
- [x] Blog article writeup

**Comment by hutchig** [comment]
@atosak 
Is the "FAT Approval Test Summary" requested above
the same thing as "Feature Approval Test Summary"? 
i.e.
https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)
as in:
https://github.com/OpenLiberty/open-liberty/issues/4087
"MP Reactive Streams Operators 1.0: Feature Test Summary"
?

**Comment by hutchig** [comment]
@atosak  Has Bob Peterssen replaced Brandy in the template above?

**Comment by atosak** [comment]
Yes Gordon, Thanks for pointing it out.  I will replace the name in the template moving forward.

**Comment by atosak** [comment]
@hutchig Yes, Test summary should be covered.

**Comment by hutchig** [comment]
@rhpeters  Please could you link me up with an ID contact to help resolve how I can deliver the ID requirements as described in the WAD? 

The WAD page on "communication" currently has:
```
This material is suitable for Open Liberty blog articles for the audience of ‘settler’ type developers.
As well as Beta and GA release blog post inclusion:

(Any security related material (e.g. regarding Principle context propogation) should be considered for the Knowledge Centre. )

An article showing the simple wiring together of two different Java EE technologies with very little application code using the fluent, functional composition that reactive streams enables along with simple operator use. The aim is to introduce streams, operators and show the expressive power/productivity of stream use.

A second article where the text and code’s aim is to jump start a developer in writing their own reactive stream Publisher and Subscriber. This article can show mixing with RxJava (and maybe) Reactor sourced stream elements and operators – showing that it is not a “choose one” scenario – where users might feel inclined to ignore new entrants.

Later on, a ‘Guide’ that shows how to use the MicroProfile Messaging Annotations to subscribe and write to a persisted Kafka topic as might be used in inter-service, Event Driven, flows.
```

So the KC requirements described in the WAD relate to no more than:

"(Any security related material (e.g. regarding Principle context propogation) should be considered for the Knowledge Centre. )"

So what I would propose is that we need something similar to:
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_fault_tolerance.html
and I will cover the above requirement.

Can I supply a draft for this? 
Please would you inform me of the format and elivery process needed?
thanks!

I suggest we handle further discussion in: 
https://github.com/OpenLiberty/open-liberty/issues/4088

**Comment by atosak** [comment]
@chirp1 Karen can u help Gordon with the question above?

**Comment by hutchig** [comment]
There are no translatable messages as part of this feature.

**Comment by hutchig** [comment]
I am going to tick the check box for 

 "OL Guides - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A"
based on https://github.com/OpenLiberty/guides-common/issues/293#issuecomment-504453442
and
https://github.com/OpenLiberty/guides-common/issues/27
https://github.com/OpenLiberty/guides-common/issues/293

@yeekangc please untick if you are not happy with that.

**Comment by hutchig** [comment]
Discussed blog with Laura - she has merged and requests close.
