### ISSUE TITLE
Open-Source Open Liberty's Apache CXF 2.6.2 

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#7824]
Currently the version of CXF used by Open Liberty's jaxws-2.2 feature comes from an IBM fork of Apache CXF 2.6.2. It has been maintained by the WebSphere team, but now needs to be relocated to Open-Liberty. 

- [x] Identify Liberty specific changes in our CXF 2.6.2 fork

- [x] Pull in CXF 2.6.2 from Maven Central

- [x] Break out the bundles in the com.ibm.ws.org.apache.cxf.jaxws project into individual projects so that each bundle corresponds to the specific CXF module. 

- [x] Add updated source to it's corresponding bundle in open-liberty

- [x] Add any dependencies the bundles need in order to compile

- [x] Build bundles/Open-Liberty and start a server with jaxws-2.2 to ensure that feature will start with updated bundles activated

- [x] Run all regression testing

**Comment by WhiteCat22** [comment]
Here are the bundles that we need to create:

Override bundles:
- [x] api - #8059
- [x] rt/bindings/soap - #8157
- [x] rt/core
- [x] rt/databinding/jaxb
- [x] rt/frontend/jaxws
- [x] rt/frontend/simple
- [x] rt/transports/http - #8710
- [x] rt/ws/policy

Stub bundles:
- [x] rt/binding/xml - #7940
- [x] rt/management - #7941
- [x] rt/ws/addr - #7942

Override bundles have Liberty specific changes, stub bundles do not and just need to pull in the cxf jars from Artifactory.

**Comment by stephenpatten** [comment]
What if you wanted to use the new 3.x bits from the CFX project, is there a story around supporting that scenario?

**Comment by neuwerk** [comment]
@stephenpatten I realize that over a year later, you probably aren't holding your breath over the answer, but I just now saw it. I'm so sorry, I wasn't notified and I haven't looked at this issue for far too long. Anyway, in case you are curious we are working on this issue and there are two ways we are doing that: 

The Jakarta XML Web Services 3.0 feature uses CXF 3.X (at 3.4 currently): 

https://github.com/OpenLiberty/open-liberty/issues/11862

xmlWS-3.0 is based on work we are doing around jaxws-2.2 and jaxws-2.3. You can see that work here: 

https://github.com/OpenLiberty/open-liberty/issues/4606

**Comment by neuwerk** [comment]
This issue should have been closed over a year ago when the work was complete.
