### ISSUE TITLE
Locking issues from polling and other operations

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#8412]
User story:
"As a user of EJB persistent timers in Liberty, I want failover of timer tasks to occur seamlessly, and efficiently, even when I am running in an environment where there are a large number of servers, so that I do not experience outages due to deadlocks or slowdowns due to locking issues."

Plan: 
- [x] Investigate and correct any locking issues present when running against supported databases
- [x] Investigate and correct any failover issues present when running against supported databases.
- [x] Perform a manual load test. Investigate any deadlock/slowdown/failover issues when running under load.
