### ISSUE TITLE
Enable installation of user features on Open Liberty   

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8986]
This feature is to enable the featureUtility command line tool and Liberty Maven/Gradle plugins to install user features on Open Liberty.

 The following scenarios will be enabled:
 - Install a user feature from Maven coordinates specified in a Maven/Gradle build
 - Install a user feature from Maven coordinates using featureUtility
 - Install a user feature from a local ESA file specified in a Maven/Gradle build
 - Install a user feature from a local ESA file using featureUtility
​

What commercial Liberty edition does this feature belong in (pick one)?
 Open Liberty

Should this feature be included in the Bluemix buildpack?
 NoWhat SalesForce Skill/Mission Team and legacy RETAIN queue will be responsible for supporting this feature? SalesForce: 

WAS L3: Liberty Install RETAIN: LL3INS

Link to UFO: https://ibm.box.com/shared/static/3e171xgh9xi63tqifirq4x0s4lp4rx4u.pptx

**Comment by atosak** [comment]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)
 
Instructions:
 - Do the actions below and mark them complete in the checklist when they are done.
 - Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **Before Development Starts or 8 weeks before Onboarding** 
- [x] POC Design / WAD Review Scheduled (David Chang) or N/A.
- [x] POC Design / WAD Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / WAD Approval (Alasdair Nottingham) or N/A.
- [ ] No Design / No WAD Approval (Arthur De Magalhaes - cloud / Alasdair Nottingham - server) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified. (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of the epic entitled "FAT Approval Test Summary".  Add and fill in the template as described here: https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **3 weeks before Onboarding** 
- [ ] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE ** 3 weeks before Onboarding** 
- [ ] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## TARGET COMPLETION DATE **2 weeks before Onboarding** 
- [ ] Implementation complete. (Epic owner / Feature owner) 
- [ ] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [ ] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## APPROVALS with TARGET COMPLETION DATE **2 to 1 week before Onboarding** 
Prereq: You must have the Design Approved or No Design Approved label on the GitHub Epic.
- [x] **Accessibility** - (Steven Zvonek). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **FAT Liberty SOE** - (Kevin Smith). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Globalization** (Sam Wong - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.
- [x] **ID** - (Kareen Deen). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - (Jared Anderson). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - (Don Bourne). Serviceability has been addressed. 
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - (Greg Ecock - Cloud, Brian Hanczaryk- APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.
- [x] **Demo** - (Liberty only - Tom Evans or Chuck Bridgham). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## TARGET COMPLETION DATE **1 week before Onboarding** 
- [ ] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [ ] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the master branch. (Epic owner / Feature owner / Backlog Subtribe PM)
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## NOT REQUIRED FOR A FEATURE
- [ ] **OL Guides** - (Yee-Kang Chang). Assessment for OL Guides is complete or N/A. 
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## Related Deliverables TARGET COMPLETION DATE **General Availability** 
- [ ] Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by yeekangc** [comment]
Can someone share a link to the UFO for this epic?  Thanks.

**Comment by bensonlatibm** [comment]
Edited description to add link to UFO.

**Comment by yeekangc** [comment]
@gkwan-ibm @cherylking @ericglau

**Comment by yeekangc** [comment]
This feature covers https://github.com/OpenLiberty/ci.maven/issues/837, which needs to be delivered in a release of ci.maven and ci.gradle before closure.  The build plugins are released on different schedule than the runtime.

**Comment by NottyCode** [comment]
@bensonlatibm  I tried to download the attached design doc, but it looks to be in Keynote format rather than powerpoint. Can you check into this?

**Comment by bensonlatibm** [comment]
@NottyCode powerpoint version uploaded.

**Comment by yeekangc** [comment]
Where are we with the work to add the corresponding support to ci.maven and ci.gradle for this?  Do you have news, @bensonlatibm @hermankailey?  Do you have pointers to the PRs?

Cc @cherylking @ericglau @gkwan-ibm

**Comment by bensonlatibm** [comment]
Uploaded latest version of UFO.

**Comment by malincoln** [comment]
@NottyCode are you now able to review the design?  Feature complete is this week.

**Comment by donbourne** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?
> Yes

2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?

> a) Typo in user inputs (feature name, maven coordinate, etc), repo connection issues
b) EOI meeting/ install team
c) Yes

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature?
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  

> SVT: Brian Hanczaryk
SVT found no concerns regarding serviceability

4.  Which L2 / L3 queues will handle PMRs for this feature?  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info.

> WAS: L3 Liberty Install

5.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?

> No new metrics / No JSON events

**Comment by bmarwell** [comment]
Hooray! :) Thanks everyone involved!

**Comment by skasund** [comment]
L2 has requested a live STE presentation for this feature.  The STE templates can be found at the links below.  You can use either one to create the education.  

Slide Template:  https://ibm.box.com/s/1an42g7zdgmaj84w7dft0indqfgi8ffm

Github Template:  https://pages.github.ibm.com/WASL3/site/STE/about

Please upload the completed slides to the same 'STE Archive' BOX folder or provide me the Github link, and I will provide the STE approval.  The live presentation can be scheduled with the L2 team at a later date.  Thanks! 

> I uploaded to the STE Archive. Thank you
Link to STE: https://ibm.box.com/s/2tpb6vaowu46nf6xffir5hvp45b0wapx

**Comment by mhldr** [comment]
Could we have a link to a feature test summary please?

> Link to FTS: https://github.com/OpenLiberty/open-liberty/issues/14677

**Comment by skasund** [comment]
@bensonlatibm @jjiwooLim  I've provided the STE approval for the slides.  Vikram will reach out to you to set up a live presentation for this feature.  Thanks

**Comment by chirp1** [comment]
The ID issue is at https://github.com/OpenLiberty/docs/issues/4559 The writer made the update and Benson has approved it. I'm approving Benson's epic.
