### ISSUE TITLE
JakartaEE: Deliver Jakarta EE 9

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#9876]
**Re-purpose this Epic Issue/Feature**
After discussions with both @atosak and @NottyCode, we decided to re-purpose this Package Rename Issue as the new Jakarta EE 9 Epic Feature.  We have made sufficient progress with the Package Rename tool and testing to satisfy our thoughts that this approach will work for Open Liberty and the Jakarta EE 9 solution.  So, we will now use this Epic Feature to drive the rest of the Jakarta EE 9 development work.  (The original Description was kept intact and is posted below.)

Following are the highlights from the [Jakarta EE 9 Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan):

- `javax` to `jakarta` namespace change
- Java SE 11 required for certification
- Pruning of following features
  - XML Registries (JAXR)
  - XML RPC (JAX-RPC)
  - Deployment (JSR 88)
  - Management (JSR 77)
  - Distributed Interop (Ch 10 of EJB 3.2 Core spec)
- Adding features due to Java SE 11 drop
  - Activation (required)
  - XML Binding (JAXB) (optional)
  - XML Web Services (JAX-WS) (optional)
  - Web Services Metadata (optional)
  - SOAP with Attachments (optional)
- Optional features
  - EJB 2.x API Group
  - Enterprise Web Services (JSR 109)

More detail on how these Jakarta EE 9 Release Plan items affect our Open Liberty deliverable will be outlined in the upcoming UFO.

**Original Description for Package Rename Prototype Investigation**
Jakarta EE 9 will introduce new names for existing packages. Some of those specifications are pulled in from open source dependencies and likely we would pick up new versions of those open source dependencies. However some components like the web container, JSP engine, WebSockets, security and the ejb container are implemented directly in Liberty and they need to continue to support Java EE 7, 8 as well as Jakarta EE 9.

Some thoughts for consideration:

1. Duplicate the code for Jakarta EE 9. This leads to duel maintenance. Fixes required to common code needs to be made twice.
2. Runtime bytecode rewriting for Jakarta EE 8 and earlier vs Jakarta EE 9 and later
3. Single source, and have the build produce duplicate binaries one for Jakarta EE 8 and earlier and another for Jakarta EE 9 and later

Run some experiments with the webcontainer to see what the best approach is.

Note we should validate that the Liberty kernel has no dependencies on Java EE/Jakarta EE APIs. Whatever happens we cannot have two kernel binaries, one for Jakarta EE 8 and earlier and another for Jakarta EE 9 or later.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## When complete & mandatory, add links to the UFO (Upcoming Feature Overview) document, FTS (Feature Test Summary), and blogs post issues(s):
- UFO: https://ibm.ent.box.com/file/817620528060
- FTS: https://github.com/openliberty/open-liberty/issues/12969
- ID issue:  https://github.com/OpenLiberty/docs/issues/4863
- Beta Blog Post (if applicable): There have been several
- Blog Post: 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## List of Steps to complete or get approvals / sign-offs for Onboarding to the Liberty release (GM date)

Instructions:
- Do the actions below and mark them complete in the checklist when they are done.
- Make sure all feature readiness approvers put the appropriate tag on the epic to indicate their approval.

## **Design**
Before Development Starts or 8 weeks before Onboarding
- [x] POC Design / UFO Review Scheduled (David Chang) or N/A.
- [x] POC Design / UFO Reviewed (Feature Owner) or N/A.
- [x] Complete any follow-ons from the POC Review.
- [x] Design / UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [x] No Design / No UFO Approval ([Alasdair Nottingham](https://github.com/NottyCode)) or N/A.
- [x] SVT Requirements identified. (Epic owner / Feature owner with SVT focal point)
- [x] ID Requirements identified ([Documenting Open Liberty](https://github.com/OpenLiberty/open-liberty/wiki/Documenting-Open-Liberty)). (Epic owner / Feature owner with ID focal point)
- [x] Create a child task of this epic entitled "Feature Test Summary" via [this template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=Feature+Test+Summary&template=feature_test_summary.md&title=). Add the link in above.

##
##

## **Development**
When active development has begun 
- [x] Add the "In Progress" label to this issue.

## **Beta**
If your feature, or portions of it, are going to be included in a beta  
Before Onboarding the beta
- [x] Beta Fence the functionality (`kind=beta`, `ibm:beta`, `ProductInfo.getBetaEdition()`)  

1 week before beta GA
- [x] Create, populate, and link to the [Beta blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_beta.md&title=BETA+BLOG+-+title_of_your_update)

## **Legal**
3 weeks before Onboarding
- [x] Identify all open source libraries that are changing or are new. Work with Legal Release Services (Cass Tucker or Release PM) to get open source cleared and approved. Or N/A. (Epic Owner).   New or changed open source impacts license and Certificate of Originality.

## **Translation**
3 weeks before Onboarding
- [x] All new or changed PII messages are checked into the integration branch, before the last translation shipment out. (Epic Owner)

## **Feature Complete**
2 weeks before Onboarding
- [x] Implementation complete. (Epic owner / Feature owner)
- [x] All function tests complete. Ready for FAT Approval. (Epic owner / Feature owner)
- [x] Review all known issues for Stop Ship. (Epic owner / Feature owner / PM)

## **Focal Point Approvals**
2 to 1 week before Onboarding
#### You **MUST** have the Design Approved or No Design Approved label before requesting focal point approvals.

All features (both "Design Approved" and "No Design Approved")
- [x] **FAT** - ([OpenLiberty/fat-approvers](https://github.com/orgs/OpenLiberty/teams/fat-approvers)). SOE FATS are running successfully or N/A . Approver adds label focalApproved:fat to the Epic in Github.
- [x] **Demo** - ([Tom Evans](https://github.com/tevans78) or [Chuck Bridgham](https://github.com/cbridgha)). Demo is scheduled for an upcoming EOI. Approver adds label focalApproved:demo to the Epic in Github.
- [x] **Globalization** ([Sam Wong](https://github.com/samwatibm) - Liberty / Simy Cheeran - tWAS). Translation is complete or N/A. TVT - complete or N/A. Approver adds label focalApproved:globalization to the Epic in Github.

"Design Approved" features
- [x] **Accessibility** - ([Steven Zvonek](https://github.com/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Epic in Github.
- [x] **ID** - ([Karen Deen](https://github.com/chirp1)). Documentation work is complete or N/A . Approver adds label focalApproved:id to the Epic in Github.
- [x] **Performance** - ([Jared Anderson](https://github.com/jhanders34)). Performance testing is complete with no high severity defects or N/A . Approver adds label focalApproved:performance to the Epic in Github.
- [x] **Serviceability** - ([Don Bourne](https://github.com/donbourne)). Serviceability has been addressed.
- [x] **STE** - (Swati Kasundra). STE chart deck is complete or N/A . Approver adds label focalApproved:ste to the Epic in Github.
- [x] **SVT** - ([Brian Hanczaryk](https://github.com/hanczaryk) - APS). SVT is complete or N/A . Approver adds label focalApproved:svt to the Epic in Github.

## **Ready for GA**
1 week before Onboarding
- [x] No Stop Ship issues for the feature. (Epic owner / Feature owner / Release PM)
- [x] Ship Readiness Review and Release Notes completed (Epic owner / Feature owner / Release PM)
- [ ] Github Epic and Epic's issues are closed / complete. All PRs are committed to the release branch. (Epic owner / Feature owner / Backlog Subtribe PM)

1 week before GA
- [ ] Create, populate, and link to the [Blog post issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=lauracowen%2C+jakub-pomykala&labels=&template=blog_post_ga_release.md&title=GA+BLOG+-+title_of_your_update)

## **Other deliverbles**
- [ ] **OL Guides** - ([Yee-Kang Chang](https://github.com/yeekangc)). Assessment for OL Guides is complete or N/A.
- [ ] **WDT** - (Leonard Theivendra). WDT work complete or N/A.
- [ ] **Blog** - ([Laura Cowen](https://github.com/lauracowen)) Blog article writeup (Epic owner / Feature owner / Laura Cowen)

**Comment by tbitonti** [comment]
Current prototype code is located at: https://github.com/bjhargrave/transformer

This issue in the repository which contains the prototype code is relevant to the goal: https://github.com/bjhargrave/transformer/issues/1

As a first goal, we should create a transformed liberty image using very basic steps:

(1) Servlet function is the first target, using a suitable jakarta dependent web application.
(2) The server will be configured to the "jakarta" servlet feature.
(3) Liberty image components which are used by this feature used must be identified.  Some will require transformation (e.g., web-common).  Others should run as-is (e.g., kernal).
(4) A set of package rename rules must be specified.  There is an initial approximation provided in the prototype transformation code which will be used, and which will be updated as needed.
(5) We will manually rename packages within on metadata, and will transform classes using the current prototype jar/class transformer.
(6) The goal is met if we are able to run the jakarta dependent web application using the transformed image.

To meet the first goal, these tasks will need to be accomplished:

(1) A jarkarta version web application -- which requires package renaming -- must be located or created.
(2) A jakarta feature name must be specified.
(3) A subset of liberty image components must be identified as those which are needed for the jakarta feature, and the components must be categorized as "will not be transformed" vs "will be transformed".
(4) Code adjustments might be necessary, for example, to remove unnecessary package dependencies (if any are present) from liberty kernal function.
(5) We will want a location for assembling the transformed image.  Should this be done using build steps in the prototype repository?
(6) An initial liberty image must be selected.
(7) Work must be done to transform the components of the image, and to update the assembly steps to make use of the transformed components.  The work will be a combination of manual and automated steps.
(8) We will need a step of verifying the transformed image against the jakarta web application.

**Comment by atosak** [comment]
Discussed we need to have an UFO for this Epic and @kwsutter confirmed he has a to do to schedule one.

**Comment by kwsutter** [comment]
Re-purposed this Epic for the overall Jakarta EE 9 effort.  Reference [updated Description](https://github.com/OpenLiberty/open-liberty/issues/9876#issue-525388605) for more information.

**Comment by andymc12** [comment]
Notes from Part 1 of the UFO Review:

Page 12 - TODO: test debugger on transformed code - goal is for app developer to be able to debug into OL code

Page 19 - TODO: note about changing feature names

Page 21 (?) - Add note about IBM APIs - see Design Issue 11497

Update chart deck to make clear that properties also need to be updated from javax to jakarta

Page 24 - update Jakarta Management so that it doesn’t sound like we are breaking EE 9 by removing something

Jared: update to say which optional features will be there - maybe mention the JAX-RS dependency on JAXB?

Part 2 is scheduled for Friday, 17 April 2020 at 11am US Eastern Time (10am US Central)

**Comment by andymc12** [comment]
Video recording for Part 1 of the UFO Review is available at https://ibm.box.com/s/v1nyjnv8pqriee1ljdb3n76mt42uk0nj

Notes from Part 2 of the UFO Review:

Page 27 - question: what do users who depend on j2eeManagement-1.1 do when they migrate to EE 9? Answer: Don’t use it.

Page 28 - TODO: need a plan for lack of tooling support

Page 29 - TODO: j2eeManagement-1.1 feature does not need to be stabilized - it can still be updated for EE 8 users.

Page 30 - TODO: need to ensure that we test JMX names for standard Java MBean names, etc. - ensure that they still look the same in EE 9

Page 32 - 
* Could Beta be CI?  No, since we don’t implement all optional specs.  
* Could Beta be compatible on Day 1? Possibly, but unlikely
* Can we have a beta ready for Think?  No, but maybe a statement of direction.
* Will it be in May beta?  Or June beta? Not May.  Maybe June - also depends on creation of Open Liberty beta program (currently only WebSphere Liberty has beta releases)
* Can we release a beta of Jakarta EE 9 before the EE 9 community publishes a release candidate? Yes
* Can we push individual child spec implementations to beta, or wait for all to be ready to beta?  Individual - get them out asap. Individual features should decide when to beta.

Page 34 - 
* New deployment descriptions. Do we want new tests with the new deployment descriptors? Yes - probably more of a functional test than system test.
* Does Transformer update the deployment descriptors for app code?  Andy G: yes, it should update deployment descriptors.  Nate: it might not be updating the package types in the descriptors...
* Will system test be using the transformer tool?  Most likely, but Kevin to follow up.

Page 35 -
* Process footprint is increasing because some components are implementing both versions (EE 8 and 9) which brings in the EE 8 APIs into an EE 9 runtime (and vice-versa).  TODO: Will take this offline.

Page 36 - will Glassfish certify on Java 8? Unknown.

Page 40 - 
* Will Eclipse / Intelli-J / VSCode / etc. support the transformer?  Unknown
* Alasdair: we’ll probably want a binary transformer in addition to a source transformer for customer apps.
* What if somebody like MQ creates a provider RAR that contains both EE 8 (javax) and EE 9 (jakarta) - do we still transform?  Andy G/Glenn M: That’s a really bad idea - we shouldn’t allow them to.  Can we put this in the spec? Possibly.  TODO: Alasdair to discuss with MQ with Kevin, Nate R, and Fred.
* Dalia: Should Transformer go into existing Migration Toolkit? Alasdair: Leave it as a maven/gradle tool - don’t put it in Liberty migration tools. Andy G: Transformer is just temporary - users eventually need to update their code.

Final thoughts:
Alasdair - features that we build on top of EE 9 - new feature or it needs to go in.
Jared (after the call ended) - Migration slide should include detect that previous server.xml had convenience feature and their app is using jaxws or jaxb which is now optional and not in the EE 9 convenience feature, that the migration tools should point out to add the jaxws or jaxb if migrating from Jakarta 8 to 9.

**Comment by andymc12** [comment]
Video recording for Part 2 of the UFO Review is available at
https://ibm.box.com/s/e4z3st37tkbnevoyumfkkhmqktslyu2b

**Comment by kwsutter** [comment]
EJB effort is being tracked via https://github.com/OpenLiberty/open-liberty/issues/11450.

**Comment by jhanders34** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval:

1.  UFO -- does the UFO identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?
```
Yes ones are identified and yes they are implemented.  The ones identified are:

- With short name changes of features, a new message is output if you specify jca-2.0 instead of connectors-2.0 for instance.
- If Jakarta EE 9 features cause a conflict, none of the features will start so that things are not in a partially started state.
- Value-add features that do not work with Jakarta EE 9 give a message indicating that they are not working because they conflict with Jakarta EE 9 features.
```
2.  Test and Demo -- As part of the serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
- Starting server with the wrong shortname, but correctly version number for Jakarta EE 9 feature.  Used jsp-3.0
- Started with a combination of EE8 and EE9 features and showed that no features started because of the conflict.
- Started server with openapi-3.1 with EE9 features and showed that it didn't start and indicated the openapi-3.1 was not compatible with Jakarta EE 9.

b) Who did you demo to?   `Emmanuel Ramos`
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?  `Yes`

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature? `Brian Hanczaryk, Jagadeeswar Gangaraju, Monica Tamboli, Rumana Haque, Tam Dinh, Tatiana A Kulik`
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  `Yes, serviceability of any problems encountered was sufficient to avoid PMRs or L2 should be able to quickly address the problems without L3.`

4.  Which L2 / L3 queues will handle PMRs for this feature?  Ensure they are present in the contact reference file and in the queue contact summary, and that the respective L2/L3 teams know they are supporting it.  Ask Don Bourne if you need links or more info.
```
This feature has the same L2/L3 teams supporting it as the Jakarta EE 8 features.
```
5.  Does this feature add any new metrics or emit any new JSON events?  If yes, have you updated the JMX metrics reference list / Metrics reference list / JSON log events reference list in the Open Liberty docs?
```
The same metrics that exist for Jakarta EE 8 are relevant for Jakarta EE 9 features 
as well.  There are no new ones that are added.
```

**Comment by malincoln** [comment]
@steven1046 can you review for accessibility approval? Thanks

**Comment by malincoln** [comment]
@tevans78 @cbridgha demo scheduled for Nov 9th.

**Comment by chirp1** [comment]
Reviewed the doc issues and discussed them with David. OL writers created doc epic at https://github.com/OpenLiberty/docs/issues/4863 #4626 #4825 #4855. #4626 has enough info for this #9876 epic. I approved the epic for #4825. #4855 is going into 22.0.0.1 for a different epic. Approving this epic, #9876.

**Comment by jhanders34** [comment]
@skasund, I uploaded an STE to https://ibm.ent.box.com/file/884337813451
